# Generated by Django 5.2.4 on 2026-05-24 18:44

import apps.core.uuid
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0017_alter_capabilitytoken_token_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantillaNotificacion',
            fields=[
                ('id_plantilla', models.UUIDField(default=apps.core.uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('codigo_plantilla', models.CharField(db_index=True, max_length=50, unique=True)),
                ('asunto', models.CharField(max_length=200)),
                ('cuerpo_html', models.TextField()),
                ('canal', models.CharField(choices=[('IN_APP', 'En aplicación'), ('EMAIL', 'Correo electrónico')], max_length=10)),
                ('variables_json', models.JSONField(blank=True, default=list, help_text='Lista de variables requeridas, ej: ["nombre_cliente", "numero_pedido"]')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plantilla de Notificación',
                'verbose_name_plural': 'Plantillas de Notificaciones',
                'db_table': 'notificaciones_plantilla',
                'ordering': ['codigo_plantilla'],
            },
        ),
        migrations.CreateModel(
            name='EventoNotificacion',
            fields=[
                ('id_evento', models.UUIDField(default=apps.core.uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('codigo_evento', models.CharField(db_index=True, max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_notificacion', to='core.empresa')),
            ],
            options={
                'verbose_name': 'Evento de Notificación',
                'verbose_name_plural': 'Eventos de Notificación',
                'db_table': 'notificaciones_evento',
                'unique_together': {('codigo_evento', 'id_empresa')},
            },
        ),
        migrations.CreateModel(
            name='LogNotificacion',
            fields=[
                ('id_log', models.UUIDField(default=apps.core.uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('destinatario', models.CharField(help_text='Email o user_id del destinatario', max_length=200)),
                ('canal', models.CharField(choices=[('IN_APP', 'En aplicación'), ('EMAIL', 'Correo electrónico')], max_length=10)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ENVIADO', 'Enviado'), ('FALLIDO', 'Fallido')], default='PENDIENTE', max_length=20)),
                ('intentos', models.IntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('id_plantilla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='notificaciones.plantillanotificacion')),
            ],
            options={
                'verbose_name': 'Log de Notificación',
                'verbose_name_plural': 'Logs de Notificaciones',
                'db_table': 'notificaciones_log',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='SuscripcionNotificacion',
            fields=[
                ('id_suscripcion', models.UUIDField(default=apps.core.uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('canal', models.CharField(choices=[('IN_APP', 'En aplicación'), ('EMAIL', 'Correo electrónico')], max_length=10)),
                ('activo', models.BooleanField(default=True)),
                ('id_evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suscripciones', to='notificaciones.eventonotificacion')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suscripciones_notificacion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Suscripción de Notificación',
                'verbose_name_plural': 'Suscripciones de Notificaciones',
                'db_table': 'notificaciones_suscripcion',
                'unique_together': {('id_evento', 'id_usuario', 'canal')},
            },
        ),
    ]
