# Generated by Django 5.2.4 on 2026-05-29 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_alter_capabilitytoken_token_and_more"),
        ("cxc", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="acuerdopago",
            new_name="cxc_acuerdo_empresa_942c39_idx",
            old_name="cxc_acuerdo_empresa_cli_est_idx",
        ),
        migrations.RenameIndex(
            model_name="acuerdopago",
            new_name="cxc_acuerdo_empresa_40dc4f_idx",
            old_name="cxc_acuerdo_empresa_estado_idx",
        ),
        migrations.RenameIndex(
            model_name="cuotaacuerdo",
            new_name="cxc_cuotaac_acuerdo_91e747_idx",
            old_name="cxc_cuota_acuerdo_fecha_est_idx",
        ),
        migrations.RenameIndex(
            model_name="gestioncobranza",
            new_name="cxc_gestion_empresa_9ee974_idx",
            old_name="cxc_gestion_empresa_cliente_idx",
        ),
        migrations.RenameIndex(
            model_name="gestioncobranza",
            new_name="cxc_gestion_empresa_c0a56c_idx",
            old_name="cxc_gestion_empresa_prox_idx",
        ),
        migrations.RenameIndex(
            model_name="gestioncobranza",
            new_name="cxc_gestion_empresa_4f5be6_idx",
            old_name="cxc_gestion_empresa_res_fecha_idx",
        ),
        migrations.RenameIndex(
            model_name="lotefraccionado",
            new_name="cxc_lotefra_empresa_71711d_idx",
            old_name="cxc_lote_empresa_estado_idx",
        ),
        migrations.RenameIndex(
            model_name="plantillacobranza",
            new_name="cxc_plantil_empresa_9f4941_idx",
            old_name="cxc_planti_empresa_canal_activa_idx",
        ),
        migrations.AlterField(
            model_name="acuerdopago",
            name="empresa",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="core.empresa",
            ),
        ),
        migrations.AlterField(
            model_name="gestioncobranza",
            name="empresa",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="core.empresa",
            ),
        ),
        migrations.AlterField(
            model_name="lotefraccionado",
            name="empresa",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="core.empresa",
            ),
        ),
        migrations.AlterField(
            model_name="plantillacobranza",
            name="empresa",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="core.empresa",
            ),
        ),
        migrations.AlterField(
            model_name="ventafraccionada",
            name="empresa",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="core.empresa",
            ),
        ),
    ]
