# Generated by Django 5.2.4 on 2025-08-02 20:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('id_almacen', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_almacen', models.CharField(max_length=100)),
                ('codigo_almacen', models.CharField(max_length=20, unique=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('referencia_externa', models.CharField(blank=True, max_length=100, null=True)),
                ('documento_json', models.JSONField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UbicacionAlmacen',
            fields=[
                ('id_ubicacion', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo_ubicacion', models.CharField(max_length=50, unique=True)),
                ('nombre_ubicacion', models.CharField(max_length=100)),
                ('tipo_ubicacion', models.CharField(choices=[('ESTANTERIA', 'Estantería'), ('PISO', 'Piso'), ('REFRIGERADO', 'Refrigerado'), ('CONGELADO', 'Congelado'), ('EXTERIOR', 'Exterior'), ('CUARENTENA', 'Cuarentena'), ('DEVOLUCION', 'Devolución'), ('PICKING', 'Picking'), ('RECEPCION', 'Recepción'), ('DESPACHO', 'Despacho')], max_length=20)),
                ('pasillo', models.CharField(blank=True, max_length=10, null=True)),
                ('estante', models.CharField(blank=True, max_length=10, null=True)),
                ('nivel', models.CharField(blank=True, max_length=10, null=True)),
                ('posicion', models.CharField(blank=True, max_length=10, null=True)),
                ('capacidad_maxima', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('unidad_capacidad', models.CharField(blank=True, max_length=20, null=True)),
                ('temperatura_minima', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('temperatura_maxima', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('requiere_autorizacion', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ubicación de Almacén',
                'verbose_name_plural': 'Ubicaciones de Almacén',
                'db_table': 'almacenes_ubicacion_almacen',
            },
        ),
    ]
