# Generated by Django 5.2.4 on 2025-08-02 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('almacenes', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='almacen',
            name='id_empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa'),
        ),
        migrations.AddField(
            model_name='almacen',
            name='id_sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.sucursal'),
        ),
        migrations.AddField(
            model_name='ubicacionalmacen',
            name='id_almacen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ubicaciones', to='almacenes.almacen'),
        ),
        migrations.AddField(
            model_name='ubicacionalmacen',
            name='id_empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ubicaciones_almacen', to='core.empresa'),
        ),
        migrations.AlterUniqueTogether(
            name='ubicacionalmacen',
            unique_together={('id_almacen', 'codigo_ubicacion')},
        ),
    ]
