# Generated by Django 5.2.4 on 2026-05-19 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacenes', '0002_initial'),
        ('core', '0016_fix_unique_numeros_documento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='almacen',
            options={'verbose_name': 'Almacén', 'verbose_name_plural': 'Almacenes'},
        ),
        migrations.AlterField(
            model_name='almacen',
            name='codigo_almacen',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='ubicacionalmacen',
            name='codigo_ubicacion',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='almacen',
            unique_together={('id_empresa', 'codigo_almacen')},
        ),
        migrations.AlterModelTable(
            name='almacen',
            table='almacenes_almacen',
        ),
    ]
