# Generated by Django 5.2.4 on 2025-08-02 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contabilidad', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asientocontable',
            name='id_empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa'),
        ),
        migrations.AddField(
            model_name='detalleasiento',
            name='id_asiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contabilidad.asientocontable'),
        ),
        migrations.AddField(
            model_name='plancuentas',
            name='id_cuenta_padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contabilidad.plancuentas'),
        ),
        migrations.AddField(
            model_name='plancuentas',
            name='id_empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa'),
        ),
        migrations.AddField(
            model_name='detalleasiento',
            name='id_cuenta_contable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contabilidad.plancuentas'),
        ),
    ]
