# Generated by Django 5.2.4 on 2026-05-19 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0003_add_mapeo_contable'),
        ('core', '0016_fix_unique_numeros_documento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asientocontable',
            options={'verbose_name': 'Asiento Contable', 'verbose_name_plural': 'Asientos Contables'},
        ),
        migrations.AlterModelOptions(
            name='plancuentas',
            options={'verbose_name': 'Plan de Cuentas', 'verbose_name_plural': 'Planes de Cuentas'},
        ),
        migrations.AlterField(
            model_name='asientocontable',
            name='numero_asiento',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mapeocontable',
            name='cuenta_debe',
            field=models.ForeignKey(help_text='Cuenta que va al Debe en este tipo de asiento.', on_delete=django.db.models.deletion.PROTECT, related_name='mapeos_debe', to='contabilidad.plancuentas'),
        ),
        migrations.AlterField(
            model_name='mapeocontable',
            name='cuenta_haber',
            field=models.ForeignKey(help_text='Cuenta que va al Haber en este tipo de asiento.', on_delete=django.db.models.deletion.PROTECT, related_name='mapeos_haber', to='contabilidad.plancuentas'),
        ),
        migrations.AlterField(
            model_name='mapeocontable',
            name='descripcion_plantilla',
            field=models.CharField(default='{tipo} - {numero}', help_text='Plantilla de descripción. Use {tipo}, {numero}.', max_length=255),
        ),
        migrations.AlterField(
            model_name='plancuentas',
            name='codigo_cuenta',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='asientocontable',
            unique_together={('id_empresa', 'numero_asiento')},
        ),
        migrations.AlterUniqueTogether(
            name='plancuentas',
            unique_together={('id_empresa', 'codigo_cuenta')},
        ),
        migrations.AlterModelTable(
            name='asientocontable',
            table='contabilidad_asiento_contable',
        ),
        migrations.AlterModelTable(
            name='plancuentas',
            table='contabilidad_plan_cuentas',
        ),
    ]
