# Generated by Django 5.2.4 on 2026-06-02 03:16

import apps.core.uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contabilidad", "0004_fix_unique_plan_cuentas_asientos"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asientocontable",
            name="id_asiento",
            field=models.UUIDField(
                default=apps.core.uuid.uuid7, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="detalleasiento",
            name="id_detalle_asiento",
            field=models.UUIDField(
                default=apps.core.uuid.uuid7, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="mapeocontable",
            name="id_mapeo",
            field=models.UUIDField(
                default=apps.core.uuid.uuid7,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="plancuentas",
            name="id_cuenta_contable",
            field=models.UUIDField(
                default=apps.core.uuid.uuid7, primary_key=True, serialize=False
            ),
        ),
    ]
