# Generated by Django 5.2.15 on 2026-06-23 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0012_asientocontable_id_usuario_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapeocontable',
            name='tipo_asiento',
            field=models.CharField(choices=[('FACTURA_VENTA', 'Factura de Venta'), ('DEVOLUCION_VENTA', 'Devolución de Venta'), ('DEVOLUCION_VENTA_IVA', 'IVA de Devolución de Venta'), ('FACTURA_COMPRA', 'Factura de Compra'), ('RECEPCION_MERCANCIA', 'Recepción de Mercancía'), ('COSTO_VENTA', 'Costo de Ventas (COGS)'), ('AJUSTE_INVENTARIO', 'Ajuste de Inventario'), ('SALIDA_INTERNA', 'Salida Interna / Requisición'), ('PAGO_CXC', 'Pago de Cuenta por Cobrar'), ('PAGO_CXP', 'Pago de Cuenta por Pagar'), ('NOMINA', 'Proceso de Nómina'), ('CAMBIO_DIVISA', 'Cambio de Divisa'), ('PAGO_TERCERO', 'Pago de Terceros'), ('PAGO_PARAFISCAL', 'Pago de Contribución Parafiscal')], max_length=30),
        ),
    ]
