# Generated by Django 5.2.4 on 2025-09-05 02:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ENVIADO', 'Enviado'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('ANULADO', 'Anulado')], default='PENDIENTE', max_length=30),
        ),
        migrations.CreateModel(
            name='PagoPedido',
            fields=[
                ('id_pago_pedido', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metodo', models.CharField(max_length=50)),
                ('moneda', models.CharField(max_length=10)),
                ('monto', models.DecimalField(decimal_places=4, max_digits=18)),
                ('tasa', models.DecimalField(decimal_places=4, default=1, max_digits=18)),
                ('referencia', models.CharField(blank=True, max_length=100, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('id_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='ventas.pedido')),
            ],
        ),
    ]
