# Generated by Django 5.2.4 on 2025-11-05 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0007_add_caja_usuario'),
        ('ventas', '0002_alter_pedido_estado_pagopedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagopedido',
            name='id_caja',
            field=models.ForeignKey(blank=True, help_text='Caja donde se registrará el movimiento.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_pedidos', to='finanzas.caja'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='id_caja',
            field=models.ForeignKey(blank=True, help_text='Caja asociada al pedido para sugerir en pagos.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='finanzas.caja'),
        ),
    ]
