# Generated by Django 5.2.4 on 2025-11-07 02:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_empresa_id_moneda_pais_empresa_pais_codigo_iso_and_more'),
        ('crm', '0001_initial'),
        ('finanzas', '0007_add_caja_usuario'),
        ('inventario', '0001_initial'),
        ('ventas', '0003_pagopedido_id_caja_pedido_id_caja'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='id_cliente',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='id_empresa',
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='convertido_a_pedido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='documento_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='id_cotizacion_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones_derivadas', to='ventas.cotizacion'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='id_pedido_resultante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizacion_origen', to='ventas.pedido'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='referencia_externa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='devolucionventa',
            name='id_nota_credito_generada',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devolucion_origen', to='ventas.notacreditoventa'),
        ),
        migrations.AddField(
            model_name='notaventa',
            name='convertido_a_factura',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notaventa',
            name='id_pedido_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_venta_derivadas', to='ventas.pedido'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='convertido_a_nota_venta',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pedido',
            name='id_cotizacion_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_derivados', to='ventas.cotizacion'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='id_nota_venta_resultante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedido_origen', to='ventas.notaventa'),
        ),
        migrations.CreateModel(
            name='FacturaFiscal',
            fields=[
                ('id_factura', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_control', models.CharField(help_text='Número de control compartido con notas de crédito', max_length=50, unique=True)),
                ('numero_factura', models.CharField(help_text='Número individual de la factura', max_length=50, unique=True)),
                ('fecha_emision', models.DateField()),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('base_imponible', models.DecimalField(decimal_places=4, default=0.0, max_digits=18)),
                ('monto_iva', models.DecimalField(decimal_places=4, default=0.0, max_digits=18)),
                ('monto_total', models.DecimalField(decimal_places=4, max_digits=18)),
                ('tasa_cambio', models.DecimalField(decimal_places=4, default=1.0, max_digits=18)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('EMITIDA', 'Emitida'), ('VENCIDA', 'Vencida'), ('PAGADA', 'Pagada')], default='BORRADOR', max_length=20)),
                ('afecta_inventario_fiscal', models.BooleanField(default=True)),
                ('referencia_externa', models.CharField(blank=True, max_length=100, null=True)),
                ('documento_json', models.JSONField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.cliente')),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
                ('id_moneda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas_fiscales', to='finanzas.moneda')),
                ('id_nota_venta_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas_derivadas', to='ventas.notaventa')),
            ],
            options={
                'verbose_name': 'Factura Fiscal',
                'verbose_name_plural': 'Facturas Fiscales',
                'db_table': 'ventas_factura_fiscal',
            },
        ),
        migrations.CreateModel(
            name='DetalleFacturaFiscal',
            fields=[
                ('id_detalle_factura', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=18)),
                ('precio_unitario', models.DecimalField(decimal_places=4, max_digits=18)),
                ('descuento_porcentaje', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('descuento_monto', models.DecimalField(decimal_places=4, default=0.0, max_digits=18)),
                ('subtotal', models.DecimalField(decimal_places=4, max_digits=18)),
                ('monto_impuesto', models.DecimalField(decimal_places=4, default=0.0, max_digits=18)),
                ('total_linea', models.DecimalField(decimal_places=4, max_digits=18)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_factura_fiscal', to='inventario.producto')),
                ('id_variante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalles_factura_fiscal', to='inventario.varianteproducto')),
                ('id_factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ventas.facturafiscal')),
            ],
            options={
                'verbose_name': 'Detalle de Factura Fiscal',
                'verbose_name_plural': 'Detalles de Factura Fiscal',
                'db_table': 'ventas_detalle_factura_fiscal',
            },
        ),
        migrations.AddField(
            model_name='notaventa',
            name='id_factura_resultante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nota_venta_origen', to='ventas.facturafiscal'),
        ),
        migrations.AlterField(
            model_name='devolucionventa',
            name='id_factura_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devoluciones', to='ventas.facturafiscal'),
        ),
        migrations.AlterField(
            model_name='notacreditoventa',
            name='id_factura_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notas_credito_venta', to='ventas.facturafiscal'),
        ),
        migrations.CreateModel(
            name='NotaCreditoFiscal',
            fields=[
                ('id_nota_credito_fiscal', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_control', models.CharField(help_text='Número de control compartido con la factura', max_length=50)),
                ('numero_nota_credito', models.CharField(help_text='Número individual de la nota de crédito', max_length=50, unique=True)),
                ('fecha_emision', models.DateField()),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('base_imponible', models.DecimalField(decimal_places=4, default=0.0, max_digits=18)),
                ('monto_iva', models.DecimalField(decimal_places=4, default=0.0, max_digits=18)),
                ('monto_total', models.DecimalField(decimal_places=4, max_digits=18)),
                ('tasa_cambio', models.DecimalField(decimal_places=4, default=1.0, max_digits=18)),
                ('motivo', models.CharField(choices=[('DEVOLUCION', 'Devolución'), ('DESCUENTO', 'Descuento'), ('ERROR_FACTURACION', 'Error de Facturación'), ('ANULACION', 'Anulación'), ('AJUSTE_PRECIO', 'Ajuste de Precio'), ('OTRO', 'Otro')], max_length=20)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('EMITIDA', 'Emitida'), ('APLICADA', 'Aplicada'), ('ANULADA', 'Anulada')], default='BORRADOR', max_length=20)),
                ('afecta_inventario_fiscal', models.BooleanField(default=True)),
                ('referencia_externa', models.CharField(blank=True, max_length=100, null=True)),
                ('documento_json', models.JSONField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.cliente')),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
                ('id_factura_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_credito_fiscal', to='ventas.facturafiscal')),
                ('id_moneda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_credito_fiscal', to='finanzas.moneda')),
            ],
            options={
                'verbose_name': 'Nota de Crédito Fiscal',
                'verbose_name_plural': 'Notas de Crédito Fiscal',
                'db_table': 'ventas_nota_credito_fiscal',
            },
        ),
        migrations.CreateModel(
            name='DetalleNotaCreditoFiscal',
            fields=[
                ('id_detalle_nota_credito', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=18)),
                ('precio_unitario', models.DecimalField(decimal_places=4, max_digits=18)),
                ('descuento_porcentaje', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('descuento_monto', models.DecimalField(decimal_places=4, default=0.0, max_digits=18)),
                ('subtotal', models.DecimalField(decimal_places=4, max_digits=18)),
                ('monto_impuesto', models.DecimalField(decimal_places=4, default=0.0, max_digits=18)),
                ('total_linea', models.DecimalField(decimal_places=4, max_digits=18)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_nota_credito_fiscal', to='inventario.producto')),
                ('id_variante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalles_nota_credito_fiscal', to='inventario.varianteproducto')),
                ('id_nota_credito_fiscal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ventas.notacreditofiscal')),
            ],
            options={
                'verbose_name': 'Detalle de Nota de Crédito Fiscal',
                'verbose_name_plural': 'Detalles de Nota de Crédito Fiscal',
                'db_table': 'ventas_detalle_nota_credito_fiscal',
            },
        ),
        migrations.DeleteModel(
            name='DetalleFactura',
        ),
        migrations.DeleteModel(
            name='Factura',
        ),
    ]
