# Generated by Django 5.2.4 on 2025-11-08 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0011_alter_caja_options_alter_cajausuario_options_and_more'),
        ('ventas', '0004_remove_factura_id_cliente_remove_factura_id_empresa_and_more'),
    ]

    operations = [
        # Limpiar referencias a cajas virtuales antes de cambiar el tipo de campo
        migrations.RunSQL(
            "UPDATE ventas_pagopedido SET id_caja_id = NULL WHERE id_caja_id IS NOT NULL;",
            reverse_sql=migrations.RunSQL.noop
        ),
        migrations.RunSQL(
            "UPDATE ventas_pedido SET id_caja_id = NULL WHERE id_caja_id IS NOT NULL;",
            reverse_sql=migrations.RunSQL.noop
        ),
        migrations.AlterField(
            model_name='pagopedido',
            name='id_caja',
            field=models.ForeignKey(blank=True, help_text='Caja física donde se registrará el movimiento.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_pedidos', to='finanzas.cajafisica'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='id_caja',
            field=models.ForeignKey(blank=True, help_text='Caja física asociada al pedido para sugerir en pagos.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='finanzas.cajafisica'),
        ),
    ]
