# Generated by Django 5.2.4 on 2025-11-08 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0011_alter_caja_options_alter_cajausuario_options_and_more'),
        ('ventas', '0005_alter_pagopedido_id_caja_alter_pedido_id_caja'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagopedido',
            name='id_caja',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='id_caja',
        ),
        migrations.AddField(
            model_name='pagopedido',
            name='id_caja_fisica',
            field=models.ForeignKey(blank=True, help_text='Caja física donde se realizó el pago.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_pedidos', to='finanzas.cajafisica'),
        ),
        migrations.AddField(
            model_name='pagopedido',
            name='id_caja_virtual',
            field=models.ForeignKey(blank=True, help_text='Caja virtual que controla el ingreso/egreso financiero.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_pedidos_virtuales', to='finanzas.caja'),
        ),
        migrations.AddField(
            model_name='pagopedido',
            name='id_cuenta_bancaria',
            field=models.ForeignKey(blank=True, help_text='Cuenta bancaria para pagos electrónicos.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_pedidos', to='finanzas.cuentabancariaempresa'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='id_caja_fisica',
            field=models.ForeignKey(blank=True, help_text='Caja física donde se realizó el pedido.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='finanzas.cajafisica'),
        ),
    ]
