# Generated by Django 5.2.4 on 2025-11-08 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0017_transacciondatafono_estado_and_more'),
        ('ventas', '0006_remove_pagopedido_id_caja_remove_pedido_id_caja_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagopedido',
            name='banco_destino',
            field=models.ForeignKey(blank=True, help_text='Banco destino para métodos electrónicos/tarjeta.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_pedidos_destino', to='finanzas.cuentabancariaempresa'),
        ),
        migrations.AddField(
            model_name='pagopedido',
            name='id_datafono',
            field=models.ForeignKey(blank=True, help_text='Datafono utilizado para pagos con tarjeta.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_pedidos', to='finanzas.datafono'),
        ),
    ]
