# Generated by Django 5.2.4 on 2026-05-11 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_usuarios_es_superusuario_omni'),
        ('crm', '0003_alter_cliente_options'),
        ('finanzas', '0034_fix_sesion_caja_unique_constraint'),
        ('ventas', '0007_pagopedido_banco_destino_pagopedido_id_datafono'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagopedido',
            name='banco_destino',
        ),
        migrations.RemoveField(
            model_name='pagopedido',
            name='id_caja_fisica',
        ),
        migrations.RemoveField(
            model_name='pagopedido',
            name='id_caja_virtual',
        ),
        migrations.RemoveField(
            model_name='pagopedido',
            name='id_cuenta_bancaria',
        ),
        migrations.RemoveField(
            model_name='pagopedido',
            name='id_datafono',
        ),
        migrations.RemoveField(
            model_name='pagopedido',
            name='id_pedido',
        ),
        migrations.AlterModelOptions(
            name='detallenotaventa',
            options={'verbose_name': 'Detalle de Nota de Venta', 'verbose_name_plural': 'Detalles de Nota de Venta'},
        ),
        migrations.AlterModelOptions(
            name='detallepedido',
            options={'verbose_name': 'Detalle de Pedido', 'verbose_name_plural': 'Detalles de Pedido'},
        ),
        migrations.AlterModelOptions(
            name='notaventa',
            options={'ordering': ['-fecha_nota'], 'verbose_name': 'Nota de Venta', 'verbose_name_plural': 'Notas de Venta'},
        ),
        migrations.AlterModelOptions(
            name='pedido',
            options={'ordering': ['-fecha_pedido'], 'verbose_name': 'Pedido', 'verbose_name_plural': 'Pedidos'},
        ),
        migrations.AlterField(
            model_name='facturafiscal',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('EMITIDA', 'Emitida'), ('VENCIDA', 'Vencida'), ('PAGADA', 'Pagada'), ('ANULADA', 'Anulada')], default='BORRADOR', max_length=20),
        ),
        migrations.AddIndex(
            model_name='notaventa',
            index=models.Index(fields=['id_empresa', 'estado'], name='ventas_nota_id_empr_861a38_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['id_empresa', 'estado'], name='ventas_pedi_id_empr_79aa5c_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['fecha_pedido'], name='ventas_pedi_fecha_p_ea00b5_idx'),
        ),
        migrations.AlterModelTable(
            name='detallenotaventa',
            table='ventas_detalle_nota_venta',
        ),
        migrations.AlterModelTable(
            name='detallepedido',
            table='ventas_detalle_pedido',
        ),
        migrations.AlterModelTable(
            name='notaventa',
            table='ventas_nota_venta',
        ),
        migrations.AlterModelTable(
            name='pedido',
            table='ventas_pedido',
        ),
        migrations.DeleteModel(
            name='PagoPedido',
        ),
    ]
