# Generated by Django 5.2.4 on 2026-05-19 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_fix_unique_numeros_documento'),
        ('ventas', '0009_listaprecio_detalleprecio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listaprecio',
            name='codigo',
            field=models.CharField(help_text='Código corto, ej: LISTA1, LISTA2, MAYOREO', max_length=20),
        ),
        migrations.AlterField(
            model_name='listaprecio',
            name='es_referencia',
            field=models.BooleanField(default=False, help_text='Lista 1: precio base visible en todos los documentos CxC.'),
        ),
        migrations.AlterField(
            model_name='notacreditoventa',
            name='numero_nota_credito',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='notaventa',
            name='numero_nota',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='numero_pedido',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='notacreditoventa',
            unique_together={('id_empresa', 'numero_nota_credito')},
        ),
        migrations.AlterUniqueTogether(
            name='notaventa',
            unique_together={('id_empresa', 'numero_nota')},
        ),
        migrations.AlterUniqueTogether(
            name='pedido',
            unique_together={('id_empresa', 'numero_pedido')},
        ),
    ]
