# Generated by Django 5.2.4 on 2026-05-19 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_fix_unique_numeros_documento'),
        ('ventas', '0010_fix_unique_numeros_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='numero_cotizacion',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='devolucionventa',
            name='numero_devolucion',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='facturafiscal',
            name='numero_control',
            field=models.CharField(help_text='Número de control compartido con notas de crédito', max_length=50),
        ),
        migrations.AlterField(
            model_name='facturafiscal',
            name='numero_factura',
            field=models.CharField(help_text='Número individual de la factura', max_length=50),
        ),
        migrations.AlterField(
            model_name='notacreditofiscal',
            name='numero_nota_credito',
            field=models.CharField(help_text='Número individual de la nota de crédito', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='cotizacion',
            unique_together={('id_empresa', 'numero_cotizacion')},
        ),
        migrations.AlterUniqueTogether(
            name='devolucionventa',
            unique_together={('id_empresa', 'numero_devolucion')},
        ),
        migrations.AlterUniqueTogether(
            name='facturafiscal',
            unique_together={('id_empresa', 'numero_control'), ('id_empresa', 'numero_factura')},
        ),
        migrations.AlterUniqueTogether(
            name='notacreditofiscal',
            unique_together={('id_empresa', 'numero_nota_credito')},
        ),
    ]
