# Generated by Django 5.2.15 on 2026-06-12 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ventas", "0014_rls_piloto_ventas"),
    ]

    operations = [
        migrations.AddField(
            model_name="devolucionventa",
            name="id_nota_venta_origen",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="devoluciones",
                to="ventas.notaventa",
            ),
        ),
    ]
