# Generated by Django 5.2.15 on 2026-06-12 22:55

import apps.core.uuid
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_claveidempotencia_usuario_ttl"),
        ("finanzas", "0039_alter_cajavirtualauto_caja_fisica"),
        ("inventario", "0009_producto_punto_reorden"),
        ("ventas", "0015_rls_lote3_ventas"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="notaventa",
            name="id_vendedor",
            field=models.ForeignKey(
                blank=True,
                help_text="Vendedor de la venta; al entregar se devenga su comisión.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="notas_venta_como_vendedor",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="pedido",
            name="id_vendedor",
            field=models.ForeignKey(
                blank=True,
                help_text="Vendedor que tomó el pedido (base del cálculo de comisiones).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pedidos_como_vendedor",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="EsquemaComision",
            fields=[
                (
                    "id_esquema_comision",
                    models.UUIDField(
                        default=apps.core.uuid.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "porcentaje_base",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Porcentaje de comisión sobre el subtotal sin impuestos (0–100).",
                        max_digits=7,
                    ),
                ),
                ("vigente_desde", models.DateField(blank=True, null=True)),
                ("vigente_hasta", models.DateField(blank=True, null=True)),
                ("activo", models.BooleanField(default=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "id_empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="esquemas_comision",
                        to="core.empresa",
                    ),
                ),
                (
                    "vendedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="esquemas_comision",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Esquema de Comisión",
                "verbose_name_plural": "Esquemas de Comisión",
                "db_table": "ventas_esquema_comision",
            },
        ),
        migrations.CreateModel(
            name="ComisionVenta",
            fields=[
                (
                    "id_comision_venta",
                    models.UUIDField(
                        default=apps.core.uuid.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "base_comisionable",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Subtotal sin impuestos de la nota.",
                        max_digits=18,
                    ),
                ),
                ("monto", models.DecimalField(decimal_places=4, max_digits=18)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("DEVENGADA", "Devengada"),
                            ("LIQUIDADA", "Liquidada"),
                            ("ANULADA", "Anulada"),
                        ],
                        default="DEVENGADA",
                        max_length=20,
                    ),
                ),
                ("fecha_devengo", models.DateField()),
                ("fecha_liquidacion", models.DateField(blank=True, null=True)),
                ("detalle_json", models.JSONField(blank=True, null=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "id_empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comisiones_venta",
                        to="core.empresa",
                    ),
                ),
                (
                    "id_moneda",
                    models.ForeignKey(
                        blank=True,
                        help_text="Moneda base de la empresa al momento del devengo.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="comisiones_venta",
                        to="finanzas.moneda",
                    ),
                ),
                (
                    "liquidada_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="comisiones_liquidadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "nota_venta",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="comision_venta",
                        to="ventas.notaventa",
                    ),
                ),
                (
                    "vendedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="comisiones_venta",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "esquema",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="comisiones",
                        to="ventas.esquemacomision",
                    ),
                ),
            ],
            options={
                "verbose_name": "Comisión de Venta",
                "verbose_name_plural": "Comisiones de Venta",
                "db_table": "ventas_comision_venta",
                "ordering": ["-fecha_devengo", "-fecha_creacion"],
            },
        ),
        migrations.CreateModel(
            name="EsquemaComisionCategoria",
            fields=[
                (
                    "id_esquema_comision_categoria",
                    models.UUIDField(
                        default=apps.core.uuid.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "porcentaje",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Porcentaje que reemplaza al base para productos de esta categoría (0–100).",
                        max_digits=7,
                    ),
                ),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="overrides_comision",
                        to="inventario.categoriaproducto",
                    ),
                ),
                (
                    "esquema",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="overrides_categoria",
                        to="ventas.esquemacomision",
                    ),
                ),
            ],
            options={
                "verbose_name": "Override de Comisión por Categoría",
                "verbose_name_plural": "Overrides de Comisión por Categoría",
                "db_table": "ventas_esquema_comision_categoria",
            },
        ),
        migrations.AddIndex(
            model_name="esquemacomision",
            index=models.Index(
                fields=["id_empresa", "vendedor", "activo"],
                name="ventas_esqu_id_empr_5d9458_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="esquemacomision",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("porcentaje_base__gte", 0), ("porcentaje_base__lte", 100)
                ),
                name="esquema_comision_porcentaje_0_100",
            ),
        ),
        migrations.AddIndex(
            model_name="comisionventa",
            index=models.Index(
                fields=["id_empresa", "vendedor", "estado"],
                name="ventas_comi_id_empr_eae1db_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="comisionventa",
            index=models.Index(
                fields=["id_empresa", "fecha_devengo"],
                name="ventas_comi_id_empr_f77388_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="esquemacomisioncategoria",
            constraint=models.CheckConstraint(
                condition=models.Q(("porcentaje__gte", 0), ("porcentaje__lte", 100)),
                name="esquema_comision_categoria_porcentaje_0_100",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="esquemacomisioncategoria",
            unique_together={("esquema", "categoria")},
        ),
    ]
