# Generated by Django 5.2.4 on 2025-08-02 20:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FlujoAprobacion',
            fields=[
                ('id_flujo_aprobacion', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('orden_etapa', models.IntegerField()),
                ('nombre_etapa', models.CharField(max_length=100)),
                ('monto_minimo', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('monto_maximo', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('id_usuario_aprobador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('rol_aprobador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.roles')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudAprobacion',
            fields=[
                ('id_solicitud_aprobacion', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('id_entidad_origen', models.UUIDField()),
                ('nombre_modelo_origen', models.CharField(max_length=100)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('estado_solicitud', models.CharField(max_length=50)),
                ('comentarios_solicitante', models.TextField(blank=True, null=True)),
                ('fecha_ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('etapa_actual_flujo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_aprobaciones.flujoaprobacion')),
                ('id_usuario_solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroAprobacion',
            fields=[
                ('id_registro_aprobacion', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_decision', models.DateTimeField(auto_now_add=True)),
                ('tipo_decision', models.CharField(max_length=20)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('id_flujo_aprobacion_etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_aprobaciones.flujoaprobacion')),
                ('id_usuario_aprobador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_solicitud_aprobacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_aprobaciones.solicitudaprobacion')),
            ],
        ),
        migrations.CreateModel(
            name='TipoAprobacion',
            fields=[
                ('id_tipo_aprobacion', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo_tipo', models.CharField(max_length=50, unique=True)),
                ('nombre_tipo', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('modulo_origen', models.CharField(max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
            ],
        ),
        migrations.AddField(
            model_name='solicitudaprobacion',
            name='id_tipo_aprobacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_aprobaciones.tipoaprobacion'),
        ),
        migrations.AddField(
            model_name='flujoaprobacion',
            name='id_tipo_aprobacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_aprobaciones.tipoaprobacion'),
        ),
    ]
