# Generated by Django 5.2.4 on 2026-05-19 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_fix_unique_numeros_documento'),
        ('gestion_aprobaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipoaprobacion',
            options={'verbose_name': 'Tipo de Aprobación', 'verbose_name_plural': 'Tipos de Aprobación'},
        ),
        migrations.AlterField(
            model_name='tipoaprobacion',
            name='codigo_tipo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='tipoaprobacion',
            unique_together={('id_empresa', 'codigo_tipo')},
        ),
        migrations.AlterModelTable(
            name='tipoaprobacion',
            table='gestion_aprobaciones_tipo_aprobacion',
        ),
    ]
