# Generated by Django 5.2.4 on 2026-06-02 03:16

import apps.core.uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion_aprobaciones", "0002_fix_unique_codigo_tipo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flujoaprobacion",
            name="id_flujo_aprobacion",
            field=models.UUIDField(
                default=apps.core.uuid.uuid7,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="registroaprobacion",
            name="id_registro_aprobacion",
            field=models.UUIDField(
                default=apps.core.uuid.uuid7,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="solicitudaprobacion",
            name="id_solicitud_aprobacion",
            field=models.UUIDField(
                default=apps.core.uuid.uuid7,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="tipoaprobacion",
            name="id_tipo_aprobacion",
            field=models.UUIDField(
                default=apps.core.uuid.uuid7,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
