# Generated by Django 5.2.15 on 2026-06-24 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_aprobaciones', '0004_rls_lote3_gestion_aprobaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudaprobacion',
            name='monto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
    ]
