# Generated by Django 5.2.4 on 2026-04-30 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_fix_sesion_caja_unique_constraint'),
        ('manufactura', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centrotrabajo',
            name='codigo_centro',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='operacionproduccion',
            name='codigo_operacion',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='centrotrabajo',
            unique_together={('id_empresa', 'codigo_centro')},
        ),
        migrations.AlterUniqueTogether(
            name='operacionproduccion',
            unique_together={('id_empresa', 'codigo_operacion')},
        ),
    ]
