# Generated by Django 5.2.15 on 2026-06-11 21:54

import apps.core.uuid
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_claveidempotencia"),
        ("manufactura", "0006_uuid_pk_modelos_legacy"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="consumomaterial",
            name="costo_unitario",
            field=models.DecimalField(
                decimal_places=4, default=Decimal("0"), max_digits=18
            ),
        ),
        migrations.CreateModel(
            name="ConfiguracionManufactura",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.uuid.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "porcentaje_overhead",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0"),
                        help_text="Overhead como % sobre (materiales + mano de obra). Ej: 10 = 10%.",
                        max_digits=7,
                    ),
                ),
                (
                    "empresa",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="configuracion_manufactura",
                        to="core.empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuración de Manufactura",
                "verbose_name_plural": "Configuraciones de Manufactura",
                "db_table": "manufactura_configuracion",
            },
        ),
        migrations.CreateModel(
            name="EtapaProduccion",
            fields=[
                (
                    "activo",
                    models.BooleanField(
                        default=True,
                        help_text="Indica si el registro está activo (False = borrado lógico).",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.uuid.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("codigo", models.CharField(max_length=50)),
                ("nombre", models.CharField(max_length=100)),
                (
                    "orden",
                    models.PositiveIntegerField(
                        help_text="Posición en la secuencia de fabricación (1 = primera)."
                    ),
                ),
                (
                    "tarifa_destajo",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0"),
                        help_text="Pago a destajo por unidad procesada en esta etapa (0 = no aplica).",
                        max_digits=18,
                    ),
                ),
                ("descripcion", models.TextField(blank=True, default="")),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="etapas_produccion",
                        to="core.empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Etapa de Producción",
                "verbose_name_plural": "Etapas de Producción",
                "db_table": "manufactura_etapa_produccion",
                "ordering": ["orden"],
                "unique_together": {("empresa", "codigo")},
            },
        ),
        migrations.CreateModel(
            name="EtapaOrdenProduccion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.uuid.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("orden", models.PositiveIntegerField()),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("completada", "Completada"),
                        ],
                        default="pendiente",
                        max_length=20,
                    ),
                ),
                (
                    "horas_trabajadas",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=10
                    ),
                ),
                (
                    "tarifa_hora",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "cantidad_destajo",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0"),
                        help_text="Unidades procesadas pagadas a destajo (tarifa_destajo de la etapa).",
                        max_digits=18,
                    ),
                ),
                (
                    "pago_destajo",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                ("fecha_completada", models.DateTimeField(blank=True, null=True)),
                ("observaciones", models.TextField(blank=True, default="")),
                (
                    "completada_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="etapas_of_completadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "orden_produccion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="etapas",
                        to="manufactura.ordenproduccion",
                    ),
                ),
                (
                    "etapa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="instancias",
                        to="manufactura.etapaproduccion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Etapa de Orden de Producción",
                "verbose_name_plural": "Etapas de Órdenes de Producción",
                "db_table": "manufactura_etapa_orden_produccion",
                "ordering": ["orden"],
                "unique_together": {("orden_produccion", "orden")},
            },
        ),
    ]
