# Generated by Django 5.2.4 on 2026-06-02 03:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_alter_capabilitytoken_token_and_more"),
        ("integration_hub", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="conectorinstancia",
            name="unique_instancia_por_empresa",
        ),
        migrations.RemoveConstraint(
            model_name="entidadsincronizada",
            name="unique_entidad_sync",
        ),
        migrations.RenameIndex(
            model_name="conectorinstancia",
            new_name="integration_id_empr_06b4de_idx",
            old_name="ih_instancia_empresa_estado_idx",
        ),
        migrations.RenameIndex(
            model_name="conectorinstancia",
            new_name="integration_id_empr_5b43cf_idx",
            old_name="ih_instancia_empresa_activo_idx",
        ),
        migrations.RenameIndex(
            model_name="entidadsincronizada",
            new_name="integration_id_inst_e7fcd9_idx",
            old_name="ih_entidad_instancia_tipo_idx",
        ),
        migrations.RenameIndex(
            model_name="entidadsincronizada",
            new_name="integration_id_inst_f72f0e_idx",
            old_name="ih_entidad_instancia_omni_idx",
        ),
        migrations.RenameIndex(
            model_name="jobsincronizacion",
            new_name="integration_id_inst_006411_idx",
            old_name="ih_job_instancia_estado_idx",
        ),
        migrations.RenameIndex(
            model_name="jobsincronizacion",
            new_name="integration_id_inst_c18cdd_idx",
            old_name="ih_job_instancia_tipo_idx",
        ),
        migrations.RenameIndex(
            model_name="logdetallesincronizacion",
            new_name="integration_id_job__6b1293_idx",
            old_name="ih_log_job_operacion_idx",
        ),
        migrations.AlterField(
            model_name="conectorinstancia",
            name="configuracion",
            field=models.JSONField(
                default=dict,
                help_text="Credenciales y configuración de conexión (almacenadas encriptadas).",
            ),
        ),
        migrations.AlterField(
            model_name="conectorinstancia",
            name="entidades_activas",
            field=models.JSONField(
                default=list,
                help_text="Entidades habilitadas para sync: ['contactos', 'productos', ...]",
            ),
        ),
        migrations.AlterField(
            model_name="conectorinstancia",
            name="intervalo_sync_minutos",
            field=models.PositiveIntegerField(
                choices=[
                    (0, "Solo manual"),
                    (15, "Cada 15 minutos"),
                    (30, "Cada 30 minutos"),
                    (60, "Cada hora"),
                    (360, "Cada 6 horas"),
                    (720, "Cada 12 horas"),
                    (1440, "Cada 24 horas"),
                ],
                default=0,
                help_text="0 = solo sincronización manual.",
            ),
        ),
        migrations.AlterField(
            model_name="conectorinstancia",
            name="mensaje_estado",
            field=models.TextField(
                blank=True,
                help_text="Detalle del último error o resultado de test de conexión.",
            ),
        ),
        migrations.AlterField(
            model_name="conectorinstancia",
            name="version_detectada",
            field=models.CharField(
                blank=True,
                help_text="Versión del sistema externo detectada al hacer test de conexión.",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="conectorproveedor",
            name="capacidades",
            field=models.JSONField(
                default=list,
                help_text="Lista de entidades soportadas: ['contactos', 'productos', 'pedidos_venta', 'pedidos_compra', 'facturas', 'pagos', 'inventario']",
            ),
        ),
        migrations.AlterField(
            model_name="conectorproveedor",
            name="versiones_soportadas",
            field=models.JSONField(
                default=list,
                help_text="['8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18']",
            ),
        ),
        migrations.AlterField(
            model_name="entidadsincronizada",
            name="modelo_omni",
            field=models.CharField(
                blank=True, help_text="Ej: apps.ventas.models.Cliente", max_length=150
            ),
        ),
        migrations.AlterField(
            model_name="jobsincronizacion",
            name="iniciado_por",
            field=models.ForeignKey(
                blank=True,
                help_text="Null = iniciado por tarea automática (Celery)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="jobs_sincronizacion",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="logdetallesincronizacion",
            name="resumen_externo",
            field=models.JSONField(
                default=dict,
                help_text="Campos no sensibles del payload externo para debug.",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="conectorinstancia",
            unique_together={("id_empresa", "nombre")},
        ),
        migrations.AlterUniqueTogether(
            name="entidadsincronizada",
            unique_together={("id_instancia", "tipo_entidad", "id_externo")},
        ),
    ]
