# Generated by Django 5.2.4 on 2026-06-02 05:26

import apps.core.fields
from django.db import migrations


def cifrar_existentes(apps, schema_editor):
    """
    H-SEC-4: cifra las configuraciones ya almacenadas en claro.

    Tras el AlterField, el campo es EncryptedJSONField: leer un valor legacy
    (dict plano) lo devuelve tal cual (fallback de from_db_value) y volver a
    guardarlo lo cifra. En BD fresca (CI) no hay filas y es un noop.
    NOTA OPERATIVA: tras desplegar, ROTAR las credenciales de los conectores.
    """
    Model = apps.get_model("integration_hub", "ConectorInstancia")
    for obj in Model.objects.all():
        obj.configuracion = obj.configuracion or {}
        obj.save(update_fields=["configuracion"])


def noop_reverse(apps, schema_editor):
    """Reverse noop: los datos quedan cifrados (revertir requiere descifrado manual)."""
    return


class Migration(migrations.Migration):

    dependencies = [
        (
            "integration_hub",
            "0002_remove_conectorinstancia_unique_instancia_por_empresa_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="conectorinstancia",
            name="configuracion",
            field=apps.core.fields.EncryptedJSONField(
                default=dict,
                help_text="Credenciales y configuración de conexión (cifradas en reposo, H-SEC-4).",
            ),
        ),
        migrations.RunPython(cifrar_existentes, noop_reverse),
    ]
