# Generated by Django 5.2.15 on 2026-06-22 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration_hub', '0005_seed_proveedores_conectores'),
    ]

    operations = [
        migrations.AddField(
            model_name='conectorproveedor',
            name='clase_conector',
            field=models.CharField(blank=True, default='', help_text="Ruta dotted a la clase BaseConnector que implementa este proveedor (p. ej. 'apps.integration_hub.connectors.odoo.connector.OdooConnector'). Si se define, el registry la carga dinámicamente sin re-desplegar (Fase 3); permite reutilizar un conector genérico para varios proveedores. Si está vacío, se usa el registro estático de apps.py.", max_length=255),
        ),
    ]
