# Generated by Django 5.2.4 on 2025-08-02 20:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('almacenes', '0002_initial'),
        ('compras', '0002_initial'),
        ('core', '0002_initial'),
        ('inventario', '0001_initial'),
        ('rrhh', '0001_initial'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Despacho',
            fields=[
                ('id_despacho', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_despacho', models.CharField(max_length=50, unique=True)),
                ('fecha_despacho', models.DateTimeField()),
                ('direccion_destino', models.TextField()),
                ('estado_despacho', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PREPARACION', 'En Preparación'), ('LISTO_ENVIO', 'Listo para Envío'), ('EN_TRANSITO', 'En Tránsito'), ('ENTREGADO', 'Entregado'), ('DEVUELTO', 'Devuelto'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20)),
                ('fecha_entrega_estimada', models.DateTimeField(blank=True, null=True)),
                ('fecha_entrega_real', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_almacen_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despachos_origen', to='almacenes.almacen')),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despachos', to='core.empresa')),
                ('id_orden_compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='despachos', to='compras.ordencompra')),
                ('id_pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='despachos', to='ventas.pedido')),
                ('id_transportista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='despachos_transportista', to='rrhh.empleado')),
            ],
            options={
                'verbose_name': 'Despacho',
                'verbose_name_plural': 'Despachos',
                'db_table': 'despacho_despacho',
            },
        ),
        migrations.CreateModel(
            name='DetalleDespacho',
            fields=[
                ('id_detalle_despacho', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cantidad_despachada', models.DecimalField(decimal_places=4, max_digits=18)),
                ('lote', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('id_despacho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='despacho.despacho')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_despacho', to='inventario.producto')),
                ('id_unidad_medida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_despacho', to='inventario.unidadmedida')),
            ],
            options={
                'verbose_name': 'Detalle de Despacho',
                'verbose_name_plural': 'Detalles de Despacho',
                'db_table': 'despacho_detalle_despacho',
            },
        ),
    ]
