# Generated by Django 5.2.4 on 2026-06-02 03:16

import apps.core.uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("despacho", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="despacho",
            name="id_despacho",
            field=models.UUIDField(
                default=apps.core.uuid.uuid7,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="detalledespacho",
            name="id_detalle_despacho",
            field=models.UUIDField(
                default=apps.core.uuid.uuid7,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
