# Generated by Django 5.2.15 on 2026-06-12 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("almacenes", "0004_alter_almacen_id_almacen_and_more"),
        ("core", "0022_claveidempotencia_usuario_ttl"),
        ("despacho", "0003_rls_lote3_despacho"),
        ("inventario", "0009_producto_punto_reorden"),
        ("rrhh", "0004_alter_beneficio_id_beneficio_and_more"),
        ("ventas", "0014_rls_piloto_ventas"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="despacho",
            options={
                "ordering": ["-fecha_despacho", "-fecha_creacion"],
                "verbose_name": "Despacho",
                "verbose_name_plural": "Despachos",
            },
        ),
        migrations.AlterUniqueTogether(
            name="despacho",
            unique_together={("id_empresa", "numero_despacho")},
        ),
        migrations.AddField(
            model_name="despacho",
            name="documento_json",
            field=models.JSONField(
                blank=True,
                help_text="Payload raw del documento externo (para auditoría/reprocesamiento).",
                null=True,
                verbose_name="Documento JSON",
            ),
        ),
        migrations.AddField(
            model_name="despacho",
            name="fecha_actualizacion",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Fecha y hora de la última modificación del registro.",
                verbose_name="Fecha de Actualización",
            ),
        ),
        migrations.AddField(
            model_name="despacho",
            name="fecha_cancelacion",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="despacho",
            name="fecha_devolucion",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="despacho",
            name="fecha_en_ruta",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="despacho",
            name="id_nota_venta",
            field=models.ForeignKey(
                blank=True,
                help_text="Nota de venta origen (ENTREGADA/FACTURADA). Nulo solo en despachos manuales.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="despachos",
                to="ventas.notaventa",
            ),
        ),
        migrations.AddField(
            model_name="despacho",
            name="referencia_externa",
            field=models.CharField(
                blank=True,
                help_text="Identificador del registro en el sistema externo de origen.",
                max_length=100,
                null=True,
                verbose_name="Referencia externa",
            ),
        ),
        migrations.AlterField(
            model_name="despacho",
            name="activo",
            field=models.BooleanField(
                default=True,
                help_text="Indica si el registro está activo (False = borrado lógico).",
                verbose_name="Activo",
            ),
        ),
        migrations.AlterField(
            model_name="despacho",
            name="direccion_destino",
            field=models.TextField(
                help_text="Dirección física donde se entrega la mercancía.",
                verbose_name="Dirección de entrega",
            ),
        ),
        migrations.AlterField(
            model_name="despacho",
            name="estado_despacho",
            field=models.CharField(
                choices=[
                    ("PENDIENTE", "Pendiente"),
                    ("EN_RUTA", "En ruta"),
                    ("ENTREGADO", "Entregado"),
                    ("DEVUELTO", "Devuelto"),
                    ("CANCELADO", "Cancelado"),
                ],
                default="PENDIENTE",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="despacho",
            name="fecha_creacion",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Fecha y hora de creación del registro.",
                verbose_name="Fecha de Creación",
            ),
        ),
        migrations.AlterField(
            model_name="despacho",
            name="fecha_despacho",
            field=models.DateTimeField(help_text="Fecha del documento de despacho."),
        ),
        migrations.AlterField(
            model_name="despacho",
            name="id_almacen_origen",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="despachos_origen",
                to="almacenes.almacen",
            ),
        ),
        migrations.AlterField(
            model_name="despacho",
            name="id_pedido",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="despachos",
                to="ventas.pedido",
            ),
        ),
        migrations.AlterField(
            model_name="despacho",
            name="numero_despacho",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="detalledespacho",
            name="id_producto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="detalles_despacho",
                to="inventario.producto",
            ),
        ),
        migrations.AlterField(
            model_name="detalledespacho",
            name="id_unidad_medida",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="detalles_despacho",
                to="inventario.unidadmedida",
            ),
        ),
        migrations.AddIndex(
            model_name="despacho",
            index=models.Index(
                fields=["id_empresa", "estado_despacho"],
                name="despacho_de_id_empr_dd95f8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="despacho",
            index=models.Index(
                fields=["fecha_despacho"], name="despacho_de_fecha_d_6871d8_idx"
            ),
        ),
        migrations.RemoveField(
            model_name="despacho",
            name="id_orden_compra",
        ),
    ]
