# Generated by Django 5.2.4 on 2025-08-02 20:41

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permisos',
            fields=[
                ('referencia_externa', models.CharField(blank=True, max_length=100, null=True)),
                ('documento_json', models.JSONField(blank=True, null=True)),
                ('id_permiso', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo_permiso', models.CharField(max_length=100, unique=True, verbose_name='Código de Permiso')),
                ('nombre_permiso', models.CharField(max_length=255, verbose_name='Nombre de Permiso')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('modulo', models.CharField(max_length=50, verbose_name='Módulo Asociado')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Permiso',
                'verbose_name_plural': 'Permisos',
                'db_table': 'permisos',
                'ordering': ['modulo', 'nombre_permiso'],
            },
        ),
        migrations.CreateModel(
            name='RegistroAuditoria',
            fields=[
                ('id_log_auditoria', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_evento', models.CharField(choices=[('LOGIN', 'Inicio de Sesión'), ('LOGOUT', 'Cierre de Sesión'), ('CREAR', 'Creación'), ('ACTUALIZAR', 'Actualización'), ('ELIMINAR', 'Eliminación'), ('ACCEDER', 'Acceso a Datos'), ('ERROR', 'Error del Sistema'), ('CAMBIO_ESTADO', 'Cambio de Estado'), ('APROBACION', 'Aprobación'), ('RECHAZO', 'Rechazo'), ('PAGO_CONFIRMADO', 'Pago Confirmado'), ('ENTREGA_REGISTRADA', 'Entrega Registrada'), ('INCIDENCIA_CREADA', 'Incidencia Creada')], max_length=50, verbose_name='Tipo de Evento')),
                ('modulo_afectado', models.CharField(max_length=50, verbose_name='Módulo Afectado')),
                ('nombre_modelo_afectado', models.CharField(blank=True, max_length=100, null=True, verbose_name='Modelo Afectado')),
                ('id_registro_afectado', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID Registro Afectado')),
                ('descripcion_accion', models.TextField(blank=True, null=True, verbose_name='Descripción de la Acción')),
                ('cambios_json', models.JSONField(blank=True, null=True, verbose_name='Cambios (JSON)')),
                ('fecha_hora_accion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de la Acción')),
                ('direccion_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('navegador_info', models.TextField(blank=True, null=True, verbose_name='Información del Navegador')),
                ('resultado_evento', models.CharField(choices=[('EXITO', 'Éxito'), ('FALLO', 'Fallo')], max_length=20, verbose_name='Resultado del Evento')),
                ('mensaje_error', models.TextField(blank=True, null=True, verbose_name='Mensaje de Error')),
            ],
            options={
                'verbose_name': 'Registro de Auditoría',
                'verbose_name_plural': 'Registros de Auditoría',
                'db_table': 'registro_auditoria',
                'ordering': ['-fecha_hora_accion'],
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('referencia_externa', models.CharField(blank=True, max_length=100, null=True)),
                ('documento_json', models.JSONField(blank=True, null=True)),
                ('id_rol', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(max_length=100, verbose_name='Nombre de Rol')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'db_table': 'roles',
                'ordering': ['nombre_rol'],
            },
        ),
        migrations.CreateModel(
            name='RolPermisos',
            fields=[
                ('id_rol_permiso', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Asignación')),
            ],
            options={
                'verbose_name': 'Permiso de Rol',
                'verbose_name_plural': 'Permisos de Roles',
                'db_table': 'rol_permisos',
                'ordering': ['id_rol__nombre_rol', 'id_permiso__nombre_permiso'],
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('referencia_externa', models.CharField(blank=True, max_length=100, null=True)),
                ('documento_json', models.JSONField(blank=True, null=True)),
                ('id_sucursal', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de Sucursal')),
                ('codigo_sucursal', models.CharField(max_length=10, unique=True, verbose_name='Código de Sucursal')),
                ('direccion', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('email_contacto', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email de Contacto')),
                ('ubicacion_gps_json', models.JSONField(blank=True, null=True, verbose_name='Ubicación GPS')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'Sucursal',
                'verbose_name_plural': 'Sucursales',
                'db_table': 'sucursales',
                'ordering': ['id_empresa', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='UsuarioRoles',
            fields=[
                ('id_usuario_rol', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Asignación')),
            ],
            options={
                'verbose_name': 'Rol de Usuario',
                'verbose_name_plural': 'Roles de Usuarios',
                'db_table': 'usuario_roles',
                'ordering': ['id_usuario__username', 'id_rol__nombre_rol'],
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('referencia_externa', models.CharField(blank=True, max_length=100, null=True)),
                ('documento_json', models.JSONField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('es_superusuario_innova', models.BooleanField(default=False, verbose_name='Es Superusuario InnovaERP')),
                ('fecha_ultimo_login', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Último Login')),
                ('token_sesion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Token de Sesión')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuarios',
                'ordering': ['username'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('referencia_externa', models.CharField(blank=True, max_length=100, null=True)),
                ('documento_json', models.JSONField(blank=True, null=True)),
                ('id_departamento', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_departamento', models.CharField(max_length=100, verbose_name='Nombre de Departamento')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('departamento_general', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subdepartamentos', to='core.departamento', verbose_name='Dirección General')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'db_table': 'departamentos',
                'ordering': ['id_empresa', 'nombre_departamento'],
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id_empresa', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_legal', models.CharField(max_length=255, verbose_name='Nombre Legal')),
                ('nombre_comercial', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre Comercial')),
                ('identificador_fiscal', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion_fiscal', models.TextField(blank=True, null=True, verbose_name='Dirección Fiscal')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('email_contacto', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email de Contacto')),
                ('web_url', models.URLField(blank=True, null=True, verbose_name='URL Web')),
                ('logo_url', models.URLField(blank=True, null=True, verbose_name='URL del Logo')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('referencia_externa', models.CharField(blank=True, max_length=100, null=True)),
                ('documento_json', models.JSONField(blank=True, null=True)),
                ('tipo_operacion', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_cierre_estimada', models.DateField(blank=True, null=True)),
                ('empresa_matriz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subsidiarias', to='core.empresa', verbose_name='Empresa Matriz')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'db_table': 'empresas',
                'ordering': ['nombre_legal'],
            },
        ),
    ]
