# Generated by Django 5.2.4 on 2025-08-02 20:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('finanzas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='id_moneda_base',
            field=models.ForeignKey(blank=True, db_column='id_moneda_base', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empresas_base', to='finanzas.moneda', verbose_name='Moneda Base'),
        ),
        migrations.AddField(
            model_name='departamento',
            name='id_empresa',
            field=models.ForeignKey(db_column='id_empresa', on_delete=django.db.models.deletion.CASCADE, related_name='departamentos', to='core.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='empresas',
            field=models.ManyToManyField(related_name='usuarios', to='core.empresa'),
        ),
        migrations.AddField(
            model_name='registroauditoria',
            name='id_empresa',
            field=models.ForeignKey(db_column='id_empresa', on_delete=django.db.models.deletion.CASCADE, related_name='registros_auditoria_empresa', to='core.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='registroauditoria',
            name='id_usuario',
            field=models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_auditoria_usuario', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='roles',
            name='id_empresa',
            field=models.ForeignKey(blank=True, db_column='id_empresa', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles_empresa', to='core.empresa', verbose_name='Empresa (Opcional)'),
        ),
        migrations.AddField(
            model_name='rolpermisos',
            name='id_permiso',
            field=models.ForeignKey(db_column='id_permiso', on_delete=django.db.models.deletion.CASCADE, related_name='roles_asignados', to='core.permisos', verbose_name='Permiso'),
        ),
        migrations.AddField(
            model_name='rolpermisos',
            name='id_rol',
            field=models.ForeignKey(db_column='id_rol', on_delete=django.db.models.deletion.CASCADE, related_name='permisos_asignados', to='core.roles', verbose_name='Rol'),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='id_empresa',
            field=models.ForeignKey(db_column='id_empresa', on_delete=django.db.models.deletion.CASCADE, related_name='sucursales', to='core.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='sucursal_matriz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subsucursales', to='core.sucursal', verbose_name='Sucursal Matriz'),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='id_sucursal_predeterminada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_predeterminados', to='core.sucursal', verbose_name='Sucursal predeterminada'),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='sucursales',
            field=models.ManyToManyField(related_name='usuarios', to='core.sucursal'),
        ),
        migrations.AddField(
            model_name='usuarioroles',
            name='id_rol',
            field=models.ForeignKey(db_column='id_rol', on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_asignados', to='core.roles', verbose_name='Rol'),
        ),
        migrations.AddField(
            model_name='usuarioroles',
            name='id_usuario',
            field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='roles_asignados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterUniqueTogether(
            name='departamento',
            unique_together={('id_empresa', 'nombre_departamento')},
        ),
        migrations.AlterUniqueTogether(
            name='roles',
            unique_together={('id_empresa', 'nombre_rol')},
        ),
        migrations.AlterUniqueTogether(
            name='rolpermisos',
            unique_together={('id_rol', 'id_permiso')},
        ),
        migrations.AlterUniqueTogether(
            name='sucursal',
            unique_together={('id_empresa', 'codigo_sucursal')},
        ),
        migrations.AlterUniqueTogether(
            name='usuarioroles',
            unique_together={('id_usuario', 'id_rol')},
        ),
    ]
