# Generated by Django 5.2.4 on 2025-08-04 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
        ('finanzas', '0003_alter_transaccionfinanciera_id_moneda_base_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='id_moneda_pais',
            field=models.ForeignKey(blank=True, db_column='id_moneda_pais', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empresas_moneda_pais', to='finanzas.moneda', verbose_name='Moneda del País'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='pais_codigo_iso',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Código ISO del País'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='pais_nombre',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre del País'),
        ),
    ]
