# Generated by Django 5.2.4 on 2025-11-10 01:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_empresa_id_moneda_pais_empresa_pais_codigo_iso_and_more'),
        ('finanzas', '0031_add_permisos_caja_fisica_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id_dispositivo', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fingerprint', models.CharField(help_text='Hash único generado por el frontend (FingerprintJS)', max_length=255, unique=True)),
                ('user_agent', models.TextField(help_text='User agent del navegador/dispositivo')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Dirección IP del dispositivo', null=True)),
                ('nombre_dispositivo', models.CharField(help_text='Nombre descriptivo del dispositivo (generado automáticamente)', max_length=100)),
                ('preguntar_crear_caja', models.BooleanField(default=True, help_text='Si True, preguntar al usuario si quiere crear caja física en próximos logins')),
                ('ultima_pregunta_caja', models.DateTimeField(blank=True, help_text='Última vez que se preguntó sobre crear caja física', null=True)),
                ('activo', models.BooleanField(default=True, help_text='Si el dispositivo está activo')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, help_text='Fecha de registro del dispositivo')),
                ('ultimo_login', models.DateTimeField(auto_now=True, help_text='Último login desde este dispositivo')),
                ('caja_fisica', models.OneToOneField(blank=True, help_text='Caja física asociada a este dispositivo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispositivo', to='finanzas.cajafisica')),
                ('creado_por', models.ForeignKey(help_text='Usuario que registró este dispositivo', on_delete=django.db.models.deletion.CASCADE, related_name='dispositivos_creados', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(help_text='Empresa a la que pertenece el dispositivo', on_delete=django.db.models.deletion.CASCADE, related_name='dispositivos', to='core.empresa')),
                ('sucursal', models.ForeignKey(help_text='Sucursal a la que pertenece el dispositivo', on_delete=django.db.models.deletion.CASCADE, related_name='dispositivos', to='core.sucursal')),
            ],
            options={
                'verbose_name': 'Dispositivo',
                'verbose_name_plural': 'Dispositivos',
                'db_table': 'core_dispositivo',
                'ordering': ['-ultimo_login'],
                'unique_together': {('fingerprint', 'empresa')},
            },
        ),
    ]
