# Generated by Django 5.2.4 on 2026-04-30 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_dispositivo_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='token_sesion',
        ),
        migrations.AlterField(
            model_name='empresa',
            name='activo',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Activo'),
        ),
    ]
