# Generated by Django 5.2.4 on 2026-05-11 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_es_superusuario_innova_to_omni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='es_superusuario_omni',
            field=models.BooleanField(default=False, verbose_name='Es Superusuario Omni ERP'),
        ),
    ]
