# Generated by Django 5.2.4 on 2026-05-12 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_usuarios_es_superusuario_omni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permisos',
            name='activo',
            field=models.BooleanField(default=True, help_text='Indica si el registro está activo (False = borrado lógico).', verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='permisos',
            name='documento_json',
            field=models.JSONField(blank=True, help_text='Payload raw del documento externo (para auditoría/reprocesamiento).', null=True, verbose_name='Documento JSON'),
        ),
        migrations.AlterField(
            model_name='permisos',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última modificación del registro.', verbose_name='Fecha de Actualización'),
        ),
        migrations.AlterField(
            model_name='permisos',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro.', verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='permisos',
            name='referencia_externa',
            field=models.CharField(blank=True, help_text='Identificador del registro en el sistema externo de origen.', max_length=100, null=True, verbose_name='Referencia externa'),
        ),
        migrations.AlterField(
            model_name='roles',
            name='activo',
            field=models.BooleanField(default=True, help_text='Indica si el registro está activo (False = borrado lógico).', verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='roles',
            name='documento_json',
            field=models.JSONField(blank=True, help_text='Payload raw del documento externo (para auditoría/reprocesamiento).', null=True, verbose_name='Documento JSON'),
        ),
        migrations.AlterField(
            model_name='roles',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última modificación del registro.', verbose_name='Fecha de Actualización'),
        ),
        migrations.AlterField(
            model_name='roles',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro.', verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='roles',
            name='referencia_externa',
            field=models.CharField(blank=True, help_text='Identificador del registro en el sistema externo de origen.', max_length=100, null=True, verbose_name='Referencia externa'),
        ),
    ]
