# Generated by Django 5.2.4 on 2026-05-15 01:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_use_base_models_for_roles_permisos'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapabilityToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro.', verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última modificación del registro.', verbose_name='Fecha de Actualización')),
                ('activo', models.BooleanField(default=True, help_text='Indica si el registro está activo (False = borrado lógico).', verbose_name='Activo')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID generado automáticamente. Se usa como API key.', unique=True, verbose_name='Token')),
                ('nombre', models.CharField(help_text='Descripción del agente o sistema que usa este token.', max_length=255, verbose_name='Nombre del token')),
                ('scopes', models.JSONField(default=list, help_text="Lista de scopes habilitados. Ejemplo: ['crm:read', 'ventas:read']", verbose_name='Scopes')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Fecha de expiración. None = no expira (solo para tokens internos).', null=True, verbose_name='Expira en')),
                ('ultimo_uso', models.DateTimeField(blank=True, null=True, verbose_name='Último uso')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tokens_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capability_tokens', to='core.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Capability Token',
                'verbose_name_plural': 'Capability Tokens',
                'db_table': 'core_capability_token',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
