# Generated by Django 5.2.4 on 2026-05-19 01:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_notificacion'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='contacto',
            new_name='core_contac_id_empr_eecd08_idx',
            old_name='core_contacto_empresa_cliente_idx',
        ),
        migrations.RenameIndex(
            model_name='contacto',
            new_name='core_contac_id_empr_66690f_idx',
            old_name='core_contacto_empresa_proveedor_idx',
        ),
        migrations.RenameIndex(
            model_name='contacto',
            new_name='core_contac_rif_b1226a_idx',
            old_name='core_contacto_rif_idx',
        ),
        migrations.RenameIndex(
            model_name='notificacion',
            new_name='core_notifi_id_empr_0261b0_idx',
            old_name='core_notif_empresa_usuario_leida_idx',
        ),
        migrations.RenameIndex(
            model_name='notificacion',
            new_name='core_notifi_id_empr_e9155a_idx',
            old_name='core_notif_empresa_tipo_fecha_idx',
        ),
        migrations.AlterField(
            model_name='configuracionflujodocumentos',
            name='activo',
            field=models.BooleanField(default=True, help_text='Indica si el registro está activo (False = borrado lógico).', verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='configuracionflujodocumentos',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última modificación del registro.', verbose_name='Fecha de Actualización'),
        ),
        migrations.AlterField(
            model_name='configuracionflujodocumentos',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro.', verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='configuracionflujodocumentos',
            name='obligatorio',
            field=models.BooleanField(default=True, help_text='Si es False, este paso puede omitirse en el flujo.'),
        ),
        migrations.AlterField(
            model_name='configuracionflujodocumentos',
            name='orden',
            field=models.PositiveSmallIntegerField(default=1, help_text='Orden relativo de ejecución dentro del tipo de documento.'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='activo',
            field=models.BooleanField(default=True, help_text='Indica si el registro está activo (False = borrado lógico).', verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última modificación del registro.', verbose_name='Fecha de Actualización'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro.', verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='nombre',
            field=models.CharField(help_text='Nombre o Razón Social', max_length=255),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='fecha_expiracion',
            field=models.DateTimeField(blank=True, help_text='Si se establece, la notificación se oculta después de esta fecha.', null=True),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='id_usuario',
            field=models.ForeignKey(blank=True, help_text='Si None, la notificación es para todos los usuarios de la empresa.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Datos adicionales para el frontend (ids de referencia, etc.).'),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='url_accion',
            field=models.CharField(blank=True, default='', help_text='URL relativa de la acción vinculada (ej. /compras/ordenes/123/).', max_length=500),
        ),
    ]
