# Generated by Django 5.2.4 on 2026-05-24 18:44

import apps.core.uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_fix_unique_numeros_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capabilitytoken',
            name='token',
            field=models.UUIDField(default=apps.core.uuid.uuid7, editable=False, help_text='UUID generado automáticamente. Se usa como API key.', unique=True, verbose_name='Token'),
        ),
        migrations.AlterField(
            model_name='configuracionflujodocumentos',
            name='id_configuracion',
            field=models.UUIDField(default=apps.core.uuid.uuid7, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='id_contacto',
            field=models.UUIDField(default=apps.core.uuid.uuid7, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='id_departamento',
            field=models.UUIDField(default=apps.core.uuid.uuid7, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='id_dispositivo',
            field=models.UUIDField(default=apps.core.uuid.uuid7, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='id_empresa',
            field=models.UUIDField(default=apps.core.uuid.uuid7, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='id_notificacion',
            field=models.UUIDField(default=apps.core.uuid.uuid7, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='permisos',
            name='id_permiso',
            field=models.UUIDField(default=apps.core.uuid.uuid7, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='registroauditoria',
            name='id_log_auditoria',
            field=models.UUIDField(default=apps.core.uuid.uuid7, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='roles',
            name='id_rol',
            field=models.UUIDField(default=apps.core.uuid.uuid7, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rolpermisos',
            name='id_rol_permiso',
            field=models.UUIDField(default=apps.core.uuid.uuid7, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='id_sucursal',
            field=models.UUIDField(default=apps.core.uuid.uuid7, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usuarioroles',
            name='id_usuario_rol',
            field=models.UUIDField(default=apps.core.uuid.uuid7, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='id',
            field=models.UUIDField(default=apps.core.uuid.uuid7, editable=False, primary_key=True, serialize=False),
        ),
    ]
