# Generated by Django 5.2.4 on 2026-06-02 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_alter_capabilitytoken_token_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="empresa",
            name="contabilidad_activa",
            field=models.BooleanField(
                default=False,
                help_text="Si True, la empresa exige contabilidad: una operación sin Mapeo Contable configurado FALLA en vez de continuar sin asiento (H-BUG-1 / R-CODE-11). Si False (bodega informal, R-PROD-3), la operación procede sin asiento. Default False para no romper empresas existentes.",
            ),
        ),
    ]
