# Generated by Django 5.2.4 on 2026-06-02 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_empresa_contabilidad_activa"),
    ]

    operations = [
        migrations.AddField(
            model_name="empresa",
            name="localizacion_legal_activa",
            field=models.BooleanField(
                default=True,
                help_text="Capa legal (impuestos/documentos/libros del país). Si False, no aplica IVA/IGTF/etc.",
            ),
        ),
        migrations.AddField(
            model_name="empresa",
            name="localizacion_mercado_activa",
            field=models.BooleanField(
                default=True,
                help_text="Capa de mercado (tasas, métodos de pago locales). Activable independientemente.",
            ),
        ),
    ]
