# Generated by Django 5.2.15 on 2026-06-09 02:56

import apps.core.uuid
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_rls_piloto_sucursales'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaveIdempotencia',
            fields=[
                ('id_clave_idempotencia', models.UUIDField(default=apps.core.uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('scope', models.CharField(help_text="Identificador del endpoint protegido. Ej: 'cxc:abonar'.", max_length=100, verbose_name='Scope / endpoint')),
                ('clave', models.CharField(help_text='Valor de la cabecera Idempotency-Key enviada por el cliente.', max_length=255, verbose_name='Idempotency-Key')),
                ('payload_hash', models.CharField(help_text='SHA-256 hex del cuerpo de la petición; detecta reuso de clave con datos distintos.', max_length=64, verbose_name='Hash del payload')),
                ('status_respuesta', models.PositiveSmallIntegerField(help_text='Código HTTP de la respuesta original que se reproduce en reintentos.', verbose_name='Status HTTP guardado')),
                ('cuerpo_respuesta', models.JSONField(blank=True, help_text='Snapshot JSON del body devuelto en la primera ejecución.', null=True, verbose_name='Cuerpo de la respuesta')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('empresa', models.ForeignKey(help_text='Tenant dueño de la clave (R-CODE-1).', on_delete=django.db.models.deletion.CASCADE, related_name='claves_idempotencia', to='core.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Clave de idempotencia',
                'verbose_name_plural': 'Claves de idempotencia',
                'db_table': 'core_clave_idempotencia',
                'ordering': ['-fecha_creacion'],
                'constraints': [models.UniqueConstraint(fields=('empresa', 'scope', 'clave'), name='uniq_idempotencia_empresa_scope_clave')],
            },
        ),
    ]
