# Generated by Django 5.2.15 on 2026-06-12 00:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_claveidempotencia"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="claveidempotencia",
            name="uniq_idempotencia_empresa_scope_clave",
        ),
        migrations.AddField(
            model_name="claveidempotencia",
            name="expira_en",
            field=models.DateTimeField(
                db_index=True,
                default=django.utils.timezone.now,
                help_text="Pasada esta fecha la clave deja de ser válida y puede purgarse (TTL ~24h).",
                verbose_name="Expira en",
            ),
        ),
        migrations.AddField(
            model_name="claveidempotencia",
            name="usuario",
            field=models.ForeignKey(
                blank=True,
                help_text="Usuario que consumió la clave; forma parte de la unicidad.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="claves_idempotencia",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuario",
            ),
        ),
        migrations.AlterField(
            model_name="claveidempotencia",
            name="status_respuesta",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Código HTTP de la respuesta original que se reproduce en reintentos. NULL mientras la operación original está 'en vuelo' (sin commitear).",
                null=True,
                verbose_name="Status HTTP guardado",
            ),
        ),
        migrations.AddConstraint(
            model_name="claveidempotencia",
            constraint=models.UniqueConstraint(
                fields=("empresa", "usuario", "scope", "clave"),
                name="uniq_idempotencia_emp_usr_scope_clave",
            ),
        ),
    ]
