# Generated by Django 5.2.4 on 2026-05-15 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_base_model_empresa_sucursal_departamento'),
        ('proveedores', '0002_base_model_rif_per_empresa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactoproveedor',
            options={'verbose_name': 'Contacto de Proveedor', 'verbose_name_plural': 'Contactos de Proveedor'},
        ),
        migrations.AlterModelOptions(
            name='proveedor',
            options={'ordering': ['razon_social']},
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='documento_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='id_empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proveedores', to='core.empresa'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='referencia_externa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
