# Generated by Django 5.2.4 on 2025-08-02 20:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carpeta',
            fields=[
                ('id_carpeta', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_carpeta', models.CharField(max_length=255)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('es_publica', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('id_carpeta_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_documental.carpeta')),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
                ('id_usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id_documento', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('tipo_contenido', models.CharField(max_length=100)),
                ('tamano_bytes', models.BigIntegerField()),
                ('ruta_almacenamiento', models.CharField(max_length=500)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('version', models.IntegerField(default=1)),
                ('id_carpeta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_documental.carpeta')),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
                ('id_usuario_subida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PermisoDocumento',
            fields=[
                ('id_permiso_documento', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('puede_ver', models.BooleanField(default=True)),
                ('puede_editar', models.BooleanField(default=False)),
                ('puede_eliminar', models.BooleanField(default=False)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('id_documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_documental.documento')),
                ('id_rol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.roles')),
                ('id_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VinculoDocumento',
            fields=[
                ('id_vinculo', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('id_entidad_origen', models.UUIDField()),
                ('nombre_modelo_origen', models.CharField(max_length=100)),
                ('tipo_vinculo', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_vinculo', models.DateTimeField(auto_now_add=True)),
                ('id_documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_documental.documento')),
            ],
        ),
    ]
