# Generated by Django 5.2.4 on 2025-08-02 20:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionHorario',
            fields=[
                ('id_asignacion_horario', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('id_empleado_temp', models.UUIDField(blank=True, null=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='HorarioTrabajo',
            fields=[
                ('id_horario', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('nombre_horario', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('dias_semana_json', models.JSONField(blank=True, null=True)),
                ('total_horas_semanales', models.DecimalField(decimal_places=2, max_digits=5)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroAsistencia',
            fields=[
                ('id_registro_asistencia', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('id_empleado_temp', models.UUIDField(blank=True, null=True)),
                ('fecha_hora_marcado', models.DateTimeField()),
                ('tipo_marcado', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida'), ('INICIO_DESCANSO', 'Inicio Descanso'), ('FIN_DESCANSO', 'Fin Descanso')], max_length=20)),
                ('metodo_marcado', models.CharField(choices=[('BIOMETRICO', 'Biométrico'), ('MANUAL', 'Manual'), ('WEB', 'Web'), ('MOVIL', 'Móvil'), ('GPS', 'GPS')], max_length=50)),
                ('ubicacion_gps_json', models.JSONField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResumenAsistenciaDiario',
            fields=[
                ('id_resumen_diario', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('id_empleado_temp', models.UUIDField(blank=True, null=True)),
                ('fecha', models.DateField()),
                ('hora_entrada_real', models.TimeField(blank=True, null=True)),
                ('hora_salida_real', models.TimeField(blank=True, null=True)),
                ('horas_trabajadas_netas', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('horas_extras_normal', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('horas_extras_feriado', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('minutos_tardanza', models.IntegerField(default=0)),
                ('es_ausencia', models.BooleanField(default=False)),
                ('id_licencia_asociada_temp', models.UUIDField(blank=True, null=True)),
                ('estado_revision', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('REVISADO', 'Revisado'), ('APROBADO', 'Aprobado')], max_length=20)),
                ('observaciones_supervisor', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
