# Generated by Django 5.2.4 on 2025-08-02 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('control_asistencia', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='horariotrabajo',
            name='id_empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa'),
        ),
        migrations.AddField(
            model_name='asignacionhorario',
            name='id_horario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control_asistencia.horariotrabajo'),
        ),
        migrations.AlterUniqueTogether(
            name='resumenasistenciadiario',
            unique_together={('id_empleado_temp', 'fecha')},
        ),
    ]
