# Generated by Django 5.2.4 on 2026-06-02 03:16

import apps.core.uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("control_asistencia", "0003_restore_empleado_fk"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asignacionhorario",
            name="id_asignacion_horario",
            field=models.UUIDField(
                default=apps.core.uuid.uuid7, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="horariotrabajo",
            name="id_horario",
            field=models.UUIDField(
                default=apps.core.uuid.uuid7, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="registroasistencia",
            name="id_registro_asistencia",
            field=models.UUIDField(
                default=apps.core.uuid.uuid7, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="resumenasistenciadiario",
            name="id_resumen_diario",
            field=models.UUIDField(
                default=apps.core.uuid.uuid7, primary_key=True, serialize=False
            ),
        ),
    ]
