# Generated by Django 5.2.15 on 2026-06-28 02:04

import apps.core.uuid
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0023_rls_lote3_core'),
    ]

    operations = [
        migrations.CreateModel(
            name='DescuentoBCVCompleto',
            fields=[
                ('id', models.UUIDField(default=apps.core.uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('porcentaje', models.DecimalField(decimal_places=6, max_digits=9)),
                ('vigencia_desde', models.DateField()),
                ('vigencia_hasta', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Descuento BCV completo',
                'verbose_name_plural': 'Descuentos BCV completo',
                'ordering': ['-vigencia_desde'],
            },
        ),
        migrations.CreateModel(
            name='DescuentoMarcaCategoria',
            fields=[
                ('id', models.UUIDField(default=apps.core.uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('marca', models.CharField(default='*', max_length=100)),
                ('categoria', models.CharField(default='*', max_length=100)),
                ('tipo_descuento', models.CharField(choices=[('contado', 'Contado')], default='contado', max_length=20)),
                ('porcentaje', models.DecimalField(decimal_places=6, max_digits=9)),
                ('vigencia_desde', models.DateField()),
                ('vigencia_hasta', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Descuento por marca/categoría',
                'verbose_name_plural': 'Descuentos por marca/categoría',
                'ordering': ['-vigencia_desde'],
            },
        ),
        migrations.CreateModel(
            name='PromocionPrimeraCompra',
            fields=[
                ('id', models.UUIDField(default=apps.core.uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('producto', models.CharField(max_length=200)),
                ('vigencia_desde', models.DateField()),
                ('vigencia_hasta', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Promoción de primera compra',
                'verbose_name_plural': 'Promociones de primera compra',
                'ordering': ['-vigencia_desde'],
            },
        ),
        migrations.CreateModel(
            name='ReglaRecurrencia',
            fields=[
                ('id', models.UUIDField(default=apps.core.uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('condicion', models.CharField(choices=[('primera_compra', 'Primera compra'), ('recompra', 'Recompra')], max_length=20)),
                ('tipo_beneficio', models.CharField(choices=[('nota_credito', 'Nota de crédito'), ('porcentaje', 'Porcentaje')], max_length=20)),
                ('valor', models.DecimalField(decimal_places=6, max_digits=18)),
                ('vigencia_desde', models.DateField()),
                ('vigencia_hasta', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Regla de recurrencia',
                'verbose_name_plural': 'Reglas de recurrencia',
                'ordering': ['-vigencia_desde'],
            },
        ),
        migrations.CreateModel(
            name='Feriado',
            fields=[
                ('id', models.UUIDField(default=apps.core.uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('nacional', 'Nacional'), ('regional', 'Regional'), ('bancario', 'Bancario')], default='nacional', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Feriado',
                'verbose_name_plural': 'Feriados',
                'ordering': ['fecha'],
                'unique_together': {('empresa', 'fecha')},
            },
        ),
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.UUIDField(default=apps.core.uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('codigo', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=120)),
                ('moneda', models.CharField(choices=[('USD', 'USD'), ('VES', 'VES')], max_length=3)),
                ('tipo_tasa', models.CharField(choices=[('BCV', 'BCV'), ('Binance', 'Binance'), ('N_A', 'N/A')], max_length=10)),
                ('es_contado', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Método de pago',
                'verbose_name_plural': 'Métodos de pago',
                'ordering': ['nombre'],
                'unique_together': {('empresa', 'codigo')},
            },
        ),
    ]
