# Generated by Django 5.2.15 on 2026-06-28 04:08

import apps.core.uuid
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_rls_lote3_core'),
        ('cxc_lubrikca', '0002_pagolubrikca_pedidolubrikca_lineapedidolubrikca_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidolubrikca',
            name='ncs_facturadas',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18),
        ),
        migrations.CreateModel(
            name='ConciliacionLubrikca',
            fields=[
                ('id', models.UUIDField(default=apps.core.uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('total_motor', models.DecimalField(decimal_places=2, max_digits=18)),
                ('monto_facturado', models.DecimalField(decimal_places=2, max_digits=18)),
                ('ncs', models.DecimalField(decimal_places=2, max_digits=18)),
                ('diferencia', models.DecimalField(decimal_places=2, max_digits=18)),
                ('resultado', models.CharField(choices=[('verde', 'Verde (cuadra)'), ('amarillo', 'Amarillo (revisar)'), ('rojo', 'Rojo (se facturó distinto)')], max_length=10)),
                ('conciliado_en', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.empresa', verbose_name='Empresa')),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conciliacion', to='cxc_lubrikca.pedidolubrikca')),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conciliación',
                'verbose_name_plural': 'Conciliaciones',
                'ordering': ['-conciliado_en'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionConciliacion',
            fields=[
                ('id', models.UUIDField(default=apps.core.uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('tolerance_rounding', models.DecimalField(decimal_places=2, default=Decimal('0.01'), max_digits=18)),
                ('tolerance_red', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=18)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Configuración de conciliación',
                'verbose_name_plural': 'Configuraciones de conciliación',
                'ordering': ['-created_at'],
            },
        ),
    ]
