# Generated by Django 5.2.4 on 2025-08-02 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaBancariaEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia_externa', models.CharField(blank=True, max_length=100, null=True)),
                ('documento_json', models.JSONField(blank=True, null=True)),
                ('banco', models.CharField(max_length=100)),
                ('numero_cuenta', models.CharField(max_length=50, unique=True)),
                ('tipo_cuenta', models.CharField(choices=[('corriente', 'Corriente'), ('ahorro', 'Ahorro')], max_length=30)),
                ('saldo_actual', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('activa', models.BooleanField(default=True)),
            ],
        ),
    ]
