# Generated by Django 5.2.4 on 2025-08-02 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContribucionParafiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('tipo', models.CharField(choices=[('IVSS', 'Seguro Social'), ('FAOV', 'Fondo de Vivienda'), ('INCES', 'INCES'), ('OTRO', 'Otro')], max_length=30)),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=5)),
                ('base_calculo', models.CharField(choices=[('SALARIO', 'Salario'), ('NOMINA', 'Nómina'), ('UTILIDAD', 'Utilidad'), ('BONIFICACION', 'Bonificación'), ('OTRO', 'Otro')], max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('es_generico', models.BooleanField(default=False, help_text='Si es True, es una contribución global del sistema, no editable por usuarios normales.')),
                ('es_publico', models.BooleanField(default=False, help_text='Si es True, la contribución es visible para todas las empresas.')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(blank=True, help_text='Empresa propietaria de la contribución. Null si es genérica.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contribuciones_empresa', to='core.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='EmpresaContribucionParafiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje_personalizado', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('contribucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fiscal.contribucionparafiscal')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Impuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('tipo', models.CharField(choices=[('IVA', 'IVA'), ('ISLR', 'ISLR'), ('IGTF', 'IGTF'), ('OTRO', 'Otro')], max_length=30)),
                ('alicuota', models.DecimalField(decimal_places=2, max_digits=5)),
                ('base_legal', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('es_generico', models.BooleanField(default=False, help_text='Si es True, es un impuesto global del sistema, no editable por usuarios normales.')),
                ('es_publico', models.BooleanField(default=False, help_text='Si es True, el impuesto es visible para todas las empresas.')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(blank=True, help_text='Empresa propietaria del impuesto. Null si es genérico.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='impuestos_empresa', to='core.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='ConfiguracionRetencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aplica_en_venta', models.BooleanField(default=True)),
                ('aplica_en_compra', models.BooleanField(default=False)),
                ('aplica_si_moneda_distinta_bolivar', models.BooleanField(default=False)),
                ('aplica_si_monto_mayor', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('aplica_si_tipo_cliente', models.CharField(blank=True, max_length=30, null=True)),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=5)),
                ('vigente_desde', models.DateField()),
                ('vigente_hasta', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('empresa', models.ForeignKey(help_text='Agente de retención', on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
                ('impuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fiscal.impuesto')),
            ],
        ),
        migrations.CreateModel(
            name='ConfiguracionImpuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aplica_en_venta', models.BooleanField(default=True)),
                ('aplica_en_compra', models.BooleanField(default=False)),
                ('aplica_si_moneda_distinta_bolivar', models.BooleanField(default=False)),
                ('requiere_agente_retencion_iva', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
                ('impuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fiscal.impuesto')),
            ],
        ),
        migrations.CreateModel(
            name='PagoContribucionParafiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(max_length=20)),
                ('monto_calculado', models.DecimalField(decimal_places=2, max_digits=18)),
                ('monto_pagado', models.DecimalField(decimal_places=2, max_digits=18)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('referencia_pago', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('contribucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fiscal.contribucionparafiscal')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Retencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('alicuota', models.DecimalField(decimal_places=2, max_digits=5)),
                ('es_generico', models.BooleanField(default=False, help_text='Si es True, es una retención global del sistema, no editable por usuarios normales.')),
                ('es_publico', models.BooleanField(default=False, help_text='Si es True, la retención es visible para todas las empresas.')),
                ('fecha', models.DateField()),
                ('monto_base', models.DecimalField(decimal_places=2, max_digits=18)),
                ('monto_retenido', models.DecimalField(decimal_places=2, max_digits=18)),
                ('numero_comprobante', models.CharField(max_length=100, unique=True)),
                ('referencia_documento', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('agente_retencion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retenciones_realizadas', to='core.empresa')),
                ('empresa', models.ForeignKey(blank=True, help_text='Empresa propietaria de la retención. Null si es genérica.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='retenciones_empresa', to='core.empresa')),
                ('impuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retenciones', to='fiscal.impuesto')),
                ('sujeto_retenido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retenciones_recibidas', to='core.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='ContribucionEmpresaActiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activa', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contribuciones_activas', to='core.empresa')),
                ('contribucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresas_activas', to='fiscal.contribucionparafiscal')),
            ],
            options={
                'verbose_name': 'Contribución activa por empresa',
                'verbose_name_plural': 'Contribuciones activas por empresa',
                'unique_together': {('empresa', 'contribucion')},
            },
        ),
        migrations.CreateModel(
            name='ImpuestoEmpresaActiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activa', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impuestos_activos', to='core.empresa')),
                ('impuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresas_activas', to='fiscal.impuesto')),
            ],
            options={
                'verbose_name': 'Impuesto activo por empresa',
                'verbose_name_plural': 'Impuestos activos por empresa',
                'unique_together': {('empresa', 'impuesto')},
            },
        ),
        migrations.CreateModel(
            name='RetencionEmpresaActiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activa', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retenciones_activas', to='core.empresa')),
                ('retencion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresas_activas', to='fiscal.retencion')),
            ],
            options={
                'verbose_name': 'Retención activa por empresa',
                'verbose_name_plural': 'Retenciones activas por empresa',
                'unique_together': {('empresa', 'retencion')},
            },
        ),
    ]
