# Generated by Django 5.2.15 on 2026-06-12 13:46

import apps.core.uuid
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_claveidempotencia_usuario_ttl"),
        ("finanzas", "0040_pagotercero"),
        ("fiscal", "0006_alter_configuracionfiscalempresa_id_and_more"),
        ("nomina", "0003_alter_conceptonomina_id_concepto_nomina_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PagoContribucionParafiscal",
            fields=[
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Fecha y hora de creación del registro.",
                        verbose_name="Fecha de Creación",
                    ),
                ),
                (
                    "fecha_actualizacion",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Fecha y hora de la última modificación del registro.",
                        verbose_name="Fecha de Actualización",
                    ),
                ),
                (
                    "activo",
                    models.BooleanField(
                        default=True,
                        help_text="Indica si el registro está activo (False = borrado lógico).",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "referencia_externa",
                    models.CharField(
                        blank=True,
                        help_text="Identificador del registro en el sistema externo de origen.",
                        max_length=100,
                        null=True,
                        verbose_name="Referencia externa",
                    ),
                ),
                (
                    "documento_json",
                    models.JSONField(
                        blank=True,
                        help_text="Payload raw del documento externo (para auditoría/reprocesamiento).",
                        null=True,
                        verbose_name="Documento JSON",
                    ),
                ),
                (
                    "id_pago_parafiscal",
                    models.UUIDField(
                        default=apps.core.uuid.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "periodo_año",
                    models.PositiveSmallIntegerField(
                        help_text="Año del período declarado (ej. 2026)."
                    ),
                ),
                (
                    "periodo_mes",
                    models.PositiveSmallIntegerField(
                        help_text="Mes del período declarado (1–12)."
                    ),
                ),
                (
                    "monto",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Monto a pagar de la contribución para el período (R-CODE-4).",
                        max_digits=18,
                    ),
                ),
                (
                    "referencia",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Referencia del pago (planilla, comprobante o transferencia).",
                        max_length=100,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente de pago"),
                            ("pagado", "Pagado"),
                            ("anulado", "Anulado"),
                        ],
                        db_index=True,
                        default="pendiente",
                        max_length=15,
                    ),
                ),
                (
                    "fecha_pago",
                    models.DateField(
                        blank=True,
                        help_text="Fecha en que se ejecutó el pago (se fija al pagar).",
                        null=True,
                    ),
                ),
                (
                    "contribucion",
                    models.ForeignKey(
                        help_text="Contribución parafiscal que se paga (IVSS, FAOV, INCES…).",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pagos_parafiscales",
                        to="fiscal.contribucionparafiscal",
                    ),
                ),
                (
                    "id_empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pagos_parafiscales",
                        to="core.empresa",
                    ),
                ),
                (
                    "id_moneda",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pagos_parafiscales",
                        to="finanzas.moneda",
                    ),
                ),
                (
                    "id_pago",
                    models.ForeignKey(
                        blank=True,
                        help_text="Pago genérico de finanzas generado por la acción 'pagar'.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pagos_parafiscales",
                        to="finanzas.pago",
                    ),
                ),
                (
                    "id_proceso_nomina",
                    models.ForeignKey(
                        blank=True,
                        help_text="Proceso de nómina del que proviene el cálculo (trazabilidad, opcional).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pagos_parafiscales",
                        to="nomina.procesonomina",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pago de Contribución Parafiscal",
                "verbose_name_plural": "Pagos de Contribuciones Parafiscales",
                "db_table": "fiscal_pago_contribucion_parafiscal",
                "ordering": ["-periodo_año", "-periodo_mes", "-fecha_creacion"],
                "indexes": [
                    models.Index(
                        fields=["id_empresa", "estado"],
                        name="fiscal_pago_id_empr_7ec0eb_idx",
                    ),
                    models.Index(
                        fields=["id_empresa", "periodo_año", "periodo_mes"],
                        name="fiscal_pago_id_empr_353fde_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("estado", "anulado"), _negated=True),
                        fields=(
                            "id_empresa",
                            "contribucion",
                            "periodo_año",
                            "periodo_mes",
                        ),
                        name="uniq_pago_parafiscal_periodo_no_anulado",
                    )
                ],
            },
        ),
    ]
