# Generated by Django 5.2.15 on 2026-06-12 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_claveidempotencia_usuario_ttl"),
        ("finanzas", "0040_pagotercero"),
        ("fiscal", "0007_pagocontribucionparafiscal"),
        ("nomina", "0003_alter_conceptonomina_id_concepto_nomina_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="pagocontribucionparafiscal",
            constraint=models.CheckConstraint(
                condition=models.Q(("periodo_mes__gte", 1), ("periodo_mes__lte", 12)),
                name="ck_pago_parafiscal_mes_entre_1_y_12",
            ),
        ),
        migrations.AddConstraint(
            model_name="pagocontribucionparafiscal",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("periodo_año__gte", 2000), ("periodo_año__lte", 2100)
                ),
                name="ck_pago_parafiscal_anio_entre_2000_y_2100",
            ),
        ),
    ]
