# Generated by Django 5.2.4 on 2025-08-02 20:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_initial'),
        ('finanzas', '0001_initial'),
        ('inventario', '0001_initial'),
        ('manufactura', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalisisVariacionCosto',
            fields=[
                ('id_analisis_variacion', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_costo', models.CharField(choices=[('MATERIAL_DIRECTO', 'Material Directo'), ('MANO_OBRA_DIRECTA', 'Mano de Obra Directa'), ('COSTOS_INDIRECTOS', 'Costos Indirectos'), ('OVERHEAD', 'Overhead')], max_length=20)),
                ('costo_estandar', models.DecimalField(decimal_places=4, max_digits=18)),
                ('costo_real', models.DecimalField(decimal_places=4, max_digits=18)),
                ('variacion_cantidad', models.DecimalField(decimal_places=4, default=0.0, max_digits=18)),
                ('variacion_precio', models.DecimalField(decimal_places=4, default=0.0, max_digits=18)),
                ('variacion_total', models.DecimalField(decimal_places=4, max_digits=18)),
                ('porcentaje_variacion', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('tipo_variacion', models.CharField(choices=[('FAVORABLE', 'Favorable'), ('DESFAVORABLE', 'Desfavorable'), ('NEUTRO', 'Neutro')], max_length=15)),
                ('fecha_analisis', models.DateTimeField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analisis_variacion_costos', to='core.empresa')),
                ('id_orden_produccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analisis_variacion', to='manufactura.ordenproduccion')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analisis_variacion', to='inventario.producto')),
            ],
            options={
                'verbose_name': 'Análisis de Variación de Costo',
                'verbose_name_plural': 'Análisis de Variaciones de Costos',
                'db_table': 'costos_analisis_variacion_costo',
            },
        ),
        migrations.CreateModel(
            name='CostoEstandarProducto',
            fields=[
                ('id_costo_estandar', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_costo', models.CharField(choices=[('MATERIAL_DIRECTO', 'Material Directo'), ('MANO_OBRA_DIRECTA', 'Mano de Obra Directa'), ('COSTOS_INDIRECTOS', 'Costos Indirectos'), ('OVERHEAD', 'Overhead')], max_length=20)),
                ('costo_unitario_estandar', models.DecimalField(decimal_places=4, max_digits=18)),
                ('fecha_vigencia_desde', models.DateField()),
                ('fecha_vigencia_hasta', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costos_estandar', to='core.empresa')),
                ('id_moneda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costos_estandar', to='finanzas.moneda')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costos_estandar', to='inventario.producto')),
            ],
            options={
                'verbose_name': 'Costo Estándar de Producto',
                'verbose_name_plural': 'Costos Estándar de Productos',
                'db_table': 'costos_costo_estandar_producto',
            },
        ),
        migrations.CreateModel(
            name='CostoProduccion',
            fields=[
                ('id_costo_produccion', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_costo', models.CharField(choices=[('MATERIAL_DIRECTO', 'Material Directo'), ('MANO_OBRA_DIRECTA', 'Mano de Obra Directa'), ('COSTOS_INDIRECTOS', 'Costos Indirectos'), ('OVERHEAD', 'Overhead')], max_length=20)),
                ('costo_unitario', models.DecimalField(decimal_places=4, max_digits=18)),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=18)),
                ('costo_total', models.DecimalField(decimal_places=4, max_digits=18)),
                ('fecha_calculo', models.DateTimeField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costos_produccion', to='core.empresa')),
                ('id_moneda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costos_produccion', to='finanzas.moneda')),
                ('id_orden_produccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costos', to='manufactura.ordenproduccion')),
            ],
            options={
                'verbose_name': 'Costo de Producción',
                'verbose_name_plural': 'Costos de Producción',
                'db_table': 'costos_costo_produccion',
            },
        ),
    ]
