# Generated by Django 5.2.4 on 2025-08-02 20:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionIntegracion',
            fields=[
                ('id_configuracion', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_integracion', models.CharField(max_length=100)),
                ('tipo_integracion', models.CharField(max_length=50)),
                ('url_endpoint', models.URLField(blank=True, null=True)),
                ('credenciales_json', models.JSONField(blank=True, null=True)),
                ('formato_datos', models.CharField(max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='LogIntegracion',
            fields=[
                ('id_log_integracion', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('tipo_transaccion', models.CharField(max_length=50)),
                ('id_entidad_origen', models.UUIDField(blank=True, null=True)),
                ('nombre_modelo_origen', models.CharField(blank=True, max_length=100, null=True)),
                ('request_payload_json', models.JSONField(blank=True, null=True)),
                ('response_payload_json', models.JSONField(blank=True, null=True)),
                ('estado_integracion', models.CharField(max_length=50)),
                ('mensaje_error', models.TextField(blank=True, null=True)),
                ('duracion_ms', models.IntegerField(blank=True, null=True)),
                ('id_configuracion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integracion_b2b.configuracionintegracion')),
            ],
        ),
        migrations.CreateModel(
            name='MapeoCampo',
            fields=[
                ('id_mapeo_campo', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_campo_interno', models.CharField(max_length=100)),
                ('nombre_campo_externo', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('id_configuracion_integracion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integracion_b2b.configuracionintegracion')),
            ],
        ),
    ]
