# Generated by Django 5.2.4 on 2025-08-02 20:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantillaMigracion',
            fields=[
                ('id_plantilla_migracion', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_plantilla', models.CharField(max_length=100)),
                ('modulo_destino', models.CharField(max_length=50)),
                ('modelo_destino', models.CharField(max_length=100)),
                ('formato_archivo', models.CharField(max_length=20)),
                ('estructura_json', models.JSONField()),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProcesoMigracion',
            fields=[
                ('id_proceso_migracion', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('estado_proceso', models.CharField(max_length=50)),
                ('total_registros_procesados', models.IntegerField(default=0)),
                ('total_registros_exitosos', models.IntegerField(default=0)),
                ('total_registros_fallidos', models.IntegerField(default=0)),
                ('ruta_archivo_cargado', models.CharField(max_length=500)),
                ('ruta_archivo_errores', models.CharField(blank=True, max_length=500, null=True)),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
                ('id_plantilla_migracion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='migracion_datos.plantillamigracion')),
                ('id_usuario_ejecutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleErrorMigracion',
            fields=[
                ('id_detalle_error', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_fila_archivo', models.IntegerField(blank=True, null=True)),
                ('campo_error', models.CharField(blank=True, max_length=100, null=True)),
                ('mensaje_error', models.TextField()),
                ('datos_originales_json', models.JSONField(blank=True, null=True)),
                ('fecha_registro_error', models.DateTimeField(auto_now_add=True)),
                ('id_proceso_migracion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='migracion_datos.procesomigracion')),
            ],
        ),
    ]
