# Generated by Django 5.2.4 on 2026-06-02 03:16

import apps.core.uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("migracion_datos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="detalleerrormigracion",
            name="id_detalle_error",
            field=models.UUIDField(
                default=apps.core.uuid.uuid7,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="plantillamigracion",
            name="id_plantilla_migracion",
            field=models.UUIDField(
                default=apps.core.uuid.uuid7,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="procesomigracion",
            name="id_proceso_migracion",
            field=models.UUIDField(
                default=apps.core.uuid.uuid7,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
