# Generated by Django 5.2.4 on 2025-08-02 20:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoValor',
            fields=[
                ('id_catalogo_valor', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo_catalogo', models.CharField(max_length=50)),
                ('valor', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('orden', models.IntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ParametroSistema',
            fields=[
                ('id_parametro', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_parametro', models.CharField(max_length=100)),
                ('codigo_parametro', models.CharField(max_length=50, unique=True)),
                ('valor_parametro', models.TextField()),
                ('tipo_dato', models.CharField(choices=[('TEXTO', 'TEXTO'), ('NUMERO', 'NUMERO'), ('BOOLEANO', 'BOOLEANO'), ('FECHA', 'FECHA')], max_length=20)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id_tipo_documento', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('modulo_origen', models.CharField(max_length=50)),
                ('es_transaccional', models.BooleanField(default=True)),
                ('prefijo_correlativo', models.CharField(blank=True, max_length=10, null=True)),
                ('ultimo_correlativo', models.IntegerField(default=0)),
            ],
        ),
    ]
