# Generated by Django 5.2.4 on 2026-05-19 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion_motor', '0002_initial'),
        ('core', '0016_fix_unique_numeros_documento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parametrosistema',
            options={'verbose_name': 'Parámetro del Sistema', 'verbose_name_plural': 'Parámetros del Sistema'},
        ),
        migrations.AlterField(
            model_name='parametrosistema',
            name='codigo_parametro',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='parametrosistema',
            unique_together={('id_empresa', 'codigo_parametro')},
        ),
        migrations.AlterModelTable(
            name='parametrosistema',
            table='configuracion_motor_parametro_sistema',
        ),
    ]
