# Generated by Django 5.2.4 on 2025-08-02 20:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaTicket',
            fields=[
                ('id_categoria_ticket', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='BaseConocimientoArticulo',
            fields=[
                ('id_articulo', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('contenido', models.TextField()),
                ('palabras_clave', models.TextField(blank=True, null=True)),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_ultima_revision', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('visibilidad', models.CharField(choices=[('INTERNA', 'Interna'), ('PUBLICA', 'Pública')], max_length=20)),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
                ('id_categoria_ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='servicio_cliente.categoriaticket')),
            ],
        ),
        migrations.CreateModel(
            name='TicketSoporte',
            fields=[
                ('id_ticket', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('numero_ticket', models.CharField(max_length=50, unique=True)),
                ('asunto', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('id_cliente_temp', models.UUIDField(blank=True, null=True)),
                ('id_usuario_reporta_temp', models.UUIDField(blank=True, null=True)),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], max_length=20)),
                ('estado_ticket', models.CharField(choices=[('ABIERTO', 'Abierto'), ('ASIGNADO', 'Asignado'), ('EN_PROGRESO', 'En Progreso'), ('PENDIENTE_CLIENTE', 'Pendiente Cliente'), ('RESUELTO', 'Resuelto'), ('CERRADO', 'Cerrado'), ('ESCALADO', 'Escalado')], max_length=50)),
                ('id_agente_asignado_temp', models.UUIDField(blank=True, null=True)),
                ('fecha_apertura', models.DateTimeField(auto_now_add=True)),
                ('fecha_ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('sla_vencimiento', models.DateTimeField(blank=True, null=True)),
                ('id_categoria_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicio_cliente.categoriaticket')),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='InteraccionTicket',
            fields=[
                ('id_interaccion', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('fecha_hora_interaccion', models.DateTimeField(auto_now_add=True)),
                ('tipo_interaccion', models.CharField(choices=[('COMENTARIO', 'Comentario'), ('EMAIL', 'Email'), ('LLAMADA', 'Llamada'), ('CAMBIO_ESTADO', 'Cambio Estado'), ('ASIGNACION', 'Asignación'), ('ADJUNTO', 'Adjunto')], max_length=50)),
                ('id_usuario_interactor_temp', models.UUIDField(blank=True, null=True)),
                ('contenido', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicio_cliente.ticketsoporte')),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackCliente',
            fields=[
                ('id_feedback', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('id_cliente_temp', models.UUIDField(blank=True, null=True)),
                ('fecha_feedback', models.DateTimeField(auto_now_add=True)),
                ('calificacion', models.IntegerField(blank=True, null=True)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('tipo_feedback', models.CharField(choices=[('ENCUESTA_SATISFACCION', 'Encuesta Satisfacción'), ('SUGERENCIA', 'Sugerencia'), ('QUEJA', 'Queja'), ('OTRO', 'Otro')], max_length=50)),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
                ('id_ticket_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='servicio_cliente.ticketsoporte')),
            ],
        ),
    ]
