# Generated by Django 5.2.4 on 2026-05-19 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_fix_unique_numeros_documento'),
        ('servicio_cliente', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticketsoporte',
            options={'verbose_name': 'Ticket de Soporte', 'verbose_name_plural': 'Tickets de Soporte'},
        ),
        migrations.AlterField(
            model_name='ticketsoporte',
            name='numero_ticket',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='ticketsoporte',
            unique_together={('id_empresa', 'numero_ticket')},
        ),
        migrations.AlterModelTable(
            name='ticketsoporte',
            table='servicio_cliente_ticket_soporte',
        ),
    ]
