# Generated by Django 5.2.4 on 2026-06-02 03:16

import apps.core.uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("servicio_cliente", "0002_fix_unique_numero_ticket"),
    ]

    operations = [
        migrations.AlterField(
            model_name="baseconocimientoarticulo",
            name="id_articulo",
            field=models.UUIDField(
                default=apps.core.uuid.uuid7, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="categoriaticket",
            name="id_categoria_ticket",
            field=models.UUIDField(
                default=apps.core.uuid.uuid7, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="feedbackcliente",
            name="id_feedback",
            field=models.UUIDField(
                default=apps.core.uuid.uuid7, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="interaccionticket",
            name="id_interaccion",
            field=models.UUIDField(
                default=apps.core.uuid.uuid7, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="ticketsoporte",
            name="id_ticket",
            field=models.UUIDField(
                default=apps.core.uuid.uuid7, primary_key=True, serialize=False
            ),
        ),
    ]
