# Generated by Django 5.2.4 on 2025-08-02 20:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficio',
            fields=[
                ('id_beneficio', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_beneficio', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo_beneficio', models.CharField(choices=[('MONETARIO', 'Monetario'), ('NO_MONETARIO', 'No Monetario'), ('TIEMPO', 'Tiempo'), ('SALUD', 'Salud'), ('EDUCACION', 'Educación'), ('TRANSPORTE', 'Transporte'), ('ALIMENTACION', 'Alimentación'), ('OTRO', 'Otro')], max_length=20)),
                ('monto_fijo', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('porcentaje_salario', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('es_obligatorio', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficios', to='core.empresa')),
            ],
            options={
                'verbose_name': 'Beneficio',
                'verbose_name_plural': 'Beneficios',
                'db_table': 'rrhh_beneficio',
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia_externa', models.CharField(blank=True, max_length=100, null=True)),
                ('documento_json', models.JSONField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia_externa', models.CharField(blank=True, max_length=100, null=True)),
                ('documento_json', models.JSONField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('cedula', models.CharField(max_length=20, unique=True)),
                ('fecha_ingreso', models.DateField()),
                ('activo', models.BooleanField(default=True)),
                ('cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rrhh.cargo')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empleados', to='core.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='BeneficioEmpleado',
            fields=[
                ('id_beneficio_empleado', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('monto_personalizado', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('porcentaje_personalizado', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('SUSPENDIDO', 'Suspendido'), ('TERMINADO', 'Terminado')], default='ACTIVO', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_beneficio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='rrhh.beneficio')),
                ('id_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficios', to='rrhh.empleado')),
            ],
            options={
                'verbose_name': 'Beneficio de Empleado',
                'verbose_name_plural': 'Beneficios de Empleados',
                'db_table': 'rrhh_beneficio_empleado',
            },
        ),
        migrations.CreateModel(
            name='TipoLicencia',
            fields=[
                ('id_tipo_licencia', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_tipo', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('es_remunerada', models.BooleanField(default=True)),
                ('dias_maximos_por_año', models.IntegerField(blank=True, null=True)),
                ('requiere_aprobacion', models.BooleanField(default=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos_licencia', to='core.empresa')),
            ],
            options={
                'verbose_name': 'Tipo de Licencia',
                'verbose_name_plural': 'Tipos de Licencia',
                'db_table': 'rrhh_tipo_licencia',
            },
        ),
        migrations.CreateModel(
            name='LicenciaEmpleado',
            fields=[
                ('id_licencia', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('dias_solicitados', models.IntegerField()),
                ('motivo', models.TextField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada'), ('EN_CURSO', 'En Curso'), ('FINALIZADA', 'Finalizada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('observaciones_aprobacion', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_aprobador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='licencias_aprobadas', to='rrhh.empleado')),
                ('id_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licencias', to='rrhh.empleado')),
                ('id_tipo_licencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licencias', to='rrhh.tipolicencia')),
            ],
            options={
                'verbose_name': 'Licencia de Empleado',
                'verbose_name_plural': 'Licencias de Empleados',
                'db_table': 'rrhh_licencia_empleado',
            },
        ),
    ]
