# Generated by Django 5.2.4 on 2026-05-19 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_fix_unique_numeros_documento'),
        ('rrhh', '0002_empleado_contacto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empleado',
            options={'verbose_name': 'Empleado', 'verbose_name_plural': 'Empleados'},
        ),
        migrations.AlterField(
            model_name='empleado',
            name='cedula',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='empleado',
            unique_together={('empresa', 'cedula')},
        ),
        migrations.AlterModelTable(
            name='empleado',
            table='rrhh_empleado',
        ),
    ]
