# Generated by Django 5.2.4 on 2026-06-02 03:16

import apps.core.uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("saas", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="suscripcion",
            new_name="saas_suscri_id_empr_47df32_idx",
            old_name="saas_sus_empresa_estado_idx",
        ),
        migrations.RenameIndex(
            model_name="suscripcion",
            new_name="saas_suscri_fecha_f_5498a1_idx",
            old_name="saas_sus_fin_estado_idx",
        ),
        migrations.AlterField(
            model_name="plan",
            name="id_plan",
            field=models.UUIDField(
                default=apps.core.uuid.uuid7,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="max_documentos_mes",
            field=models.PositiveIntegerField(
                default=100,
                help_text="Máximo de documentos (facturas/pedidos) por mes (0 = ilimitado).",
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="max_empresas",
            field=models.PositiveIntegerField(
                default=1, help_text="Máximo de empresas en la cuenta (0 = ilimitado)."
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="max_usuarios",
            field=models.PositiveIntegerField(
                default=5,
                help_text="Máximo de usuarios activos permitidos (0 = ilimitado).",
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="permite_api",
            field=models.BooleanField(
                default=False, help_text="Acceso a la API REST para integraciones."
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="permite_ia",
            field=models.BooleanField(
                default=False,
                help_text="Acceso a módulos de Inteligencia Artificial (agentes M9).",
            ),
        ),
        migrations.AlterField(
            model_name="suscripcion",
            name="id_suscripcion",
            field=models.UUIDField(
                default=apps.core.uuid.uuid7,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
