# Generated by Django 5.2.4 on 2025-08-02 20:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogAuditoria',
            fields=[
                ('id_log_auditoria', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('id_entidad_afectada', models.UUIDField(blank=True, null=True)),
                ('nombre_entidad_afectada', models.CharField(blank=True, max_length=100, null=True)),
                ('modulo', models.CharField(max_length=50)),
                ('tipo_accion', models.CharField(max_length=50)),
                ('descripcion_accion', models.TextField(blank=True, null=True)),
                ('cambios_json', models.JSONField(blank=True, null=True)),
                ('fecha_hora_accion', models.DateTimeField(auto_now_add=True)),
                ('direccion_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('navegador_info', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
