# Generated by Django 5.2.15 on 2026-06-22 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0011_rls_lote3_compras'),
        ('cuentas_por_pagar', '0006_rls_lote3_cuentas_por_pagar'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentaporpagar',
            name='id_recepcion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuentas_por_pagar', to='compras.recepcionmercancia'),
        ),
    ]
