# Generated by Django 5.2.15 on 2026-06-24 03:01

import apps.core.uuid
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_rls_lote3_core'),
        ('cuentas_por_pagar', '0007_cuentaporpagar_id_recepcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiferenciaCambiaria',
            fields=[
                ('id_diferencia', models.UUIDField(default=apps.core.uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('monto_moneda', models.DecimalField(decimal_places=4, max_digits=18)),
                ('tasa_original', models.DecimalField(decimal_places=8, max_digits=18)),
                ('tasa_pago', models.DecimalField(decimal_places=8, max_digits=18)),
                ('monto_diferencia', models.DecimalField(decimal_places=4, max_digits=18)),
                ('tipo', models.CharField(choices=[('GANANCIA', 'Ganancia'), ('PERDIDA', 'Pérdida')], max_length=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_abono_cxp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diferencias_cambiarias', to='cuentas_por_pagar.abonocxp')),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
            ],
            options={
                'verbose_name': 'Diferencia Cambiaria',
                'verbose_name_plural': 'Diferencias Cambiarias',
                'db_table': 'cuentas_por_pagar_diferencia_cambiaria',
            },
        ),
    ]
