# Generated by Django 5.2.4 on 2025-08-02 20:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id_metodo_pago', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('referencia_externa', models.CharField(blank=True, max_length=100, null=True)),
                ('documento_json', models.JSONField(blank=True, null=True)),
                ('nombre_metodo', models.CharField(max_length=100)),
                ('tipo_metodo', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('ELECTRONICO', 'Electrónico'), ('TARJETA', 'Tarjeta'), ('CHEQUE', 'Cheque'), ('CREDITO', 'Crédito'), ('OTRO', 'Otro')], max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('es_generico', models.BooleanField(default=False, help_text='Si es True, es un método global del sistema, no editable por usuarios normales.')),
                ('es_publico', models.BooleanField(default=False, help_text='Si es True, el método es visible para todas las empresas.')),
                ('empresa', models.ForeignKey(blank=True, help_text='Empresa propietaria del método. Null si es genérico.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metodos_pago_empresa', to='core.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='MetodoPagoEmpresaActiva',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activa', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metodos_pago_activos', to='core.empresa')),
                ('metodo_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresas_activas', to='finanzas.metodopago')),
            ],
        ),
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('id_moneda', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_moneda', models.CharField(choices=[('fiat', 'Fiat'), ('crypto', 'Cripto'), ('otro', 'Otro')], default='fiat', max_length=10)),
                ('codigo_iso', models.CharField(max_length=5, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('referencia_externa', models.CharField(blank=True, max_length=100, null=True)),
                ('documento_json', models.JSONField(blank=True, null=True)),
                ('tipo_operacion', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_cierre_estimada', models.DateField(blank=True, null=True)),
                ('simbolo', models.CharField(max_length=5)),
                ('decimales', models.IntegerField(default=2)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('es_generica', models.BooleanField(default=False, help_text='Si es True, es una moneda global del sistema, no editable por usuarios normales.')),
                ('es_publica', models.BooleanField(default=False, help_text='Si es True, la moneda es visible para todas las empresas.')),
                ('empresa', models.ForeignKey(blank=True, help_text='Empresa propietaria de la moneda. Null si es genérica.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monedas_empresa', to='core.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='CuentaBancariaEmpresa',
            fields=[
                ('id_cuenta_bancaria', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_banco', models.CharField(max_length=100)),
                ('numero_cuenta', models.CharField(max_length=50, unique=True)),
                ('tipo_cuenta', models.CharField(choices=[('AHORRO', 'Ahorro'), ('CORRIENTE', 'Corriente'), ('CREDITO', 'Crédito')], max_length=50)),
                ('saldo_actual', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuentas_bancarias_finanzas', to='core.empresa')),
                ('id_moneda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuentas_bancarias_finanzas', to='finanzas.moneda')),
            ],
            options={
                'verbose_name': 'Cuenta Bancaria Empresa',
                'verbose_name_plural': 'Cuentas Bancarias Empresa',
                'db_table': 'finanzas_cuenta_bancaria_empresa',
            },
        ),
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id_caja', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('tipo_caja', models.CharField(choices=[('REGISTRADORA', 'Caja Registradora'), ('GERENCIA', 'Caja Gerente Sucursal'), ('MATRIZ', 'Caja Matriz/Principal'), ('OTRO', 'Otro')], default='REGISTRADORA', max_length=20)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('saldo_inicial', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('saldo_actual', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('activa', models.BooleanField(default=True)),
                ('referencia_externa', models.CharField(blank=True, max_length=100, null=True)),
                ('documento_json', models.JSONField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cajas', to='core.empresa')),
                ('sucursal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cajas', to='core.sucursal')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cajas', to='finanzas.moneda')),
            ],
            options={
                'verbose_name': 'Caja',
                'verbose_name_plural': 'Cajas',
                'db_table': 'finanzas_caja',
            },
        ),
        migrations.CreateModel(
            name='MonedaEmpresaActiva',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activa', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monedas_activas', to='core.empresa')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresas_activas', to='finanzas.moneda')),
            ],
        ),
        migrations.CreateModel(
            name='TasaCambio',
            fields=[
                ('id_tasa_cambio', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_tasa', models.CharField(choices=[('OFICIAL_BCV', 'Oficial BCV'), ('ESPECIAL_USUARIO', 'Especial Usuario'), ('PROMEDIO_MERCADO', 'Promedio Mercado'), ('FIJA', 'Fija')], max_length=20)),
                ('valor_tasa', models.DecimalField(decimal_places=8, max_digits=18)),
                ('fecha_tasa', models.DateField()),
                ('hora_tasa', models.TimeField(blank=True, null=True)),
                ('referencia_externa', models.CharField(blank=True, max_length=100, null=True)),
                ('documento_json', models.JSONField(blank=True, null=True)),
                ('tipo_operacion', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_cierre_estimada', models.DateField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_empresa', models.ForeignKey(blank=True, help_text='Para OFICIAL_BCV puede ser null y será global para todas las empresas.', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
                ('id_moneda_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasa_destino', to='finanzas.moneda')),
                ('id_moneda_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasa_origen', to='finanzas.moneda')),
                ('id_usuario_registro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TransaccionFinanciera',
            fields=[
                ('id_transaccion', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_hora_transaccion', models.DateTimeField()),
                ('tipo_transaccion', models.CharField(choices=[('INGRESO', 'Ingreso'), ('EGRESO', 'Egreso'), ('TRANSFERENCIA', 'Transferencia')], max_length=20)),
                ('monto_transaccion', models.DecimalField(decimal_places=2, max_digits=18)),
                ('monto_base_empresa', models.DecimalField(decimal_places=2, max_digits=18)),
                ('referencia_pago', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones_financieras', to='core.empresa')),
                ('id_metodo_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to='finanzas.metodopago')),
                ('id_moneda_transaccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones_moneda', to='finanzas.moneda')),
                ('id_usuario_registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones_registradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transacción Financiera',
                'verbose_name_plural': 'Transacciones Financieras',
                'db_table': 'finanzas_transaccion_financiera',
            },
        ),
        migrations.CreateModel(
            name='MovimientoCajaBanco',
            fields=[
                ('id_movimiento', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_movimiento', models.DateField()),
                ('hora_movimiento', models.TimeField()),
                ('tipo_movimiento', models.CharField(choices=[('INGRESO', 'Ingreso'), ('EGRESO', 'Egreso'), ('TRANSFERENCIA_ENTRADA', 'Transferencia Entrada'), ('TRANSFERENCIA_SALIDA', 'Transferencia Salida')], max_length=50)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=18)),
                ('concepto', models.CharField(max_length=255)),
                ('referencia', models.CharField(blank=True, max_length=100, null=True)),
                ('saldo_anterior', models.DecimalField(decimal_places=2, max_digits=18)),
                ('saldo_nuevo', models.DecimalField(decimal_places=2, max_digits=18)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_caja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='finanzas.caja')),
                ('id_cuenta_bancaria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='finanzas.cuentabancariaempresa')),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_caja_banco', to='core.empresa')),
                ('id_moneda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_caja_banco', to='finanzas.moneda')),
                ('id_usuario_registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_caja_banco_registrados', to=settings.AUTH_USER_MODEL)),
                ('id_transaccion_financiera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_caja_banco', to='finanzas.transaccionfinanciera')),
            ],
            options={
                'verbose_name': 'Movimiento de Caja/Banco',
                'verbose_name_plural': 'Movimientos de Caja/Banco',
                'db_table': 'finanzas_movimiento_caja_banco',
            },
        ),
    ]
