# Generated by Django 5.2.4 on 2025-08-04 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneda',
            name='pais_codigo_iso',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Código ISO del País'),
        ),
        migrations.AddField(
            model_name='moneda',
            name='pais_nombre',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre del País'),
        ),
        migrations.AddField(
            model_name='transaccionfinanciera',
            name='id_moneda_base',
            field=models.ForeignKey(null=True, blank=True, help_text='Moneda base de la empresa para la transacción.', on_delete=django.db.models.deletion.CASCADE, related_name='transacciones_base', to='finanzas.moneda'),
        ),
        migrations.AddField(
            model_name='transaccionfinanciera',
            name='id_moneda_pais_empresa',
            field=models.ForeignKey(null=True, blank=True, help_text='Moneda país de la empresa para la transacción.', on_delete=django.db.models.deletion.CASCADE, related_name='transacciones_pais_empresa', to='finanzas.moneda'),
        ),
        migrations.AddField(
            model_name='transaccionfinanciera',
            name='monto_moneda_pais',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monto equivalente en moneda país de la empresa.', max_digits=18, null=True),
        ),
    ]
