# Generated by Django 5.2.4 on 2025-08-04 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0002_moneda_pais_codigo_iso_moneda_pais_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccionfinanciera',
            name='id_moneda_base',
            field=models.ForeignKey(blank=True, help_text='Moneda base de la empresa para la transacción.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transacciones_base', to='finanzas.moneda'),
        ),
        migrations.AlterField(
            model_name='transaccionfinanciera',
            name='id_moneda_pais_empresa',
            field=models.ForeignKey(blank=True, help_text='Moneda país de la empresa para la transacción.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transacciones_pais_empresa', to='finanzas.moneda'),
        ),
    ]
