# Generated by Django 5.2.4 on 2025-08-05 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0003_alter_transaccionfinanciera_id_moneda_base_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccionfinanciera',
            name='id_caja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacciones_financieras', to='finanzas.caja'),
        ),
        migrations.AddField(
            model_name='transaccionfinanciera',
            name='id_cuenta_bancaria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacciones_financieras', to='finanzas.cuentabancariaempresa'),
        ),
        migrations.AddField(
            model_name='transaccionfinanciera',
            name='nro_documento_asociado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaccionfinanciera',
            name='tipo_documento_asociado',
            field=models.CharField(blank=True, choices=[('COMPRA', 'Compra'), ('VENTA', 'Venta'), ('GASTO', 'Gasto'), ('NOMINA', 'Nómina'), ('AJUSTE', 'Ajuste')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='movimientocajabanco',
            name='tipo_movimiento',
            field=models.CharField(choices=[('INGRESO', 'Ingreso'), ('EGRESO', 'Egreso'), ('TRANSFERENCIA_ENTRADA', 'Transferencia Entrada'), ('TRANSFERENCIA_SALIDA', 'Transferencia Salida'), ('AJUSTE_POSITIVO', 'Ajuste Positivo'), ('AJUSTE_NEGATIVO', 'Ajuste Negativo')], max_length=50),
        ),
        migrations.AlterField(
            model_name='transaccionfinanciera',
            name='tipo_transaccion',
            field=models.CharField(choices=[('INGRESO', 'Ingreso'), ('EGRESO', 'Egreso')], max_length=20),
        ),
    ]
