# Generated by Django 5.2.4 on 2025-08-07 15:59

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_empresa_id_moneda_pais_empresa_pais_codigo_iso_and_more'),
        ('finanzas', '0004_transaccionfinanciera_id_caja_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='caja',
            name='fecha_ultimo_cierre',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora del último cierre de caja.', null=True),
        ),
        migrations.AddField(
            model_name='caja',
            name='metodos_pago',
            field=models.ManyToManyField(blank=True, help_text='Métodos de pago permitidos para esta caja.', related_name='cajas', to='finanzas.metodopago'),
        ),
        migrations.AddField(
            model_name='cuentabancariaempresa',
            name='metodos_pago',
            field=models.ManyToManyField(blank=True, help_text='Métodos de pago permitidos para esta cuenta bancaria.', related_name='cuentas_bancarias', to='finanzas.metodopago'),
        ),
        migrations.AddField(
            model_name='cuentabancariaempresa',
            name='monedas',
            field=models.ManyToManyField(blank=True, help_text='Monedas aceptadas por este método de pago.', related_name='metodos_pago', to='finanzas.moneda'),
        ),
        migrations.CreateModel(
            name='Datafono',
            fields=[
                ('id_datafono', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('serial', models.CharField(help_text='Número de serie o identificación única del datafono.', max_length=100, unique=True)),
                ('comision_porcentaje', models.DecimalField(decimal_places=2, default=0.0, help_text='Porcentaje de comisión por transacción.', max_digits=5)),
                ('saldo_temporal', models.DecimalField(decimal_places=2, default=0.0, help_text='Saldo acumulado de transacciones no cerradas.', max_digits=18)),
                ('fecha_ultimo_cierre', models.DateTimeField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_caja', models.ForeignKey(blank=True, help_text='Caja principal a la que está asociado el datafono.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='datafonos', to='finanzas.caja')),
                ('id_cuenta_bancaria_asociada', models.ForeignKey(blank=True, help_text='Cuenta bancaria donde se depositan los fondos.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='datafonos', to='finanzas.cuentabancariaempresa')),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datafonos', to='core.empresa')),
                ('id_sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datafonos', to='core.sucursal')),
            ],
            options={
                'verbose_name': 'Datafono',
                'verbose_name_plural': 'Datafonos',
                'db_table': 'finanzas_datafono',
            },
        ),
        migrations.CreateModel(
            name='SesionCaja',
            fields=[
                ('id_sesion', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('ABIERTA', 'Abierta'), ('CERRADA', 'Cerrada')], default='ABIERTA', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('saldo_inicial', models.JSONField(default=dict, help_text='Saldos iniciales por caja y moneda')),
                ('saldo_final', models.JSONField(default=dict, help_text='Saldos finales por caja y moneda')),
                ('cajas', models.ManyToManyField(related_name='sesiones_caja', to='finanzas.caja')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones_caja', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sesión de Caja',
                'verbose_name_plural': 'Sesiones de Caja',
                'db_table': 'finanzas_sesion_caja',
            },
        ),
        migrations.CreateModel(
            name='TransaccionDatafono',
            fields=[
                ('id_transaccion_datafono', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=18)),
                ('referencia_bancaria', models.CharField(blank=True, help_text='Número de referencia de la operación en el datafono.', max_length=100, null=True)),
                ('fecha_hora_transaccion', models.DateTimeField(auto_now_add=True)),
                ('conciliada', models.BooleanField(default=False, help_text='Indica si la transacción fue incluida en un cierre y conciliada con el depósito bancario.')),
                ('id_datafono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones_datafono', to='finanzas.datafono')),
                ('id_transaccion_financiera_origen', models.ForeignKey(blank=True, help_text='Transacción de venta que originó el pago con datafono.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transacciones_datafono', to='finanzas.transaccionfinanciera')),
                ('id_usuario_registro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transacción de Datafono',
                'verbose_name_plural': 'Transacciones de Datafonos',
                'db_table': 'finanzas_transaccion_datafono',
            },
        ),
    ]
