# Generated by Django 5.2.4 on 2025-08-08 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0005_caja_fecha_ultimo_cierre_caja_metodos_pago_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='caja',
            name='monedas',
            field=models.ManyToManyField(blank=True, help_text='Monedas aceptadas por esta caja.', related_name='caja_monedas', to='finanzas.moneda'),
        ),
        migrations.AddField(
            model_name='metodopago',
            name='monedas',
            field=models.ManyToManyField(blank=True, help_text='Monedas aceptadas por este método de pago.', related_name='metodopago_monedas', to='finanzas.moneda'),
        ),
        migrations.AlterField(
            model_name='cuentabancariaempresa',
            name='monedas',
            field=models.ManyToManyField(blank=True, help_text='Monedas aceptadas por esta cuenta bancaria.', related_name='cuentabancaria_monedas', to='finanzas.moneda'),
        ),
    ]
