# Generated by Django 5.2.4 on 2025-11-05 01:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0006_caja_monedas_metodopago_monedas_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CajaUsuario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('es_predeterminada', models.BooleanField(default=False, help_text='Si es True, esta caja será sugerida por defecto para este usuario.')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_asignados', to='finanzas.caja')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cajas_asignadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Caja de Usuario',
                'verbose_name_plural': 'Cajas de Usuarios',
                'db_table': 'finanzas_caja_usuario',
                'unique_together': {('usuario', 'caja')},
            },
        ),
    ]
