# Generated by Django 5.2.4 on 2025-11-08 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0007_add_caja_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='caja',
            name='es_fisica',
            field=models.BooleanField(default=True, help_text='Si es True, representa una caja física con hardware específico. Si es False, es virtual.'),
        ),
        migrations.AddField(
            model_name='caja',
            name='identificador_hardware',
            field=models.CharField(blank=True, help_text='Identificador único del hardware físico (ej: MAC address, serial number)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='caja',
            name='requiere_sesion_activa',
            field=models.BooleanField(default=True, help_text='Si es True, requiere que un usuario tenga una sesión activa para operar'),
        ),
        migrations.AddField(
            model_name='caja',
            name='ubicacion_fisica',
            field=models.CharField(blank=True, help_text='Descripción de la ubicación física del puesto de trabajo', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sesioncaja',
            name='caja_fisica_principal',
            field=models.ForeignKey(blank=True, help_text='Caja física principal de la sesión', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sesiones_principales', to='finanzas.caja'),
        ),
        migrations.AddField(
            model_name='sesioncaja',
            name='cajas_virtuales',
            field=models.JSONField(default=list, help_text="Lista de cajas virtuales creadas en esta sesión: [{'id': 'uuid', 'nombre': 'str', 'monedas': ['VES', 'USD'], 'metodos_pago': ['EFECTIVO', 'TARJETA']}]"),
        ),
    ]
