# Generated by Django 5.2.4 on 2025-11-08 01:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_empresa_id_moneda_pais_empresa_pais_codigo_iso_and_more'),
        ('finanzas', '0008_agregar_cajas_fisicas_virtuales'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantillaCajaVirtual',
            fields=[
                ('id_plantilla', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text="Nombre descriptivo de la plantilla (ej: 'Caja Efectivo VES', 'Caja Tarjeta USD')", max_length=100)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada del uso de esta plantilla', null=True)),
                ('es_predeterminada', models.BooleanField(default=False, help_text='Si es True, se sugiere automáticamente al abrir sesión')),
                ('orden_sugerido', models.PositiveIntegerField(default=0, help_text='Orden de aparición en listas de sugerencias')),
                ('activa', models.BooleanField(default=True, help_text='Si es False, no se puede usar para crear nuevas cajas virtuales')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('creada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plantillas_creadas', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantillas_cajas_virtuales', to='core.empresa')),
                ('metodos_pago', models.ManyToManyField(blank=True, help_text='Métodos de pago que aceptará esta caja virtual', related_name='plantillas_cajas_virtuales', to='finanzas.metodopago')),
                ('monedas', models.ManyToManyField(blank=True, help_text='Monedas que aceptará esta caja virtual', related_name='plantillas_cajas_virtuales', to='finanzas.moneda')),
                ('sucursal', models.ForeignKey(blank=True, help_text='Si es null, la plantilla está disponible para todas las sucursales de la empresa', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plantillas_cajas_virtuales', to='core.sucursal')),
            ],
            options={
                'verbose_name': 'Plantilla de Caja Virtual',
                'verbose_name_plural': 'Plantillas de Cajas Virtuales',
                'db_table': 'finanzas_plantilla_caja_virtual',
                'ordering': ['orden_sugerido', 'nombre'],
                'unique_together': {('empresa', 'sucursal', 'nombre')},
            },
        ),
    ]
