# Generated by Django 5.2.4 on 2025-11-08 01:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_empresa_id_moneda_pais_empresa_pais_codigo_iso_and_more'),
        ('finanzas', '0009_agregar_plantillas_cajas_virtuales'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantillaMaestroCajasVirtuales',
            fields=[
                ('id_plantilla_maestro', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Nombre de la configuración maestra', max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('aplicar_a_todas_cajas_fisicas', models.BooleanField(default=True, help_text='Si es True, se aplica automáticamente a todas las cajas físicas')),
                ('aplicar_a_empleados_con_rol', models.CharField(blank=True, help_text='Nombre del rol/permiso para aplicar automáticamente a empleados', max_length=100, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('creada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantilla_maestro_cajas', to='core.empresa')),
                ('metodos_pago_base', models.ManyToManyField(help_text='Métodos de pago disponibles en la plantilla', related_name='plantillas_maestro_metodos', to='finanzas.metodopago')),
                ('monedas_base', models.ManyToManyField(help_text='Monedas disponibles en la plantilla', related_name='plantillas_maestro_monedas', to='finanzas.moneda')),
            ],
            options={
                'verbose_name': 'Plantilla Maestro Cajas Virtuales',
                'verbose_name_plural': 'Plantillas Maestro Cajas Virtuales',
                'db_table': 'finanzas_plantilla_maestro_cajas',
            },
        ),
        migrations.CreateModel(
            name='CajaMetodoPagoOverride',
            fields=[
                ('id_override', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deshabilitado', models.BooleanField(default=True)),
                ('motivo', models.TextField(blank=True, help_text='Motivo del override', null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('caja_fisica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overrides_metodos_pago', to='finanzas.caja')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('metodo_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overrides_por_caja', to='finanzas.metodopago')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overrides_cajas', to='core.sucursal')),
            ],
            options={
                'verbose_name': 'Override Método Pago Caja',
                'verbose_name_plural': 'Overrides Métodos Pago Cajas',
                'db_table': 'finanzas_caja_metodo_pago_override',
                'unique_together': {('caja_fisica', 'metodo_pago')},
            },
        ),
        migrations.CreateModel(
            name='CajaVirtualAuto',
            fields=[
                ('id_caja_virtual', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activa', models.BooleanField(default=True)),
                ('creada_automaticamente', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('caja_fisica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cajas_virtuales_auto', to='finanzas.caja')),
                ('empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cajas_virtuales_auto', to=settings.AUTH_USER_MODEL)),
                ('metodo_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finanzas.metodopago')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finanzas.moneda')),
                ('plantilla_maestro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cajas_virtuales_auto', to='finanzas.plantillamaestrocajasvirtuales')),
            ],
            options={
                'verbose_name': 'Caja Virtual Automática',
                'verbose_name_plural': 'Cajas Virtuales Automáticas',
                'db_table': 'finanzas_caja_virtual_auto',
                'unique_together': {('caja_fisica', 'plantilla_maestro', 'moneda', 'metodo_pago'), ('empleado', 'plantilla_maestro', 'moneda', 'metodo_pago')},
            },
        ),
    ]
