# Generated by Django 5.2.4 on 2025-11-08 02:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_empresa_id_moneda_pais_empresa_pais_codigo_iso_and_more'),
        ('finanzas', '0010_agregar_sistema_centralizado_cajas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caja',
            options={'verbose_name': 'Caja Virtual', 'verbose_name_plural': 'Cajas Virtuales'},
        ),
        migrations.AlterModelOptions(
            name='cajausuario',
            options={'verbose_name': 'Caja de Usuario (Legacy)', 'verbose_name_plural': 'Cajas de Usuarios (Legacy)'},
        ),
        migrations.RemoveField(
            model_name='caja',
            name='es_fisica',
        ),
        migrations.RemoveField(
            model_name='caja',
            name='fecha_ultimo_cierre',
        ),
        migrations.RemoveField(
            model_name='caja',
            name='identificador_hardware',
        ),
        migrations.RemoveField(
            model_name='caja',
            name='requiere_sesion_activa',
        ),
        migrations.RemoveField(
            model_name='caja',
            name='saldo_actual',
        ),
        migrations.RemoveField(
            model_name='caja',
            name='saldo_inicial',
        ),
        migrations.RemoveField(
            model_name='caja',
            name='ubicacion_fisica',
        ),
        migrations.AddField(
            model_name='caja',
            name='plantilla_maestro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cajas_virtuales', to='finanzas.plantillamaestrocajasvirtuales'),
        ),
        migrations.AlterField(
            model_name='caja',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cajas_virtuales', to='core.empresa'),
        ),
        migrations.AlterField(
            model_name='caja',
            name='metodos_pago',
            field=models.ManyToManyField(blank=True, help_text='Métodos de pago permitidos para esta caja virtual.', related_name='cajas_virtuales', to='finanzas.metodopago'),
        ),
        migrations.AlterField(
            model_name='caja',
            name='moneda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cajas_virtuales', to='finanzas.moneda'),
        ),
        migrations.AlterField(
            model_name='caja',
            name='monedas',
            field=models.ManyToManyField(blank=True, help_text='Monedas aceptadas por esta caja virtual.', related_name='caja_virtual_monedas', to='finanzas.moneda'),
        ),
        migrations.AlterField(
            model_name='caja',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cajas_virtuales', to='core.sucursal'),
        ),
        migrations.AlterField(
            model_name='caja',
            name='tipo_caja',
            field=models.CharField(choices=[('REGISTRADORA', 'Caja Registradora Virtual'), ('GERENCIA', 'Caja Gerente Virtual'), ('MATRIZ', 'Caja Matriz Virtual'), ('OTRO', 'Otro Virtual')], default='REGISTRADORA', max_length=20),
        ),
        migrations.AlterField(
            model_name='movimientocajabanco',
            name='id_caja',
            field=models.ForeignKey(blank=True, help_text='Referencia a caja virtual', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='finanzas.caja'),
        ),
        migrations.AlterModelTable(
            name='caja',
            table='finanzas_caja_virtual',
        ),
        migrations.CreateModel(
            name='CajaFisica',
            fields=[
                ('id_caja_fisica', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('tipo_caja', models.CharField(choices=[('REGISTRADORA', 'Caja Registradora'), ('GERENCIA', 'Caja Gerente Sucursal'), ('MATRIZ', 'Caja Matriz/Principal'), ('OTRO', 'Otro')], default='REGISTRADORA', max_length=20)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('saldo_inicial', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('saldo_actual', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('activa', models.BooleanField(default=True)),
                ('referencia_externa', models.CharField(blank=True, max_length=100, null=True)),
                ('documento_json', models.JSONField(blank=True, null=True)),
                ('fecha_ultimo_cierre', models.DateTimeField(blank=True, help_text='Fecha y hora del último cierre de caja física.', null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('identificador_hardware', models.CharField(blank=True, help_text='Identificador único del hardware físico (ej: MAC address, serial number)', max_length=100, null=True)),
                ('ubicacion_fisica', models.CharField(blank=True, help_text='Descripción de la ubicación física del puesto de trabajo', max_length=200, null=True)),
                ('requiere_sesion_activa', models.BooleanField(default=True, help_text='Si es True, requiere que un usuario tenga una sesión activa para operar')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cajas_fisicas', to='core.empresa')),
                ('metodos_pago', models.ManyToManyField(blank=True, help_text='Métodos de pago permitidos para esta caja física.', related_name='cajas_fisicas', to='finanzas.metodopago')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cajas_fisicas', to='finanzas.moneda')),
                ('monedas', models.ManyToManyField(blank=True, help_text='Monedas aceptadas por esta caja física.', related_name='caja_fisica_monedas', to='finanzas.moneda')),
                ('sucursal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cajas_fisicas', to='core.sucursal')),
            ],
            options={
                'verbose_name': 'Caja Física',
                'verbose_name_plural': 'Cajas Físicas',
                'db_table': 'finanzas_caja_fisica',
            },
        ),
        migrations.AddField(
            model_name='movimientocajabanco',
            name='id_caja_fisica',
            field=models.ForeignKey(blank=True, help_text='Referencia a caja física', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='finanzas.cajafisica'),
        ),
        migrations.CreateModel(
            name='CajaFisicaUsuario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('es_predeterminada', models.BooleanField(default=False, help_text='Si es True, esta caja física será sugerida por defecto para este usuario.')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('caja_fisica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_asignados', to='finanzas.cajafisica')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cajas_fisicas_asignadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Caja Física de Usuario',
                'verbose_name_plural': 'Cajas Físicas de Usuarios',
                'db_table': 'finanzas_caja_fisica_usuario',
                'unique_together': {('usuario', 'caja_fisica')},
            },
        ),
        migrations.CreateModel(
            name='CajaVirtualUsuario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('es_predeterminada', models.BooleanField(default=False, help_text='Si es True, esta caja virtual será sugerida por defecto para este usuario.')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('caja_virtual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_virtuales_asignados', to='finanzas.caja')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cajas_virtuales_asignadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Caja Virtual de Usuario',
                'verbose_name_plural': 'Cajas Virtuales de Usuarios',
                'db_table': 'finanzas_caja_virtual_usuario',
                'unique_together': {('usuario', 'caja_virtual')},
            },
        ),
    ]
