# Generated by Django 5.2.4 on 2025-11-08 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0011_alter_caja_options_alter_cajausuario_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caja',
            name='monedas',
        ),
        migrations.RemoveField(
            model_name='cajafisica',
            name='metodos_pago',
        ),
        migrations.RemoveField(
            model_name='cajafisica',
            name='moneda',
        ),
        migrations.RemoveField(
            model_name='cajafisica',
            name='monedas',
        ),
        migrations.RemoveField(
            model_name='plantillacajavirtual',
            name='monedas',
        ),
        migrations.RemoveField(
            model_name='plantillamaestrocajasvirtuales',
            name='monedas_base',
        ),
        migrations.AddField(
            model_name='cajafisica',
            name='cajas_virtuales',
            field=models.ManyToManyField(blank=True, help_text='Cajas virtuales asociadas a esta caja física.', related_name='cajas_fisicas_asociadas', to='finanzas.caja'),
        ),
        migrations.AddField(
            model_name='plantillacajavirtual',
            name='moneda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plantillas_cajas_virtuales', to='finanzas.moneda'),
        ),
        migrations.AddField(
            model_name='plantillamaestrocajasvirtuales',
            name='moneda_base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plantillas_maestro_monedas', to='finanzas.moneda'),
        ),
        migrations.AlterField(
            model_name='movimientocajabanco',
            name='id_moneda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_caja_banco', to='finanzas.moneda'),
        ),
    ]
