# Generated by Django 5.2.4 on 2025-11-08 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0012_remove_caja_monedas_remove_cajafisica_metodos_pago_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantillacajavirtual',
            name='moneda',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='plantillas_cajas_virtuales', to='finanzas.moneda'),
        ),
        migrations.AlterField(
            model_name='plantillamaestrocajasvirtuales',
            name='moneda_base',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='plantillas_maestro_monedas', to='finanzas.moneda'),
        ),
    ]
