# Generated by Django 5.2.4 on 2025-11-08 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0013_alter_plantillacajavirtual_moneda_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cajafisica',
            name='cajas_virtuales',
        ),
        migrations.AddField(
            model_name='caja',
            name='caja_fisica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cajas_virtuales', to='finanzas.cajafisica'),
        ),
        migrations.AlterField(
            model_name='plantillacajavirtual',
            name='moneda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantillas_cajas_virtuales', to='finanzas.moneda'),
        ),
        migrations.AlterField(
            model_name='plantillamaestrocajasvirtuales',
            name='moneda_base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantillas_maestro_monedas', to='finanzas.moneda'),
        ),
    ]
