# Generated by Django 5.2.4 on 2025-11-08 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0014_remove_cajafisica_cajas_virtuales_caja_caja_fisica_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlantillaCajaVirtual',
        ),
    ]
