# Generated by Django 5.2.4 on 2025-11-08 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0015_delete_plantillacajavirtual'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='metodopago',
            options={'verbose_name': 'Método de Pago', 'verbose_name_plural': 'Métodos de Pago'},
        ),
        migrations.AlterModelTable(
            name='metodopago',
            table='finanzas_metodo_pago',
        ),
    ]
