# Generated by Django 5.2.4 on 2025-11-08 04:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0016_alter_metodopago_options_alter_metodopago_table'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transacciondatafono',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CERRADO_EN_DATAFONO', 'Cerrado en Datafono'), ('ENVIADO_A_BANCO', 'Enviado a Banco'), ('CONCILIADO', 'Conciliado')], default='PENDIENTE', max_length=20),
        ),
        migrations.AddField(
            model_name='transacciondatafono',
            name='fecha_conciliacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transacciondatafono',
            name='fecha_envio_banco',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transacciondatafono',
            name='lote_bancario',
            field=models.CharField(blank=True, help_text='ID del lote bancario al que pertenece esta transacción', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='transacciondatafono',
            name='conciliada',
            field=models.BooleanField(default=False, help_text="Campo legacy - usar estado='CONCILIADO' en su lugar."),
        ),
        migrations.CreateModel(
            name='SesionDatafono',
            fields=[
                ('id_sesion', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_apertura', models.DateTimeField(auto_now_add=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('ABIERTA', 'Abierta'), ('CERRADA', 'Cerrada'), ('CONCILIADA', 'Conciliada')], default='ABIERTA', max_length=20)),
                ('total_transacciones', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('comision_calculada', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('neto_esperado', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('datafono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='finanzas.datafono')),
                ('usuario_apertura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones_datafono_abiertas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sesión de Datafono',
                'verbose_name_plural': 'Sesiones de Datafonos',
                'db_table': 'finanzas_sesion_datafono',
                'ordering': ['-fecha_apertura'],
            },
        ),
        migrations.CreateModel(
            name='DepositoDatafono',
            fields=[
                ('id_deposito', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lote_bancario', models.CharField(help_text='Identificador único del lote enviado al banco', max_length=50, unique=True)),
                ('fecha_envio', models.DateTimeField(help_text='Fecha y hora en que se envió el depósito al banco')),
                ('fecha_recepcion_banco', models.DateTimeField(blank=True, help_text='Fecha y hora en que el banco recibió el depósito', null=True)),
                ('fecha_conciliacion', models.DateTimeField(blank=True, help_text='Fecha y hora en que se concilió el depósito', null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Recepción'), ('RECIBIDO', 'Recibido en Banco'), ('CONCILIADO', 'Conciliado')], default='PENDIENTE', max_length=20)),
                ('total_bruto', models.DecimalField(decimal_places=2, help_text='Total de transacciones antes de comisión', max_digits=18)),
                ('comision_banco', models.DecimalField(decimal_places=2, help_text='Comisión calculada por el banco', max_digits=18)),
                ('total_neto', models.DecimalField(decimal_places=2, help_text='Monto neto recibido (bruto - comisión)', max_digits=18)),
                ('referencia_banco', models.CharField(blank=True, help_text='Referencia proporcionada por el banco', max_length=100, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('datafono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depositos', to='finanzas.datafono')),
                ('movimiento_banco', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deposito_datafono', to='finanzas.movimientocajabanco')),
                ('usuario_conciliacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depositos_conciliados', to=settings.AUTH_USER_MODEL)),
                ('usuario_envio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depositos_enviados', to=settings.AUTH_USER_MODEL)),
                ('sesion_datafono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depositos', to='finanzas.sesiondatafono')),
            ],
            options={
                'verbose_name': 'Depósito de Datafono',
                'verbose_name_plural': 'Depósitos de Datafonos',
                'db_table': 'finanzas_deposito_datafono',
                'ordering': ['-fecha_envio'],
            },
        ),
        migrations.AddField(
            model_name='transacciondatafono',
            name='sesion_datafono',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transacciones_datafono', to='finanzas.sesiondatafono'),
        ),
    ]
