# Generated by Django 5.2.4 on 2025-11-08 04:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_empresa_id_moneda_pais_empresa_pais_codigo_iso_and_more'),
        ('cuentas_por_pagar', '0001_initial'),
        ('finanzas', '0017_transacciondatafono_estado_and_more'),
        ('fiscal', '0001_initial'),
        ('ventas', '0007_pagopedido_banco_destino_pagopedido_id_datafono'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id_pago', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_operacion', models.CharField(choices=[('INGRESO', 'Ingreso'), ('EGRESO', 'Egreso')], max_length=20)),
                ('tipo_documento', models.CharField(choices=[('PEDIDO', 'Pedido de Venta'), ('FACTURA', 'Factura Fiscal'), ('NOTA_VENTA', 'Nota de Venta'), ('NOTA_CREDITO_VENTA', 'Nota de Crédito Venta'), ('CXP', 'Cuenta por Pagar'), ('COMPRA', 'Compra'), ('GASTO', 'Gasto'), ('NOMINA', 'Nómina'), ('IMPUESTO', 'Impuesto/Contribución'), ('AJUSTE', 'Ajuste Manual'), ('TRANSFERENCIA', 'Transferencia')], max_length=30)),
                ('id_documento', models.UUIDField(help_text='ID del documento específico (pedido, cxp, etc.)')),
                ('fecha_pago', models.DateTimeField()),
                ('monto', models.DecimalField(decimal_places=4, max_digits=18)),
                ('tasa', models.DecimalField(decimal_places=4, default=1, max_digits=18)),
                ('referencia', models.CharField(blank=True, max_length=100, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('banco_destino', models.ForeignKey(blank=True, help_text='Banco destino para métodos electrónicos/tarjeta.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_destino', to='finanzas.cuentabancariaempresa')),
                ('id_caja_fisica', models.ForeignKey(blank=True, help_text='Caja física donde se realizó el pago.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos', to='finanzas.cajafisica')),
                ('id_caja_virtual', models.ForeignKey(blank=True, help_text='Caja virtual que controla el ingreso/egreso financiero.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_virtuales', to='finanzas.caja')),
                ('id_contribucion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_genericos', to='fiscal.contribucionparafiscal')),
                ('id_cuenta_bancaria', models.ForeignKey(blank=True, help_text='Cuenta bancaria origen/destino.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos', to='finanzas.cuentabancariaempresa')),
                ('id_cxp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_genericos', to='cuentas_por_pagar.cuentaporpagar')),
                ('id_datafono', models.ForeignKey(blank=True, help_text='Datafono utilizado para pagos con tarjeta.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos', to='finanzas.datafono')),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='core.empresa')),
                ('id_metodo_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='finanzas.metodopago')),
                ('id_moneda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='finanzas.moneda')),
                ('id_pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_genericos', to='ventas.pedido')),
                ('id_transaccion_financiera', models.OneToOneField(blank=True, help_text='Transacción financiera generada automáticamente por este pago.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pago_asociado', to='finanzas.transaccionfinanciera')),
                ('id_usuario_registro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'db_table': 'finanzas_pago',
                'indexes': [models.Index(fields=['id_empresa', 'tipo_operacion', 'fecha_pago'], name='finanzas_pa_id_empr_0418aa_idx'), models.Index(fields=['tipo_documento', 'id_documento'], name='finanzas_pa_tipo_do_1c15ed_idx'), models.Index(fields=['id_metodo_pago', 'fecha_pago'], name='finanzas_pa_id_meto_dd7f4c_idx')],
            },
        ),
    ]
