# Generated by Django 5.2.4 on 2025-11-08 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0018_pago'),
        ('gastos', '0001_initial'),
        ('nomina', '0001_initial'),
        ('ventas', '0007_pagopedido_banco_destino_pagopedido_id_datafono'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='id_factura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_genericos', to='ventas.facturafiscal'),
        ),
        migrations.AddField(
            model_name='pago',
            name='id_gasto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_genericos', to='gastos.gasto'),
        ),
        migrations.AddField(
            model_name='pago',
            name='id_nomina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_genericos', to='nomina.nomina'),
        ),
        migrations.AddField(
            model_name='pago',
            name='id_nota_venta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_genericos', to='ventas.notaventa'),
        ),
        migrations.AddField(
            model_name='pago',
            name='id_reembolso_gasto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_genericos', to='gastos.reembolsogasto'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='tipo_documento',
            field=models.CharField(choices=[('PEDIDO', 'Pedido de Venta'), ('FACTURA', 'Factura Fiscal'), ('NOTA_VENTA', 'Nota de Venta'), ('NOTA_CREDITO_VENTA', 'Nota de Crédito Venta'), ('CXP', 'Cuenta por Pagar'), ('COMPRA', 'Compra'), ('GASTO', 'Gasto'), ('REEMBOLSO_GASTO', 'Reembolso de Gasto'), ('NOMINA', 'Nómina'), ('IMPUESTO', 'Impuesto/Contribución'), ('AJUSTE', 'Ajuste Manual'), ('TRANSFERENCIA', 'Transferencia')], max_length=30),
        ),
    ]
