# Generated by Django 5.2.4 on 2025-11-08 04:56

from django.db import migrations
from django.utils import timezone


def migrate_pagos_data(apps, schema_editor):
    """Migra datos de modelos de pago separados al modelo unificado Pago"""

    # Obtener modelos históricos
    PagoPedido = apps.get_model('ventas', 'PagoPedido')
    PagoCxP = apps.get_model('cuentas_por_pagar', 'PagoCxP')
    PagoContribucionParafiscal = apps.get_model('fiscal', 'PagoContribucionParafiscal')

    # Obtener modelo nuevo y relacionados
    Pago = apps.get_model('finanzas', 'Pago')
    MetodoPago = apps.get_model('finanzas', 'MetodoPago')
    Moneda = apps.get_model('finanzas', 'Moneda')

    # Obtener valores por defecto
    try:
        metodo_default = MetodoPago.objects.filter(activo=True).first()
        if not metodo_default:
            # Crear método por defecto si no existe
            metodo_default = MetodoPago.objects.create(
                nombre_metodo='EFECTIVO',
                tipo_metodo='EFECTIVO',
                activo=True,
                es_generico=True
            )
        moneda_default = Moneda.objects.filter(codigo_iso='VES').first() or Moneda.objects.first()
    except:
        # Si hay algún error, crear valores básicos
        metodo_default = MetodoPago.objects.create(
            nombre_metodo='EFECTIVO',
            tipo_metodo='EFECTIVO',
            activo=True,
            es_generico=True
        )
        moneda_default = Moneda.objects.filter(codigo_iso='VES').first() or Moneda.objects.create(
            codigo_iso='VES',
            nombre='Bolívar Venezolano',
            simbolo='Bs.',
            activo=True
        )

    # Migrar PagoPedido
    for pago_pedido in PagoPedido.objects.all():
        # Obtener empresa del pedido
        empresa = pago_pedido.id_pedido.id_empresa if hasattr(pago_pedido.id_pedido, 'id_empresa') else None

        # Buscar o crear método de pago
        metodo = MetodoPago.objects.filter(nombre_metodo=pago_pedido.metodo, activo=True).first()
        if not metodo:
            metodo = MetodoPago.objects.create(
                nombre_metodo=pago_pedido.metodo,
                tipo_metodo='OTRO',
                activo=True,
                es_generico=True
            )

        # Buscar moneda
        moneda = Moneda.objects.filter(codigo_iso=pago_pedido.moneda).first()
        if not moneda:
            moneda = moneda_default

        Pago.objects.create(
            id_empresa=empresa,
            tipo_operacion='INGRESO',
            tipo_documento='PEDIDO',
            id_documento=pago_pedido.id_pedido.id_pedido,
            fecha_pago=pago_pedido.fecha_pago,
            monto=pago_pedido.monto,
            id_moneda=moneda,
            tasa=pago_pedido.tasa,
            id_metodo_pago=metodo,
            referencia=pago_pedido.referencia,
            observaciones=pago_pedido.observacion,
            id_caja_fisica=pago_pedido.id_caja_fisica,
            id_caja_virtual=pago_pedido.id_caja_virtual,
            id_cuenta_bancaria=pago_pedido.id_cuenta_bancaria,
            id_datafono=pago_pedido.id_datafono,
            banco_destino=pago_pedido.banco_destino,
            id_pedido=pago_pedido.id_pedido,
        )

    # Migrar PagoCxP
    for pago_cxp in PagoCxP.objects.all():
        # Obtener empresa de la CxP
        empresa = pago_cxp.id_cxp.id_empresa if hasattr(pago_cxp.id_cxp, 'id_empresa') else None

        # Buscar o crear método de pago
        metodo = MetodoPago.objects.filter(nombre_metodo=pago_cxp.metodo_pago or 'EFECTIVO', activo=True).first()
        if not metodo:
            metodo = MetodoPago.objects.create(
                nombre_metodo=pago_cxp.metodo_pago or 'EFECTIVO',
                tipo_metodo='OTRO',
                activo=True,
                es_generico=True
            )

        Pago.objects.create(
            id_empresa=empresa,
            tipo_operacion='EGRESO',
            tipo_documento='CXP',
            id_documento=pago_cxp.id_cxp.id_cxp,
            fecha_pago=timezone.datetime.combine(pago_cxp.fecha_pago, timezone.datetime.min.time()),
            monto=pago_cxp.monto_pagado,
            id_moneda=moneda_default,
            tasa=1,
            id_metodo_pago=metodo,
            referencia=pago_cxp.referencia,
            observaciones=pago_cxp.observaciones,
            id_cxp=pago_cxp.id_cxp,
        )

    # Migrar PagoContribucionParafiscal
    for pago_impuesto in PagoContribucionParafiscal.objects.all():
        # Buscar o crear método de pago
        metodo = MetodoPago.objects.filter(nombre_metodo='TRANSFERENCIA', activo=True).first()
        if not metodo:
            metodo = MetodoPago.objects.create(
                nombre_metodo='TRANSFERENCIA',
                tipo_metodo='ELECTRONICO',
                activo=True,
                es_generico=True
            )

        Pago.objects.create(
            id_empresa=pago_impuesto.empresa,
            tipo_operacion='EGRESO',
            tipo_documento='IMPUESTO',
            id_documento=pago_impuesto.contribucion.id_contribucion,
            fecha_pago=timezone.datetime.combine(pago_impuesto.fecha_pago, timezone.datetime.min.time()) if pago_impuesto.fecha_pago else timezone.now(),
            monto=pago_impuesto.monto_pagado,
            id_moneda=moneda_default,
            tasa=1,
            id_metodo_pago=metodo,
            referencia=pago_impuesto.referencia_pago,
            id_contribucion=pago_impuesto.contribucion,
        )


def reverse_migrate_pagos_data(apps, schema_editor):
    """Reverse migration - elimina los pagos migrados"""
    Pago = apps.get_model('finanzas', 'Pago')
    # Solo eliminar pagos que tienen referencias a los modelos antiguos
    # Esto es una simplificación - en producción necesitarías una estrategia más sofisticada
    Pago.objects.filter(tipo_documento__in=['PEDIDO', 'CXP', 'IMPUESTO']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0019_pago_id_factura_pago_id_gasto_pago_id_nomina_and_more'),
        ('ventas', '0001_initial'),  # Dependencia de ventas
        ('cuentas_por_pagar', '0001_initial'),  # Dependencia de cuentas_por_pagar
        ('fiscal', '0001_initial'),  # Dependencia de fiscal
    ]

    operations = [
        migrations.RunPython(migrate_pagos_data, reverse_migrate_pagos_data),
    ]
