# Generated by Django 5.2.4 on 2025-11-09 19:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_empresa_id_moneda_pais_empresa_pais_codigo_iso_and_more'),
        ('finanzas', '0020_migrate_pagos_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cajafisica',
            name='fecha_ultimo_cierre',
        ),
        migrations.RemoveField(
            model_name='cajafisica',
            name='identificador_hardware',
        ),
        migrations.RemoveField(
            model_name='cajafisica',
            name='saldo_actual',
        ),
        migrations.RemoveField(
            model_name='cajafisica',
            name='saldo_inicial',
        ),
        migrations.RemoveField(
            model_name='cajafisica',
            name='ubicacion_fisica',
        ),
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id_dispositivo', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Nombre descriptivo del dispositivo', max_length=100)),
                ('tipo_dispositivo', models.CharField(choices=[('PC', 'Computadora Personal'), ('TABLET', 'Tablet'), ('MOVIL', 'Teléfono Móvil'), ('TERMINAL', 'Terminal de Pago'), ('OTRO', 'Otro')], default='PC', max_length=20)),
                ('identificador_unico', models.CharField(help_text='Identificador único del dispositivo (MAC, serial, UUID)', max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ultima_conexion', models.DateTimeField(blank=True, help_text='Última vez que el dispositivo se conectó al sistema', null=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dispositivos', to='core.empresa')),
                ('sucursal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispositivos', to='core.sucursal')),
            ],
            options={
                'verbose_name': 'Dispositivo',
                'verbose_name_plural': 'Dispositivos',
                'db_table': 'finanzas_dispositivo',
            },
        ),
        migrations.AddField(
            model_name='cajafisica',
            name='dispositivo',
            field=models.ForeignKey(blank=True, help_text='Dispositivo físico asociado a esta caja', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cajas_fisicas', to='finanzas.dispositivo'),
        ),
    ]
