# Generated by Django 5.2.4 on 2025-11-09 19:41

from django.db import migrations
import uuid


def create_sample_devices(apps, schema_editor):
    """Crear dispositivos de ejemplo y asignarlos a cajas físicas existentes"""
    Dispositivo = apps.get_model('finanzas', 'Dispositivo')
    CajaFisica = apps.get_model('finanzas', 'CajaFisica')
    
    # Crear dispositivo de ejemplo para este PC
    dispositivo_pc, created = Dispositivo.objects.get_or_create(
        identificador_unico='PC-OMNI-ERP-001',
        defaults={
            'nombre': 'PC Principal Omni ERP',
            'tipo_dispositivo': 'PC',
            'descripcion': 'Computadora principal del sistema Omni ERP',
            'activo': True,
        }
    )
    
    # Asignar este dispositivo a todas las cajas físicas existentes que no tengan dispositivo
    cajas_sin_dispositivo = CajaFisica.objects.filter(dispositivo__isnull=True)
    for caja in cajas_sin_dispositivo:
        caja.dispositivo = dispositivo_pc
        caja.save()


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0021_add_dispositivo_model_modify_caja_fisica'),
    ]

    operations = [
        migrations.RunPython(
            create_sample_devices,
            reverse_code=migrations.RunPython.noop
        ),
    ]
