# Generated by Django 5.2.4 on 2025-11-09 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0022_create_sample_devices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cajafisica',
            name='dispositivo',
            field=models.ForeignKey(help_text='Dispositivo físico asociado a esta caja', on_delete=django.db.models.deletion.CASCADE, related_name='cajas_fisicas', to='finanzas.dispositivo'),
        ),
    ]
