# Generated by Django 5.2.4 on 2025-11-09 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0023_make_dispositivo_required'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cajafisica',
            name='dispositivo',
        ),
        migrations.AddField(
            model_name='cajafisica',
            name='descripcion_dispositivo',
            field=models.TextField(blank=True, help_text='Descripción del dispositivo', null=True),
        ),
        migrations.AddField(
            model_name='cajafisica',
            name='identificador_dispositivo',
            field=models.CharField(default='', help_text='Identificador único del dispositivo (MAC, serial, UUID)', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='cajafisica',
            name='nombre_dispositivo',
            field=models.CharField(default='', help_text='Nombre descriptivo del dispositivo físico', max_length=100),
        ),
        migrations.AddField(
            model_name='cajafisica',
            name='tipo_dispositivo',
            field=models.CharField(choices=[('PC', 'Computadora Personal'), ('TABLET', 'Tablet'), ('MOVIL', 'Teléfono Móvil'), ('TERMINAL', 'Terminal de Pago'), ('OTRO', 'Otro')], default='PC', help_text='Tipo de dispositivo físico', max_length=20),
        ),
        migrations.AddField(
            model_name='cajafisica',
            name='ultima_conexion_dispositivo',
            field=models.DateTimeField(blank=True, help_text='Última vez que el dispositivo se conectó al sistema', null=True),
        ),
        migrations.DeleteModel(
            name='Dispositivo',
        ),
    ]
