# Generated by Django 5.2.4 on 2025-11-09 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0024_remove_cajafisica_dispositivo_and_more'),
    ]

    operations = [
        # Nota: Los datos de Dispositivo se perdieron al eliminar el modelo.
        # Esta migración marca la finalización de la refactorización.
        # Si había datos importantes en Dispositivo, deben ser restaurados manualmente.
    ]
