# Generated by Django 5.2.4 on 2025-11-09 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0025_migrate_dispositivo_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafono',
            name='id_caja_fisica',
            field=models.ForeignKey(blank=True, help_text='Caja física donde está conectado el datafono.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='datafonos', to='finanzas.cajafisica'),
        ),
    ]
