# Generated by Django 5.2.4 on 2025-11-09 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0026_datafono_id_caja_fisica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafono',
            name='id_caja',
            field=models.ForeignKey(blank=True, help_text='Caja principal a la que está asociado el datafono.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='datafonos_caja_virtual', to='finanzas.caja'),
        ),
    ]
