# Generated by Django 5.2.4 on 2025-11-09 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0027_fix_datafono_related_names'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datafono',
            name='id_caja',
        ),
    ]
