# Generated by Django 5.2.4 on 2025-11-09 22:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_empresa_id_moneda_pais_empresa_pais_codigo_iso_and_more'),
        ('finanzas', '0028_remove_datafono_id_caja_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cajametodopagooverride',
            options={'verbose_name': 'Override Método de Pago', 'verbose_name_plural': 'Overrides Métodos de Pago'},
        ),
        migrations.AlterUniqueTogether(
            name='cajametodopagooverride',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='cajametodopagooverride',
            name='caja_fisica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metodo_pago_overrides', to='finanzas.cajafisica'),
        ),
        migrations.AlterField(
            model_name='cajametodopagooverride',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metodo_pago_overrides', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cajametodopagooverride',
            name='deshabilitado',
            field=models.BooleanField(default=True, help_text='Si es True, este método de pago queda deshabilitado para esta caja/sucursal'),
        ),
        migrations.AlterField(
            model_name='cajametodopagooverride',
            name='metodo_pago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caja_overrides', to='finanzas.metodopago'),
        ),
        migrations.AlterField(
            model_name='cajametodopagooverride',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metodo_pago_overrides', to='core.sucursal'),
        ),
        migrations.AlterUniqueTogether(
            name='cajametodopagooverride',
            unique_together={('caja_fisica', 'metodo_pago', 'sucursal')},
        ),
    ]
