# Generated by Django 5.2.4 on 2025-11-10 00:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_empresa_id_moneda_pais_empresa_pais_codigo_iso_and_more'),
        ('finanzas', '0029_alter_cajametodopagooverride_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SesionCajaFisica',
            fields=[
                ('id_sesion', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('ABIERTA', 'Abierta'), ('CERRADA', 'Cerrada'), ('PAUSADA', 'Pausada')], default='ABIERTA', max_length=20)),
                ('fecha_apertura', models.DateTimeField(auto_now_add=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('fecha_ultima_actividad', models.DateTimeField(auto_now=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('saldo_inicial', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('caja_fisica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='finanzas.cajafisica')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones_caja_fisica', to='core.empresa')),
                ('sucursal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sesiones_caja_fisica', to='core.sucursal')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones_caja_fisica', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sesión de Caja Física',
                'verbose_name_plural': 'Sesiones de Caja Física',
                'db_table': 'finanzas_sesion_caja_fisica',
                'ordering': ['-fecha_apertura'],
                'unique_together': {('caja_fisica', 'estado')},
            },
        ),
        migrations.DeleteModel(
            name='SesionCaja',
        ),
    ]
