# Generated by Django 5.2.4 on 2025-11-10 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0030_sesioncajafisica_delete_sesioncaja'),
    ]

    operations = [
        migrations.AddField(
            model_name='cajafisicausuario',
            name='puede_abrir_sesion',
            field=models.BooleanField(default=True, help_text='Si es True, el usuario puede abrir sesiones en esta caja física.'),
        ),
        migrations.AddField(
            model_name='cajafisicausuario',
            name='puede_cerrar_sesion',
            field=models.BooleanField(default=True, help_text='Si es True, el usuario puede cerrar sesiones en esta caja física.'),
        ),
    ]
