# Generated by Django 5.2.4 on 2025-11-10 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0031_add_permisos_caja_fisica_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafono',
            name='metodos_pago',
            field=models.ManyToManyField(blank=True, help_text='Métodos de pago permitidos para este datafono.', related_name='datafonos', to='finanzas.metodopago'),
        ),
        migrations.AddField(
            model_name='datafono',
            name='monedas',
            field=models.ManyToManyField(blank=True, help_text='Monedas aceptadas por este datafono.', related_name='datafonos', to='finanzas.moneda'),
        ),
    ]
