# Generated by Django 5.2.4 on 2025-11-11 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0032_add_datafono_metodos_monedas'),
    ]

    operations = [
        migrations.AddField(
            model_name='caja',
            name='saldo_actual',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
        ),
    ]
