# Generated by Django 5.2.4 on 2026-04-30 06:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_fix_sesion_caja_unique_constraint'),
        ('finanzas', '0033_add_saldo_actual_to_caja'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sesioncajafisica',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='sesioncajafisica',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'ABIERTA')), fields=('caja_fisica',), name='unique_sesion_abierta_por_caja'),
        ),
    ]
