# Generated by Django 5.2.15 on 2026-06-11 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finanzas", "0037_rls_piloto_finanzas"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movimientocajabanco",
            name="tipo_movimiento",
            field=models.CharField(
                choices=[
                    ("INGRESO", "Ingreso"),
                    ("EGRESO", "Egreso"),
                    ("TRANSFERENCIA_ENTRADA", "Transferencia Entrada"),
                    ("TRANSFERENCIA_SALIDA", "Transferencia Salida"),
                    ("AJUSTE_POSITIVO", "Ajuste Positivo"),
                    ("AJUSTE_NEGATIVO", "Ajuste Negativo"),
                    ("CIERRE", "Cierre"),
                ],
                max_length=50,
            ),
        ),
    ]
