# Generated by Django 5.2.15 on 2026-06-12 02:40
# FIX modelado: CajaVirtualAuto.caja_fisica apuntaba a Caja (virtual) en vez de
# CajaFisica. Antes de re-apuntar el FK se anulan las referencias huérfanas
# (ids que no corresponden a una CajaFisica). Reversible: el reverse re-apunta
# el FK a Caja y la limpieza de datos no se puede deshacer (noop), lo cual es
# seguro porque esos valores eran inválidos bajo el modelado correcto.

import django.db.models.deletion
from django.db import migrations, models


def _anular_referencias_invalidas(apps, schema_editor):
    CajaVirtualAuto = apps.get_model("finanzas", "CajaVirtualAuto")
    CajaFisica = apps.get_model("finanzas", "CajaFisica")
    ids_validos = CajaFisica.objects.values_list("id_caja_fisica", flat=True)
    CajaVirtualAuto.objects.exclude(caja_fisica_id__isnull=True).exclude(
        caja_fisica_id__in=ids_validos
    ).update(caja_fisica=None)


class Migration(migrations.Migration):

    dependencies = [
        ("finanzas", "0038_alter_movimientocajabanco_tipo_movimiento"),
    ]

    operations = [
        migrations.RunPython(_anular_referencias_invalidas, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="cajavirtualauto",
            name="caja_fisica",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cajas_virtuales_auto",
                to="finanzas.cajafisica",
            ),
        ),
    ]
