# Generated by Django 5.2.15 on 2026-06-12 04:49

import apps.core.uuid
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_claveidempotencia_usuario_ttl"),
        ("cuentas_por_cobrar", "0002_cuentaporcobrar_cliente_externo_id_and_more"),
        ("cuentas_por_pagar", "0005_alter_abonocxp_id_abono_cxp_and_more"),
        ("finanzas", "0039_alter_cajavirtualauto_caja_fisica"),
        ("proveedores", "0005_alter_contactoproveedor_id_contacto_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PagoTercero",
            fields=[
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Fecha y hora de creación del registro.",
                        verbose_name="Fecha de Creación",
                    ),
                ),
                (
                    "fecha_actualizacion",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Fecha y hora de la última modificación del registro.",
                        verbose_name="Fecha de Actualización",
                    ),
                ),
                (
                    "activo",
                    models.BooleanField(
                        default=True,
                        help_text="Indica si el registro está activo (False = borrado lógico).",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "referencia_externa",
                    models.CharField(
                        blank=True,
                        help_text="Identificador del registro en el sistema externo de origen.",
                        max_length=100,
                        null=True,
                        verbose_name="Referencia externa",
                    ),
                ),
                (
                    "documento_json",
                    models.JSONField(
                        blank=True,
                        help_text="Payload raw del documento externo (para auditoría/reprocesamiento).",
                        null=True,
                        verbose_name="Documento JSON",
                    ),
                ),
                (
                    "id_pago_tercero",
                    models.UUIDField(
                        default=apps.core.uuid.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "monto",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Monto del cobro recibido en la cuenta del tercero.",
                        max_digits=18,
                    ),
                ),
                (
                    "comision",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Comisión que cobra el proveedor por el reintegro (opcional). La CxC del reintegro se emite por monto − comisión.",
                        max_digits=18,
                        null=True,
                    ),
                ),
                (
                    "referencia_zelle",
                    models.CharField(
                        help_text="Referencia/confirmación de la transferencia Zelle.",
                        max_length=100,
                    ),
                ),
                (
                    "fecha",
                    models.DateField(
                        help_text="Fecha del cobro en la cuenta del tercero."
                    ),
                ),
                ("concepto", models.TextField(blank=True, default="")),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("abonado", "Abonado a CxP"),
                            ("reintegro_pendiente", "Reintegro pendiente"),
                            ("reintegrado", "Reintegrado"),
                            ("anulado", "Anulado"),
                        ],
                        db_index=True,
                        default="pendiente",
                        max_length=20,
                    ),
                ),
                (
                    "id_abono_cxp",
                    models.ForeignKey(
                        blank=True,
                        help_text="Abono CxP generado por la acción 'abonar'.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pagos_terceros",
                        to="cuentas_por_pagar.abonocxp",
                    ),
                ),
                (
                    "id_cxc_reintegro",
                    models.ForeignKey(
                        blank=True,
                        help_text="CxC contra el proveedor generada por 'solicitar_reintegro'.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reintegros_pago_tercero",
                        to="cuentas_por_cobrar.cuentaporcobrar",
                    ),
                ),
                (
                    "id_empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pagos_terceros",
                        to="core.empresa",
                    ),
                ),
                (
                    "id_moneda",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pagos_terceros",
                        to="finanzas.moneda",
                    ),
                ),
                (
                    "id_proveedor",
                    models.ForeignKey(
                        blank=True,
                        help_text="Proveedor por cuya cuenta entró el cobro. Opcional al crear (cobro originado en caja); requerido para abonar o reintegrar.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pagos_terceros",
                        to="proveedores.proveedor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pago de Tercero",
                "verbose_name_plural": "Pagos de Terceros",
                "db_table": "finanzas_pago_tercero",
                "ordering": ["-fecha", "-fecha_creacion"],
                "indexes": [
                    models.Index(
                        fields=["id_empresa", "estado"],
                        name="finanzas_pa_id_empr_b70bd7_idx",
                    ),
                    models.Index(
                        fields=["id_empresa", "id_proveedor"],
                        name="finanzas_pa_id_empr_cdbf58_idx",
                    ),
                ],
            },
        ),
    ]
