# Generated by Django 5.2.4 on 2025-08-02 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('finanzas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoInternoFondo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia_externa', models.CharField(blank=True, max_length=100, null=True)),
                ('documento_json', models.JSONField(blank=True, null=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=18)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('caja_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_entrada', to='finanzas.caja')),
                ('caja_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_salida', to='finanzas.caja')),
            ],
        ),
        migrations.CreateModel(
            name='OperacionCambioDivisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia_externa', models.CharField(blank=True, max_length=100, null=True)),
                ('documento_json', models.JSONField(blank=True, null=True)),
                ('numero_operacion', models.CharField(max_length=50, unique=True)),
                ('fecha_operacion', models.DateTimeField()),
                ('tipo_operacion', models.CharField(choices=[('COMPRA', 'Compra'), ('VENTA', 'Venta')], max_length=20)),
                ('monto_origen', models.DecimalField(decimal_places=4, max_digits=18)),
                ('tasa_cambio', models.DecimalField(decimal_places=6, max_digits=18)),
                ('monto_destino', models.DecimalField(decimal_places=4, max_digits=18)),
                ('comision', models.DecimalField(decimal_places=4, default=0.0, max_digits=18)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operaciones_cambio', to='core.empresa')),
                ('moneda_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operaciones_destino', to='finanzas.moneda')),
                ('moneda_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operaciones_origen', to='finanzas.moneda')),
            ],
            options={
                'verbose_name': 'Operación de Cambio de Divisa',
                'verbose_name_plural': 'Operaciones de Cambio de Divisa',
                'db_table': 'tesoreria_operacion_cambio_divisa',
            },
        ),
    ]
