# Generated by Django 5.2.4 on 2025-08-05 03:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0004_transaccionfinanciera_id_caja_and_more'),
        ('proveedores', '0001_initial'),
        ('tesoreria', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientointernofondo',
            name='id_banco_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_banco_destino', to='finanzas.cuentabancariaempresa'),
        ),
        migrations.AddField(
            model_name='movimientointernofondo',
            name='id_banco_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_banco_origen', to='finanzas.cuentabancariaempresa'),
        ),
        migrations.AddField(
            model_name='movimientointernofondo',
            name='id_moneda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_internos', to='finanzas.moneda'),
        ),
        migrations.AddField(
            model_name='movimientointernofondo',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_internos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='operacioncambiodivisa',
            name='banco_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operaciones_cambio_banco_destino', to='finanzas.cuentabancariaempresa'),
        ),
        migrations.AddField(
            model_name='operacioncambiodivisa',
            name='banco_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operaciones_cambio_banco_origen', to='finanzas.cuentabancariaempresa'),
        ),
        migrations.AddField(
            model_name='operacioncambiodivisa',
            name='caja_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operaciones_cambio_destino', to='finanzas.caja'),
        ),
        migrations.AddField(
            model_name='operacioncambiodivisa',
            name='caja_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operaciones_cambio_origen', to='finanzas.caja'),
        ),
        migrations.AddField(
            model_name='operacioncambiodivisa',
            name='casa_de_cambio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operaciones_cambio', to='proveedores.proveedor'),
        ),
        migrations.AddField(
            model_name='operacioncambiodivisa',
            name='metodo_pago_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operaciones_cambio_metodo_destino', to='finanzas.metodopago'),
        ),
        migrations.AddField(
            model_name='operacioncambiodivisa',
            name='metodo_pago_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operaciones_cambio_metodo_origen', to='finanzas.metodopago'),
        ),
        migrations.AddField(
            model_name='operacioncambiodivisa',
            name='numero_documento_gasto',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='operacioncambiodivisa',
            name='referencia_transaccion_destino',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='operacioncambiodivisa',
            name='referencia_transaccion_origen',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='operacioncambiodivisa',
            name='tipo_documento_gasto',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
