# Generated by Django 5.2.4 on 2026-05-19 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_fix_unique_numeros_documento'),
        ('tesoreria', '0002_movimientointernofondo_id_banco_destino_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operacioncambiodivisa',
            name='numero_operacion',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='operacioncambiodivisa',
            unique_together={('empresa', 'numero_operacion')},
        ),
    ]
