# Generated by Django 5.2.4 on 2026-06-02 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tesoreria", "0004_movimiento_bancario_conciliacion"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="movimientobancario",
            new_name="tesoreria_m_id_empr_5161fd_idx",
            old_name="tesoreria_mov_empresa_estado_idx",
        ),
        migrations.RenameIndex(
            model_name="movimientobancario",
            new_name="tesoreria_m_id_cuen_56a833_idx",
            old_name="tesoreria_mov_cuenta_fecha_idx",
        ),
    ]
