# Generated by Django 5.2.15 on 2026-06-07 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_empresa_localizacion_legal_activa_and_more'),
        ('crm', '0008_alter_cliente_dias_credito_alter_cliente_id_cliente_and_more'),
        ('cuentas_por_cobrar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentaporcobrar',
            name='cliente_externo_id',
            field=models.CharField(blank=True, default='', help_text='ID del deudor en la fuente externa (p. ej. partner_id de Odoo). Se usa cuando no hay FK a crm.Cliente.', max_length=100),
        ),
        migrations.AddField(
            model_name='cuentaporcobrar',
            name='cliente_externo_nombre',
            field=models.CharField(blank=True, default='', help_text='Nombre del deudor denormalizado (fuente externa sin crm.Cliente).', max_length=255),
        ),
        migrations.AlterField(
            model_name='cuentaporcobrar',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cuentas_por_cobrar', to='crm.cliente'),
        ),
        migrations.AddConstraint(
            model_name='cuentaporcobrar',
            constraint=models.CheckConstraint(condition=models.Q(('cliente__isnull', False), models.Q(('cliente_externo_id', ''), _negated=True), _connector='OR'), name='cxc_cliente_o_externo_requerido'),
        ),
    ]
