# Generated by Django 5.2.4 on 2025-08-02 20:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_initial'),
        ('rrhh', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptoNomina',
            fields=[
                ('id_concepto_nomina', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo_concepto', models.CharField(max_length=20, unique=True)),
                ('nombre_concepto', models.CharField(max_length=100)),
                ('tipo_concepto', models.CharField(choices=[('DEVENGADO', 'Devengado'), ('DEDUCCION', 'Deducción'), ('APORTE_PATRONAL', 'Aporte Patronal')], max_length=15)),
                ('categoria', models.CharField(choices=[('SUELDO_BASE', 'Sueldo Base'), ('HORAS_EXTRAS', 'Horas Extras'), ('COMISION', 'Comisión'), ('BONO', 'Bono'), ('VACACIONES', 'Vacaciones'), ('PRESTACIONES', 'Prestaciones'), ('SEGURO_SOCIAL', 'Seguro Social'), ('IMPUESTO_RENTA', 'Impuesto sobre la Renta'), ('OTROS', 'Otros')], max_length=20)),
                ('formula_calculo', models.TextField(blank=True, null=True)),
                ('es_fijo', models.BooleanField(default=False)),
                ('monto_fijo', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('es_porcentaje', models.BooleanField(default=False)),
                ('porcentaje', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conceptos_nomina', to='core.empresa')),
            ],
            options={
                'verbose_name': 'Concepto de Nómina',
                'verbose_name_plural': 'Conceptos de Nómina',
                'db_table': 'nomina_concepto_nomina',
            },
        ),
        migrations.CreateModel(
            name='Nomina',
            fields=[
                ('id_nomina', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sueldo_base', models.DecimalField(decimal_places=4, max_digits=18)),
                ('total_devengado', models.DecimalField(decimal_places=4, default=0.0, max_digits=18)),
                ('total_deducciones', models.DecimalField(decimal_places=4, default=0.0, max_digits=18)),
                ('total_neto', models.DecimalField(decimal_places=4, default=0.0, max_digits=18)),
                ('dias_trabajados', models.IntegerField(default=0)),
                ('horas_trabajadas', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('horas_extras', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('estado', models.CharField(choices=[('CALCULADA', 'Calculada'), ('APROBADA', 'Aprobada'), ('PAGADA', 'Pagada')], default='CALCULADA', max_length=15)),
                ('fecha_calculo', models.DateTimeField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('id_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nominas', to='rrhh.empleado')),
            ],
            options={
                'verbose_name': 'Nómina',
                'verbose_name_plural': 'Nóminas',
                'db_table': 'nomina_nomina',
            },
        ),
        migrations.CreateModel(
            name='DetalleNomina',
            fields=[
                ('id_detalle_nomina', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cantidad', models.DecimalField(decimal_places=4, default=1.0, max_digits=18)),
                ('valor_unitario', models.DecimalField(decimal_places=4, max_digits=18)),
                ('valor_total', models.DecimalField(decimal_places=4, max_digits=18)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('id_concepto_nomina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_nomina', to='nomina.conceptonomina')),
                ('id_nomina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='nomina.nomina')),
            ],
            options={
                'verbose_name': 'Detalle de Nómina',
                'verbose_name_plural': 'Detalles de Nómina',
                'db_table': 'nomina_detalle_nomina',
            },
        ),
        migrations.CreateModel(
            name='PeriodoNomina',
            fields=[
                ('id_periodo_nomina', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_periodo', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('fecha_pago', models.DateField()),
                ('tipo_periodo', models.CharField(choices=[('SEMANAL', 'Semanal'), ('QUINCENAL', 'Quincenal'), ('MENSUAL', 'Mensual'), ('ANUAL', 'Anual')], max_length=15)),
                ('estado', models.CharField(choices=[('ABIERTO', 'Abierto'), ('PROCESANDO', 'Procesando'), ('CERRADO', 'Cerrado'), ('PAGADO', 'Pagado')], default='ABIERTO', max_length=15)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodos_nomina', to='core.empresa')),
            ],
            options={
                'verbose_name': 'Período de Nómina',
                'verbose_name_plural': 'Períodos de Nómina',
                'db_table': 'nomina_periodo_nomina',
            },
        ),
        migrations.CreateModel(
            name='ProcesoNomina',
            fields=[
                ('id_proceso_nomina', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_proceso', models.CharField(max_length=50, unique=True)),
                ('fecha_proceso', models.DateTimeField()),
                ('total_empleados', models.IntegerField(default=0)),
                ('total_devengado', models.DecimalField(decimal_places=4, default=0.0, max_digits=18)),
                ('total_deducciones', models.DecimalField(decimal_places=4, default=0.0, max_digits=18)),
                ('total_neto', models.DecimalField(decimal_places=4, default=0.0, max_digits=18)),
                ('estado', models.CharField(choices=[('EN_PROCESO', 'En Proceso'), ('COMPLETADO', 'Completado'), ('APROBADO', 'Aprobado'), ('CANCELADO', 'Cancelado')], default='EN_PROCESO', max_length=15)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procesos_nomina', to='core.empresa')),
                ('id_periodo_nomina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procesos', to='nomina.periodonomina')),
            ],
            options={
                'verbose_name': 'Proceso de Nómina',
                'verbose_name_plural': 'Procesos de Nómina',
                'db_table': 'nomina_proceso_nomina',
            },
        ),
        migrations.AddField(
            model_name='nomina',
            name='id_proceso_nomina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nominas', to='nomina.procesonomina'),
        ),
        migrations.CreateModel(
            name='ProcesoNominaExtrasalarial',
            fields=[
                ('id_proceso_extrasalarial', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_proceso', models.CharField(max_length=50, unique=True)),
                ('tipo_proceso', models.CharField(choices=[('AGUINALDO', 'Aguinaldo'), ('VACACIONES', 'Vacaciones'), ('PRESTACIONES', 'Prestaciones'), ('LIQUIDACION', 'Liquidación'), ('BONO_ESPECIAL', 'Bono Especial')], max_length=20)),
                ('fecha_proceso', models.DateTimeField()),
                ('fecha_corte', models.DateField()),
                ('total_empleados', models.IntegerField(default=0)),
                ('total_monto', models.DecimalField(decimal_places=4, default=0.0, max_digits=18)),
                ('estado', models.CharField(choices=[('EN_PROCESO', 'En Proceso'), ('COMPLETADO', 'Completado'), ('APROBADO', 'Aprobado'), ('PAGADO', 'Pagado'), ('CANCELADO', 'Cancelado')], default='EN_PROCESO', max_length=15)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procesos_extrasalarial', to='core.empresa')),
            ],
            options={
                'verbose_name': 'Proceso de Nómina Extrasalarial',
                'verbose_name_plural': 'Procesos de Nómina Extrasalarial',
                'db_table': 'nomina_proceso_nomina_extrasalarial',
            },
        ),
        migrations.CreateModel(
            name='NominaExtrasalarial',
            fields=[
                ('id_nomina_extrasalarial', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('periodo_inicio', models.DateField()),
                ('periodo_fin', models.DateField()),
                ('salario_promedio', models.DecimalField(decimal_places=4, default=0.0, max_digits=18)),
                ('dias_laborados', models.IntegerField(default=0)),
                ('monto_calculado', models.DecimalField(decimal_places=4, max_digits=18)),
                ('deducciones', models.DecimalField(decimal_places=4, default=0.0, max_digits=18)),
                ('monto_neto', models.DecimalField(decimal_places=4, max_digits=18)),
                ('estado', models.CharField(choices=[('CALCULADA', 'Calculada'), ('APROBADA', 'Aprobada'), ('PAGADA', 'Pagada')], default='CALCULADA', max_length=15)),
                ('fecha_calculo', models.DateTimeField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('id_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nominas_extrasalarial', to='rrhh.empleado')),
                ('id_proceso_extrasalarial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nominas_extrasalarial', to='nomina.procesonominaextrasalarial')),
            ],
            options={
                'verbose_name': 'Nómina Extrasalarial',
                'verbose_name_plural': 'Nóminas Extrasalariales',
                'db_table': 'nomina_nomina_extrasalarial',
            },
        ),
    ]
