# Generated by Django 5.2.4 on 2026-05-11 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_usuarios_es_superusuario_omni'),
        ('nomina', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conceptonomina',
            name='codigo_concepto',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='procesonomina',
            name='numero_proceso',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='procesonominaextrasalarial',
            name='numero_proceso',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='conceptonomina',
            unique_together={('id_empresa', 'codigo_concepto')},
        ),
        migrations.AlterUniqueTogether(
            name='procesonomina',
            unique_together={('id_empresa', 'numero_proceso')},
        ),
        migrations.AlterUniqueTogether(
            name='procesonominaextrasalarial',
            unique_together={('id_empresa', 'numero_proceso')},
        ),
    ]
