# Generated by Django 5.2.4 on 2026-06-02 03:16

import apps.core.uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nomina", "0002_alter_conceptonomina_codigo_concepto_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conceptonomina",
            name="id_concepto_nomina",
            field=models.UUIDField(
                default=apps.core.uuid.uuid7,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="detallenomina",
            name="id_detalle_nomina",
            field=models.UUIDField(
                default=apps.core.uuid.uuid7,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="nomina",
            name="id_nomina",
            field=models.UUIDField(
                default=apps.core.uuid.uuid7,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="nominaextrasalarial",
            name="id_nomina_extrasalarial",
            field=models.UUIDField(
                default=apps.core.uuid.uuid7,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="periodonomina",
            name="id_periodo_nomina",
            field=models.UUIDField(
                default=apps.core.uuid.uuid7,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="procesonomina",
            name="id_proceso_nomina",
            field=models.UUIDField(
                default=apps.core.uuid.uuid7,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="procesonominaextrasalarial",
            name="id_proceso_extrasalarial",
            field=models.UUIDField(
                default=apps.core.uuid.uuid7,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
