# Generated by Django 5.2.4 on 2026-06-02 03:16

import apps.core.uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personalizacion", "0002_ctf002_dsl_runtime_models"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="entidadinstancia",
            new_name="personaliza_id_empr_3b51c3_idx",
            old_name="idx_ent_inst_emp_nombre",
        ),
        migrations.RenameIndex(
            model_name="estadopersonalizado",
            new_name="personaliza_id_empr_c18708_idx",
            old_name="idx_estado_pers_emp_modelo",
        ),
        migrations.RenameIndex(
            model_name="vistapersonalizada",
            new_name="personaliza_id_empr_7c24a1_idx",
            old_name="idx_vista_pers_emp_entidad",
        ),
        migrations.AlterField(
            model_name="personalizacionconfig",
            name="id_config",
            field=models.UUIDField(
                default=apps.core.uuid.uuid7,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
