# Generated by Django 5.2.4 on 2025-11-09 18:49

import apps.crm.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='rif',
            field=models.CharField(max_length=20, unique=True, validators=[apps.crm.models.validar_rif]),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[apps.crm.models.validar_telefono]),
        ),
    ]
