# Generated by Django 5.2.4 on 2026-05-11 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_alter_cliente_rif_alter_cliente_telefono'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['razon_social']},
        ),
    ]
