# Generated by Django 5.2.4 on 2026-05-15 02:48

import apps.crm.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_base_model_empresa_sucursal_departamento'),
        ('crm', '0004_base_model_rif_per_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='id_empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='core.empresa'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='rif',
            field=models.CharField(max_length=20, validators=[apps.crm.models.validar_rif]),
        ),
    ]
