# Generated by Django 5.2.4 on 2026-06-02 03:16

import apps.core.uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0007_cliente_contacto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="dias_credito",
            field=models.PositiveSmallIntegerField(
                default=0, help_text="Días de plazo de crédito."
            ),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="id_cliente",
            field=models.UUIDField(
                default=apps.core.uuid.uuid7,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="limite_credito",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Límite de crédito aprobado. 0 = sin límite definido (requiere tipo_cliente=CREDITO).",
                max_digits=18,
            ),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="tipo_cliente",
            field=models.CharField(
                choices=[("CONTADO", "Contado"), ("CREDITO", "Crédito")],
                default="CONTADO",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="contactocliente",
            name="id_contacto",
            field=models.UUIDField(
                default=apps.core.uuid.uuid7,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="direccioncliente",
            name="id_direccion",
            field=models.UUIDField(
                default=apps.core.uuid.uuid7,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
