# Generated by Django 5.2.4 on 2025-08-02 20:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('almacenes', '0002_initial'),
        ('core', '0002_initial'),
        ('crm', '0001_initial'),
        ('finanzas', '0001_initial'),
        ('fiscal', '0001_initial'),
        ('proveedores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProducto',
            fields=[
                ('id_categoria_producto', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('referencia_externa', models.CharField(blank=True, max_length=100, null=True)),
                ('documento_json', models.JSONField(blank=True, null=True)),
                ('nombre_categoria', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('id_categoria_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.categoriaproducto')),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id_unidad_medida', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('referencia_externa', models.CharField(blank=True, max_length=100, null=True)),
                ('documento_json', models.JSONField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=50)),
                ('abreviatura', models.CharField(max_length=10, unique=True)),
                ('tipo', models.CharField(choices=[('CANTIDAD', 'Cantidad'), ('PESO', 'Peso'), ('VOLUMEN', 'Volumen'), ('LONGITUD', 'Longitud')], max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('referencia_externa', models.CharField(blank=True, max_length=100, null=True)),
                ('documento_json', models.JSONField(blank=True, null=True)),
                ('tipo_operacion', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_cierre_estimada', models.DateField(blank=True, null=True)),
                ('nombre_producto', models.CharField(max_length=255)),
                ('sku', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo_producto', models.CharField(choices=[('PRODUCTO_FISICO', 'Producto Físico'), ('SERVICIO', 'Servicio'), ('KIT', 'Kit'), ('COMBO', 'Combo')], default='PRODUCTO_FISICO', max_length=50)),
                ('maneja_lotes', models.BooleanField(default=False)),
                ('maneja_seriales', models.BooleanField(default=False)),
                ('costo_promedio', models.DecimalField(decimal_places=4, default=0.0, max_digits=18)),
                ('precio_venta_sugerido', models.DecimalField(decimal_places=4, default=0.0, max_digits=18)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.categoriaproducto')),
                ('id_configuracion_impuesto_compra_default', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='producto_impuesto_compra', to='fiscal.configuracionimpuesto')),
                ('id_configuracion_impuesto_venta_default', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='producto_impuesto_venta', to='fiscal.configuracionimpuesto')),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
                ('id_moneda_precio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finanzas.moneda')),
                ('id_unidad_medida_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.unidadmedida')),
            ],
        ),
        migrations.CreateModel(
            name='VarianteProducto',
            fields=[
                ('id_variante', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo_variante', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('atributos_json', models.JSONField(default=dict)),
                ('sku', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variantes', to='inventario.producto')),
            ],
            options={
                'verbose_name': 'Variante de Producto',
                'verbose_name_plural': 'Variantes de Producto',
                'db_table': 'inventario_variante_producto',
            },
        ),
        migrations.CreateModel(
            name='StockConsignacionProveedor',
            fields=[
                ('id_stock_consignacion', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cantidad_recibida', models.DecimalField(decimal_places=4, max_digits=18)),
                ('cantidad_consumida', models.DecimalField(decimal_places=4, default=0.0, max_digits=18)),
                ('cantidad_devuelta', models.DecimalField(decimal_places=4, default=0.0, max_digits=18)),
                ('fecha_recepcion', models.DateField()),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('costo_unitario_consignacion', models.DecimalField(decimal_places=4, max_digits=18)),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('VENCIDA', 'Vencida'), ('CERRADA', 'Cerrada'), ('CANCELADA', 'Cancelada')], default='ACTIVA', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_consignacion_proveedores', to='core.empresa')),
                ('id_moneda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_consignacion_proveedores', to='finanzas.moneda')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_consignacion_proveedores', to='inventario.producto')),
                ('id_proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_consignacion', to='proveedores.proveedor')),
                ('id_variante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_consignacion_proveedores', to='inventario.varianteproducto')),
            ],
            options={
                'verbose_name': 'Stock en Consignación de Proveedor',
                'verbose_name_plural': 'Stocks en Consignación de Proveedores',
                'db_table': 'inventario_stock_consignacion_proveedor',
            },
        ),
        migrations.CreateModel(
            name='StockConsignacionCliente',
            fields=[
                ('id_stock_consignacion', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cantidad_consignada', models.DecimalField(decimal_places=4, max_digits=18)),
                ('cantidad_vendida', models.DecimalField(decimal_places=4, default=0.0, max_digits=18)),
                ('cantidad_devuelta', models.DecimalField(decimal_places=4, default=0.0, max_digits=18)),
                ('fecha_consignacion', models.DateField()),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('precio_unitario_consignacion', models.DecimalField(decimal_places=4, max_digits=18)),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('VENCIDA', 'Vencida'), ('CERRADA', 'Cerrada'), ('CANCELADA', 'Cancelada')], default='ACTIVA', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_consignacion', to='crm.cliente')),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_consignacion_clientes', to='core.empresa')),
                ('id_moneda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_consignacion_clientes', to='finanzas.moneda')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_consignacion_clientes', to='inventario.producto')),
                ('id_variante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_consignacion_clientes', to='inventario.varianteproducto')),
            ],
            options={
                'verbose_name': 'Stock en Consignación a Cliente',
                'verbose_name_plural': 'Stocks en Consignación a Clientes',
                'db_table': 'inventario_stock_consignacion_cliente',
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id_movimiento_inventario', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_hora_movimiento', models.DateTimeField()),
                ('tipo_movimiento', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida'), ('TRANSFERENCIA', 'Transferencia'), ('AJUSTE', 'Ajuste'), ('CONSUMO_PRODUCCION', 'Consumo Producción'), ('RECEPCION_COMPRA', 'Recepción Compra'), ('DESPACHO_VENTA', 'Despacho Venta')], max_length=50)),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=18)),
                ('costo_unitario_movimiento', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('id_documento_origen', models.UUIDField(blank=True, null=True)),
                ('nombre_modelo_origen', models.CharField(blank=True, max_length=100, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_almacen_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_destino', to='almacenes.almacen')),
                ('id_almacen_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_origen', to='almacenes.almacen')),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_inventario', to='core.empresa')),
                ('id_usuario_registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_inventario_registrados', to=settings.AUTH_USER_MODEL)),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='inventario.producto')),
                ('id_variante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='inventario.varianteproducto')),
            ],
            options={
                'verbose_name': 'Movimiento de Inventario',
                'verbose_name_plural': 'Movimientos de Inventario',
                'db_table': 'inventario_movimiento_inventario',
            },
        ),
        migrations.CreateModel(
            name='ConversionUnidadMedida',
            fields=[
                ('id_conversion', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('factor_conversion', models.DecimalField(decimal_places=8, max_digits=18)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversiones_unidad', to='core.empresa')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversiones_unidad', to='inventario.producto')),
                ('id_unidad_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversiones_destino', to='inventario.unidadmedida')),
                ('id_unidad_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversiones_origen', to='inventario.unidadmedida')),
            ],
            options={
                'verbose_name': 'Conversión de Unidad de Medida',
                'verbose_name_plural': 'Conversiones de Unidades de Medida',
                'db_table': 'inventario_conversion_unidad_medida',
                'unique_together': {('id_producto', 'id_unidad_origen', 'id_unidad_destino')},
            },
        ),
        migrations.CreateModel(
            name='StockActual',
            fields=[
                ('id_stock_actual', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cantidad_disponible', models.DecimalField(decimal_places=4, default=0.0, max_digits=18)),
                ('cantidad_comprometida', models.DecimalField(decimal_places=4, default=0.0, max_digits=18)),
                ('cantidad_en_transito', models.DecimalField(decimal_places=4, default=0.0, max_digits=18)),
                ('cantidad_minima', models.DecimalField(decimal_places=4, default=0.0, max_digits=18)),
                ('cantidad_maxima', models.DecimalField(decimal_places=4, default=0.0, max_digits=18)),
                ('fecha_ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('id_almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacenes.almacen')),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.producto')),
                ('id_variante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.varianteproducto')),
            ],
            options={
                'verbose_name': 'Stock Actual',
                'verbose_name_plural': 'Stocks Actuales',
                'db_table': 'inventario_stock_actual',
                'unique_together': {('id_producto', 'id_variante', 'id_almacen')},
            },
        ),
    ]
