# Generated by Django 5.2.4 on 2026-05-11 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_usuarios_es_superusuario_omni'),
        ('finanzas', '0034_fix_sesion_caja_unique_constraint'),
        ('fiscal', '0002_delete_pagocontribucionparafiscal'),
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterModelOptions(
            name='unidadmedida',
            options={'verbose_name': 'Unidad de Medida', 'verbose_name_plural': 'Unidades de Medida'},
        ),
        migrations.AlterField(
            model_name='producto',
            name='sku',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='unidadmedida',
            name='abreviatura',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='varianteproducto',
            name='codigo_variante',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='varianteproducto',
            name='sku',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='producto',
            unique_together={('id_empresa', 'sku')},
        ),
        migrations.AlterUniqueTogether(
            name='unidadmedida',
            unique_together={('id_empresa', 'abreviatura')},
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['id_empresa', 'activo'], name='inventario__id_empr_efbd98_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['nombre_producto'], name='inventario__nombre__38f5b8_idx'),
        ),
        migrations.AlterModelTable(
            name='producto',
            table='inventario_producto',
        ),
        migrations.AlterModelTable(
            name='unidadmedida',
            table='inventario_unidad_medida',
        ),
    ]
