# Generated by Django 5.2.4 on 2026-05-15 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_base_model_all_models'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriaproducto',
            options={'verbose_name': 'Categoría de Producto', 'verbose_name_plural': 'Categorías de Producto'},
        ),
        migrations.AlterModelTable(
            name='categoriaproducto',
            table='inventario_categoria_producto',
        ),
    ]
