# Generated by Django 5.2.4 on 2026-06-02 03:16

import apps.core.uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0006_add_reserva_venta_tipo_movimiento"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categoriaproducto",
            name="id_categoria_producto",
            field=models.UUIDField(
                default=apps.core.uuid.uuid7,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="conversionunidadmedida",
            name="id_conversion",
            field=models.UUIDField(
                default=apps.core.uuid.uuid7,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="detallerequisicion",
            name="id_detalle",
            field=models.UUIDField(
                default=apps.core.uuid.uuid7,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="movimientoinventario",
            name="id_movimiento_inventario",
            field=models.UUIDField(
                default=apps.core.uuid.uuid7,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="id_producto",
            field=models.UUIDField(
                default=apps.core.uuid.uuid7,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="requisicioninterna",
            name="activo",
            field=models.BooleanField(
                default=True,
                help_text="Indica si el registro está activo (False = borrado lógico).",
                verbose_name="Activo",
            ),
        ),
        migrations.AlterField(
            model_name="requisicioninterna",
            name="fecha_actualizacion",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Fecha y hora de la última modificación del registro.",
                verbose_name="Fecha de Actualización",
            ),
        ),
        migrations.AlterField(
            model_name="requisicioninterna",
            name="fecha_creacion",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Fecha y hora de creación del registro.",
                verbose_name="Fecha de Creación",
            ),
        ),
        migrations.AlterField(
            model_name="requisicioninterna",
            name="id_requisicion",
            field=models.UUIDField(
                default=apps.core.uuid.uuid7,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="stockactual",
            name="id_stock_actual",
            field=models.UUIDField(
                default=apps.core.uuid.uuid7,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="stockconsignacioncliente",
            name="id_stock_consignacion",
            field=models.UUIDField(
                default=apps.core.uuid.uuid7,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="stockconsignacionproveedor",
            name="id_stock_consignacion",
            field=models.UUIDField(
                default=apps.core.uuid.uuid7,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="unidadmedida",
            name="id_unidad_medida",
            field=models.UUIDField(
                default=apps.core.uuid.uuid7,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="varianteproducto",
            name="id_variante",
            field=models.UUIDField(
                default=apps.core.uuid.uuid7,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
