# Generated by Django 5.2.15 on 2026-06-12 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0008_rls_lote2_inventario"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="punto_reorden",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Stock mínimo a partir del cual se generan alertas de reorden. NULL = sin alerta.",
                max_digits=18,
                null=True,
            ),
        ),
    ]
