# Generated by Django 5.2.15 on 2026-06-23 02:43

import apps.core.uuid
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacenes', '0005_rls_lote3_almacenes'),
        ('core', '0023_rls_lote3_core'),
        ('inventario', '0010_rls_lote3_inventario'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='metodo_valoracion',
            field=models.CharField(choices=[('PROMEDIO', 'Costo Promedio'), ('FIFO', 'FIFO (Primero en Entrar, Primero en Salir)')], default='PROMEDIO', help_text='Método de valoración de inventario usado al costear las salidas de este producto.', max_length=10),
        ),
        migrations.CreateModel(
            name='ValoracionInventario',
            fields=[
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro.', verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última modificación del registro.', verbose_name='Fecha de Actualización')),
                ('id_valoracion', models.UUIDField(default=apps.core.uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('sentido', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida')], max_length=10)),
                ('metodo', models.CharField(choices=[('PROMEDIO', 'Costo Promedio'), ('FIFO', 'FIFO')], max_length=10)),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=18)),
                ('costo_unitario', models.DecimalField(decimal_places=4, max_digits=18)),
                ('valor_total', models.DecimalField(decimal_places=4, max_digits=18)),
                ('cantidad_restante', models.DecimalField(decimal_places=4, default=0, help_text='Unidades de esta capa aún no consumidas (solo aplica a ENTRADA en FIFO).', max_digits=18)),
                ('id_almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valoraciones', to='almacenes.almacen')),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valoraciones_inventario', to='core.empresa')),
                ('id_movimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valoraciones', to='inventario.movimientoinventario')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valoraciones', to='inventario.producto')),
                ('id_variante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='valoraciones', to='inventario.varianteproducto')),
            ],
            options={
                'verbose_name': 'Valoración de Inventario',
                'verbose_name_plural': 'Valoraciones de Inventario',
                'db_table': 'inventario_valoracion_inventario',
                'indexes': [models.Index(fields=['id_empresa', 'id_producto', 'id_variante', 'id_almacen', 'sentido'], name='inv_valoracion_pila_idx')],
            },
        ),
    ]
