# Generated by Django 5.2.15 on 2026-06-23 04:22

import apps.core.uuid
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacenes', '0005_rls_lote3_almacenes'),
        ('core', '0023_rls_lote3_core'),
        ('inventario', '0012_rls_valoracion_inventario'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasoOperacion',
            fields=[
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro.', verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última modificación del registro.', verbose_name='Fecha de Actualización')),
                ('activo', models.BooleanField(default=True, help_text='Indica si el registro está activo (False = borrado lógico).', verbose_name='Activo')),
                ('id_paso_operacion', models.UUIDField(default=apps.core.uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('tipo_operacion', models.CharField(choices=[('RECEPCION', 'Recepción'), ('ENTREGA', 'Entrega')], max_length=12)),
                ('nombre_paso', models.CharField(max_length=100)),
                ('secuencia', models.PositiveIntegerField(help_text='Orden del paso (1 = primero). Debe ser único por almacén y tipo de operación.')),
                ('id_almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pasos_operacion', to='almacenes.almacen')),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pasos_operacion', to='core.empresa')),
            ],
            options={
                'verbose_name': 'Paso de Operación',
                'verbose_name_plural': 'Pasos de Operación',
                'db_table': 'inventario_paso_operacion',
                'ordering': ['id_almacen', 'tipo_operacion', 'secuencia'],
                'unique_together': {('id_almacen', 'tipo_operacion', 'nombre_paso'), ('id_almacen', 'tipo_operacion', 'secuencia')},
            },
        ),
    ]
