# Generated by Django 5.2.15 on 2026-06-23 04:49

import apps.core.uuid
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacenes', '0005_rls_lote3_almacenes'),
        ('core', '0023_rls_lote3_core'),
        ('inventario', '0014_rls_paso_operacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperacionInventario',
            fields=[
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro.', verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última modificación del registro.', verbose_name='Fecha de Actualización')),
                ('activo', models.BooleanField(default=True, help_text='Indica si el registro está activo (False = borrado lógico).', verbose_name='Activo')),
                ('id_operacion', models.UUIDField(default=apps.core.uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=30)),
                ('tipo_operacion', models.CharField(choices=[('RECEPCION', 'Recepción'), ('ENTREGA', 'Entrega')], max_length=12)),
                ('origen_tipo', models.CharField(choices=[('PURCHASE', 'Compra'), ('SALE', 'Venta'), ('TRANSFER', 'Transferencia'), ('RETURN', 'Devolución'), ('SCRAP', 'Desecho')], max_length=12)),
                ('origen_id', models.UUIDField(blank=True, help_text='Documento de origen (OC, NotaVenta, etc.) si aplica.', null=True)),
                ('estado', models.CharField(choices=[('EN_PROCESO', 'En proceso'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada')], default='EN_PROCESO', max_length=12)),
                ('motivo', models.TextField(blank=True, default='', help_text='Obligatorio para devoluciones/desechos.')),
                ('fecha', models.DateTimeField()),
                ('id_almacen', models.ForeignKey(help_text='Almacén que recibe (recepción) o despacha (entrega).', on_delete=django.db.models.deletion.PROTECT, related_name='operaciones_inventario', to='almacenes.almacen')),
                ('id_almacen_contraparte', models.ForeignKey(blank=True, help_text='Almacén destino en transferencias.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operaciones_inventario_contraparte', to='almacenes.almacen')),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operaciones_inventario', to='core.empresa')),
            ],
            options={
                'verbose_name': 'Operación de Inventario',
                'verbose_name_plural': 'Operaciones de Inventario',
                'db_table': 'inventario_operacion_inventario',
                'ordering': ['-fecha'],
                'unique_together': {('id_empresa', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='OperacionInventarioLinea',
            fields=[
                ('id_linea', models.UUIDField(default=apps.core.uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=18)),
                ('costo_unitario', models.DecimalField(blank=True, decimal_places=4, help_text='Costo de recepción; en entregas lo calcula la valoración.', max_digits=18, null=True)),
                ('id_operacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='inventario.operacioninventario')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lineas_operacion', to='inventario.producto')),
                ('id_variante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.varianteproducto')),
            ],
            options={
                'verbose_name': 'Línea de Operación de Inventario',
                'verbose_name_plural': 'Líneas de Operación de Inventario',
                'db_table': 'inventario_operacion_inventario_linea',
            },
        ),
        migrations.CreateModel(
            name='OperacionInventarioPaso',
            fields=[
                ('id_operacion_paso', models.UUIDField(default=apps.core.uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('secuencia', models.PositiveIntegerField()),
                ('nombre_paso', models.CharField(max_length=100)),
                ('confirmado', models.BooleanField(default=False)),
                ('fecha_confirmacion', models.DateTimeField(blank=True, null=True)),
                ('id_operacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pasos', to='inventario.operacioninventario')),
                ('id_usuario_confirmacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pasos_operacion_confirmados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paso de Operación de Inventario',
                'verbose_name_plural': 'Pasos de Operación de Inventario',
                'db_table': 'inventario_operacion_inventario_paso',
                'ordering': ['secuencia'],
                'unique_together': {('id_operacion', 'secuencia')},
            },
        ),
    ]
