# Generated by Django 5.2.15 on 2026-06-24 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0016_rls_operacion_inventario'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='es_comprable',
            field=models.BooleanField(default=True, help_text='Si es False, el producto no puede comprarse (solo-venta).'),
        ),
        migrations.AddField(
            model_name='producto',
            name='es_vendible',
            field=models.BooleanField(default=True, help_text='Si es False, el producto es solo-compra y no puede venderse.'),
        ),
    ]
