# Redpanda Console — configuración para docker-compose dev
# Docs: https://docs.redpanda.com/redpanda-cloud/manage/console/
kafka:
  brokers:
    - redpanda:9092
  schemaRegistry:
    enabled: true
    urls:
      - "http://redpanda:8081"

redpanda:
  adminApi:
    enabled: true
    urls:
      - "http://redpanda:9644"
