# Generated by Django 5.2.4 on 2026-06-02 03:16

import apps.core.uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agentes", "0002_nivelautonomia_configagente"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="prediccionagente",
            new_name="agentes_pre_id_empr_dcf018_idx",
            old_name="agentes_pre_id_empr_idx",
        ),
        migrations.RenameIndex(
            model_name="prediccionagente",
            new_name="agentes_pre_agente_493a0c_idx",
            old_name="agentes_pre_agente_idx",
        ),
        migrations.AlterField(
            model_name="prediccionagente",
            name="agente",
            field=models.CharField(
                choices=[
                    ("clasificador_gastos", "Clasificador de Gastos"),
                    ("cobranza_estratega", "Estratega de Cobranza"),
                    ("reorden_sugeridor", "Sugeridor de Reorden"),
                    ("personalizacion_capa2", "Personalización Capa 2"),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="prediccionagente",
            name="id_prediccion",
            field=models.UUIDField(
                default=apps.core.uuid.uuid7,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
