# Generated by Django 5.2.4 on 2025-08-02 20:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('finanzas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaGasto',
            fields=[
                ('id_categoria_gasto', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id_gasto', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('fecha_gasto', models.DateField()),
                ('descripcion', models.TextField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=18)),
                ('id_empleado_responsable_temp', models.UUIDField(blank=True, null=True)),
                ('estado_gasto', models.CharField(choices=[('PENDIENTE_APROBACION', 'Pendiente Aprobación'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('REEMBOLSADO', 'Reembolsado'), ('CONTABILIZADO', 'Contabilizado')], max_length=20)),
                ('id_usuario_registro_temp', models.UUIDField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_categoria_gasto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gastos.categoriagasto')),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
                ('id_moneda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finanzas.moneda')),
            ],
        ),
        migrations.CreateModel(
            name='ReembolsoGasto',
            fields=[
                ('id_reembolso', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('id_empleado_temp', models.UUIDField(blank=True, null=True)),
                ('monto_reembolso', models.DecimalField(decimal_places=2, max_digits=18)),
                ('fecha_reembolso', models.DateField()),
                ('estado_reembolso', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADO', 'Pagado'), ('ANULADO', 'Anulado')], max_length=20)),
                ('id_usuario_registro_temp', models.UUIDField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
                ('id_gasto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gastos.gasto')),
                ('id_metodo_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finanzas.metodopago')),
                ('id_moneda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finanzas.moneda')),
            ],
        ),
    ]
