# Generated by Django 5.2.4 on 2026-06-02 03:16

import apps.core.uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gastos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categoriagasto",
            name="id_categoria_gasto",
            field=models.UUIDField(
                default=apps.core.uuid.uuid7, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="gasto",
            name="id_gasto",
            field=models.UUIDField(
                default=apps.core.uuid.uuid7, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="reembolsogasto",
            name="id_reembolso",
            field=models.UUIDField(
                default=apps.core.uuid.uuid7, primary_key=True, serialize=False
            ),
        ),
    ]
