# Generated by Django 5.2.15 on 2026-06-23 11:18

import apps.core.uuid
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0013_alter_mapeocontable_tipo_asiento'),
        ('gastos', '0003_rls_lote3_gastos'),
        ('inventario', '0016_rls_operacion_inventario'),
        ('proveedores', '0006_rls_lote3_proveedores'),
        ('rrhh', '0005_rls_lote3_rrhh'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriagasto',
            name='id_cuenta_contable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categorias_gasto', to='contabilidad.plancuentas'),
        ),
        migrations.AddField(
            model_name='categoriagasto',
            name='requiere_factura',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gasto',
            name='id_empleado_responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gastos_responsable', to='rrhh.empleado'),
        ),
        migrations.AddField(
            model_name='gasto',
            name='id_producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gastos', to='inventario.producto'),
        ),
        migrations.AddField(
            model_name='gasto',
            name='id_proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gastos', to='proveedores.proveedor'),
        ),
        migrations.AddField(
            model_name='gasto',
            name='id_usuario_registro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gastos_registrados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gasto',
            name='monto_iva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='gasto',
            name='numero_factura',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gasto',
            name='sin_respaldo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gasto',
            name='tasa_cambio',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=18),
        ),
        migrations.AddField(
            model_name='gasto',
            name='tiene_factura',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reembolsogasto',
            name='id_empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reembolsos', to='rrhh.empleado'),
        ),
        migrations.AddField(
            model_name='reembolsogasto',
            name='id_usuario_registro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reembolsos_registrados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='estado_gasto',
            field=models.CharField(choices=[('PENDIENTE_APROBACION', 'Pendiente Aprobación'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('REEMBOLSADO', 'Reembolsado'), ('CONTABILIZADO', 'Contabilizado')], default='PENDIENTE_APROBACION', max_length=20),
        ),
        migrations.CreateModel(
            name='DetalleGasto',
            fields=[
                ('id_detalle_gasto', models.UUIDField(default=apps.core.uuid.uuid7, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=18)),
                ('monto_iva', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('id_cuenta_contable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_gasto', to='contabilidad.plancuentas')),
                ('id_gasto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='gastos.gasto')),
            ],
        ),
    ]
