# Generated by Django 5.2.4 on 2025-08-02 20:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleFacturaCompra',
            fields=[
                ('id_detalle_factura', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=18)),
                ('precio_unitario', models.DecimalField(decimal_places=4, max_digits=18)),
                ('descuento_porcentaje', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('descuento_monto', models.DecimalField(decimal_places=4, default=0.0, max_digits=18)),
                ('subtotal', models.DecimalField(decimal_places=4, max_digits=18)),
                ('monto_impuesto', models.DecimalField(decimal_places=4, default=0.0, max_digits=18)),
                ('total_linea', models.DecimalField(decimal_places=4, max_digits=18)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Detalle de Factura de Compra',
                'verbose_name_plural': 'Detalles de Factura de Compra',
                'db_table': 'compras_detalle_factura_compra',
            },
        ),
        migrations.CreateModel(
            name='DetalleOfertaProveedor',
            fields=[
                ('id_detalle_oferta', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=18)),
                ('precio_unitario', models.DecimalField(decimal_places=4, max_digits=18)),
                ('subtotal', models.DecimalField(decimal_places=4, max_digits=18)),
                ('tiempo_entrega', models.CharField(blank=True, max_length=100, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Detalle de Oferta',
                'verbose_name_plural': 'Detalles de Oferta',
                'db_table': 'compras_detalle_oferta_proveedor',
            },
        ),
        migrations.CreateModel(
            name='DetalleOrdenCompra',
            fields=[
                ('id_detalle_orden_compra', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=18)),
                ('precio_unitario', models.DecimalField(decimal_places=4, max_digits=18)),
                ('subtotal', models.DecimalField(decimal_places=4, max_digits=18)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleRecepcionMercancia',
            fields=[
                ('id_detalle_recepcion', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cantidad_esperada', models.DecimalField(decimal_places=4, max_digits=18)),
                ('cantidad_recibida', models.DecimalField(decimal_places=4, max_digits=18)),
                ('estado_mercancia', models.CharField(choices=[('CONFORME', 'Conforme'), ('DEFECTUOSO', 'Defectuoso'), ('INCOMPLETO', 'Incompleto'), ('DAÑADO', 'Dañado')], default='CONFORME', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Detalle de Recepción',
                'verbose_name_plural': 'Detalles de Recepción',
                'db_table': 'compras_detalle_recepcion_mercancia',
            },
        ),
        migrations.CreateModel(
            name='DetalleRequisicionCompra',
            fields=[
                ('id_detalle_requisicion', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cantidad_solicitada', models.DecimalField(decimal_places=4, max_digits=18)),
                ('precio_estimado', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('justificacion', models.TextField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Detalle de Requisición',
                'verbose_name_plural': 'Detalles de Requisición',
                'db_table': 'compras_detalle_requisicion_compra',
            },
        ),
        migrations.CreateModel(
            name='DetalleSolicitudCotizacion',
            fields=[
                ('id_detalle_solicitud', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=18)),
                ('especificaciones', models.TextField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Detalle de Solicitud de Cotización',
                'verbose_name_plural': 'Detalles de Solicitud de Cotización',
                'db_table': 'compras_detalle_solicitud_cotizacion',
            },
        ),
        migrations.CreateModel(
            name='FacturaCompra',
            fields=[
                ('id_factura_compra', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('referencia_externa', models.CharField(blank=True, max_length=100, null=True)),
                ('documento_json', models.JSONField(blank=True, null=True)),
                ('numero_factura', models.CharField(max_length=50)),
                ('fecha_emision', models.DateField()),
                ('monto_total', models.DecimalField(decimal_places=4, max_digits=18)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OfertaProveedor',
            fields=[
                ('id_oferta', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_oferta', models.CharField(max_length=50)),
                ('fecha_oferta', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('estado', models.CharField(choices=[('RECIBIDA', 'Recibida'), ('EVALUADA', 'Evaluada'), ('ACEPTADA', 'Aceptada'), ('RECHAZADA', 'Rechazada'), ('VENCIDA', 'Vencida')], default='RECIBIDA', max_length=20)),
                ('monto_total', models.DecimalField(decimal_places=4, default=0.0, max_digits=18)),
                ('condiciones_pago', models.TextField(blank=True, null=True)),
                ('tiempo_entrega', models.CharField(blank=True, max_length=100, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Oferta de Proveedor',
                'verbose_name_plural': 'Ofertas de Proveedores',
                'db_table': 'compras_oferta_proveedor',
            },
        ),
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id_orden_compra', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('referencia_externa', models.CharField(blank=True, max_length=100, null=True)),
                ('documento_json', models.JSONField(blank=True, null=True)),
                ('tipo_operacion', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_cierre_estimada', models.DateField(blank=True, null=True)),
                ('numero_orden', models.CharField(max_length=50, unique=True)),
                ('fecha_orden', models.DateField()),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('ENVIADA', 'Enviada'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada'), ('CERRADA', 'Cerrada'), ('ANULADA', 'Anulada')], default='BORRADOR', max_length=30)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecepcionMercancia',
            fields=[
                ('id_recepcion', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('referencia_externa', models.CharField(blank=True, max_length=100, null=True)),
                ('documento_json', models.JSONField(blank=True, null=True)),
                ('fecha_recepcion', models.DateField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RequisicionCompra',
            fields=[
                ('id_requisicion', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_requisicion', models.CharField(max_length=50, unique=True)),
                ('fecha_requisicion', models.DateField()),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('PENDIENTE', 'Pendiente'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada'), ('PROCESADA', 'Procesada'), ('ANULADA', 'Anulada')], default='BORRADOR', max_length=20)),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='MEDIA', max_length=15)),
                ('fecha_necesidad', models.DateField()),
                ('justificacion', models.TextField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Requisición de Compra',
                'verbose_name_plural': 'Requisiciones de Compra',
                'db_table': 'compras_requisicion_compra',
            },
        ),
        migrations.CreateModel(
            name='SolicitudCotizacion',
            fields=[
                ('id_solicitud_cotizacion', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_solicitud', models.CharField(max_length=50, unique=True)),
                ('fecha_solicitud', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('ENVIADA', 'Enviada'), ('RESPONDIDA', 'Respondida'), ('VENCIDA', 'Vencida'), ('ANULADA', 'Anulada')], default='BORRADOR', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Solicitud de Cotización',
                'verbose_name_plural': 'Solicitudes de Cotización',
                'db_table': 'compras_solicitud_cotizacion',
            },
        ),
    ]
