# Generated by Django 5.2.4 on 2025-08-02 20:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compras', '0001_initial'),
        ('core', '0002_initial'),
        ('inventario', '0001_initial'),
        ('proveedores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='detallefacturacompra',
            name='id_producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_factura_compra', to='inventario.producto'),
        ),
        migrations.AddField(
            model_name='detalleofertaproveedor',
            name='id_producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_oferta', to='inventario.producto'),
        ),
        migrations.AddField(
            model_name='detalleordencompra',
            name='id_producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.producto'),
        ),
        migrations.AddField(
            model_name='detallerecepcionmercancia',
            name='id_producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_recepcion', to='inventario.producto'),
        ),
        migrations.AddField(
            model_name='detallerequisicioncompra',
            name='id_producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_requisicion', to='inventario.producto'),
        ),
        migrations.AddField(
            model_name='detallesolicitudcotizacion',
            name='id_producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_solicitud_cotizacion', to='inventario.producto'),
        ),
        migrations.AddField(
            model_name='detallefacturacompra',
            name='id_factura_compra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='compras.facturacompra'),
        ),
        migrations.AddField(
            model_name='ofertaproveedor',
            name='id_proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas', to='proveedores.proveedor'),
        ),
        migrations.AddField(
            model_name='detalleofertaproveedor',
            name='id_oferta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='compras.ofertaproveedor'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='id_empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='id_proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedores.proveedor'),
        ),
        migrations.AddField(
            model_name='facturacompra',
            name='id_orden_compra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.ordencompra'),
        ),
        migrations.AddField(
            model_name='detalleordencompra',
            name='id_orden_compra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='compras.ordencompra'),
        ),
        migrations.AddField(
            model_name='recepcionmercancia',
            name='id_orden_compra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.ordencompra'),
        ),
        migrations.AddField(
            model_name='detallerecepcionmercancia',
            name='id_recepcion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='compras.recepcionmercancia'),
        ),
        migrations.AddField(
            model_name='requisicioncompra',
            name='id_departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requisiciones', to='core.departamento'),
        ),
        migrations.AddField(
            model_name='requisicioncompra',
            name='id_empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisiciones_compra', to='core.empresa'),
        ),
        migrations.AddField(
            model_name='requisicioncompra',
            name='id_solicitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisiciones_solicitadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detallerequisicioncompra',
            name='id_requisicion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='compras.requisicioncompra'),
        ),
        migrations.AddField(
            model_name='solicitudcotizacion',
            name='id_empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_cotizacion', to='core.empresa'),
        ),
        migrations.AddField(
            model_name='ofertaproveedor',
            name='id_solicitud_cotizacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas', to='compras.solicitudcotizacion'),
        ),
        migrations.AddField(
            model_name='detallesolicitudcotizacion',
            name='id_solicitud_cotizacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='compras.solicitudcotizacion'),
        ),
    ]
