# Generated by Django 5.2.4 on 2026-05-11 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_initial'),
        ('core', '0007_alter_usuarios_es_superusuario_omni'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordencompra',
            options={'ordering': ['-fecha_orden'], 'verbose_name': 'Orden de Compra', 'verbose_name_plural': 'Órdenes de Compra'},
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='numero_orden',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='requisicioncompra',
            name='numero_requisicion',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='solicitudcotizacion',
            name='numero_solicitud',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='ordencompra',
            unique_together={('id_empresa', 'numero_orden')},
        ),
        migrations.AlterUniqueTogether(
            name='requisicioncompra',
            unique_together={('id_empresa', 'numero_requisicion')},
        ),
        migrations.AlterUniqueTogether(
            name='solicitudcotizacion',
            unique_together={('id_empresa', 'numero_solicitud')},
        ),
        migrations.AlterModelTable(
            name='ordencompra',
            table='compras_orden_compra',
        ),
    ]
