# Generated by Django 5.2.4 on 2026-06-02 03:16

import apps.core.uuid
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compras", "0008_recepcionmercancia_id_empresa_not_null"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="facturacompra",
            options={
                "verbose_name": "Factura de Compra",
                "verbose_name_plural": "Facturas de Compra",
            },
        ),
        migrations.AlterModelOptions(
            name="recepcionmercancia",
            options={
                "verbose_name": "Recepción de Mercancía",
                "verbose_name_plural": "Recepciones de Mercancía",
            },
        ),
        migrations.AlterField(
            model_name="detallefacturacompra",
            name="id_detalle_factura",
            field=models.UUIDField(
                default=apps.core.uuid.uuid7,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="detalleofertaproveedor",
            name="id_detalle_oferta",
            field=models.UUIDField(
                default=apps.core.uuid.uuid7,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="detalleordencompra",
            name="id_detalle_orden_compra",
            field=models.UUIDField(
                default=apps.core.uuid.uuid7,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="detallerecepcionmercancia",
            name="cantidad_esperada",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name="detallerecepcionmercancia",
            name="id_detalle_recepcion",
            field=models.UUIDField(
                default=apps.core.uuid.uuid7,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="detallerequisicioncompra",
            name="id_detalle_requisicion",
            field=models.UUIDField(
                default=apps.core.uuid.uuid7,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="detallesolicitudcotizacion",
            name="id_detalle_solicitud",
            field=models.UUIDField(
                default=apps.core.uuid.uuid7,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="facturacompra",
            name="id_factura_compra",
            field=models.UUIDField(
                default=apps.core.uuid.uuid7,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="facturacompra",
            name="id_orden_compra",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="facturas",
                to="compras.ordencompra",
            ),
        ),
        migrations.AlterField(
            model_name="ofertaproveedor",
            name="id_oferta",
            field=models.UUIDField(
                default=apps.core.uuid.uuid7,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="ordencompra",
            name="id_orden_compra",
            field=models.UUIDField(
                default=apps.core.uuid.uuid7,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="recepcionmercancia",
            name="id_orden_compra",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recepciones",
                to="compras.ordencompra",
            ),
        ),
        migrations.AlterField(
            model_name="recepcionmercancia",
            name="id_recepcion",
            field=models.UUIDField(
                default=apps.core.uuid.uuid7,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="requisicioncompra",
            name="id_requisicion",
            field=models.UUIDField(
                default=apps.core.uuid.uuid7,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="solicitudcotizacion",
            name="id_solicitud_cotizacion",
            field=models.UUIDField(
                default=apps.core.uuid.uuid7,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
